// Generated by uniffi-bindgen-js. DO NOT EDIT.
import { UniffiRuntime, UniFFIWriter, UniFFIReader } from './uniffi_runtime.js';

const _rt = await UniffiRuntime.load(new URL('./ffi_custom_types.wasm', import.meta.url), 'ffi_custom_types');

export type Handle = bigint;

export type Url = URL;

// --- Serialization helpers ---

export namespace FfiCustomTypes {
  export function handlesEqual(a: Handle, b: Handle): boolean {
    const _argPtr = _rt.scratchAlloc(2 * 8);
    _rt.writeI64Element(_argPtr, BigInt(a));
    _rt.writeI64Element(_argPtr + 8, BigInt(b));
    const _retPtr = _rt.scratchAlloc(5 * 8);
    try {
      _rt.call('uniffi_ffibuffer_ffi_custom_types_fn_func_handles_equal', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 8);
      const _result = _rt.readBoolElement(_retPtr);
      return _result;
    } finally {
      _rt.scratchReset();
    }
  }
  export function makeHandle(seed: bigint): Handle {
    const _argPtr = _rt.scratchAlloc(1 * 8);
    _rt.writeI64Element(_argPtr, BigInt(seed));
    const _retPtr = _rt.scratchAlloc(5 * 8);
    try {
      _rt.call('uniffi_ffibuffer_ffi_custom_types_fn_func_make_handle', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 8);
      const _result = _rt.readI64Element(_retPtr);
      return _result;
    } finally {
      _rt.scratchReset();
    }
  }
  export function normalizeUrl(url: Url): Url {
    const _ct_url = url.toString();
    const _rb__ct_url = _rt.lowerString(_ct_url);
    const _argPtr = _rt.scratchAlloc(3 * 8);
    _rt.writeRustBufferElements(_argPtr, _rb__ct_url);
    const _retPtr = _rt.scratchAlloc(7 * 8);
    try {
      _rt.call('uniffi_ffibuffer_ffi_custom_types_fn_func_normalize_url', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 24);
      const _result = _rt.liftString(_rt.readRustBufferElements(_retPtr));
      return new URL(_result);
    } finally {
      _rt.scratchReset();
    }
  }
}
