// Generated by uniffi-bindgen-js. DO NOT EDIT.
import __init, * as __bg from './custom_types_bg.js';
export { __init as init };

export type Handle = bigint;

export type Url = URL;

export namespace CustomTypes {
  export function handlesEqual(a: Handle, b: Handle): boolean { return __bg.handles_equal(a, b); }
  export function makeHandle(seed: bigint): Handle { return __bg.make_handle(seed); }
  export function normalizeUrl(url: Url): Url { return new URL(__bg.normalize_url(url.toString())); }
}
