// Generated by uniffi-bindgen-js. DO NOT EDIT.
import __init, * as __bg from './custom_types_bg.js';

function _uniffiEnsureApiIntegrity(): void {
  const bindingsContractVersion = 30;
  const scaffoldingContractVersion: number = (__bg as any).ffi_crate_name_uniffi_contract_version();
  if (bindingsContractVersion !== scaffoldingContractVersion) {
    throw new Error(`UniFFI contract version mismatch: expected ${bindingsContractVersion}, got ${scaffoldingContractVersion}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_handles_equal: number = (__bg as any).uniffi_crate_name_checksum_func_handles_equal();
  if (_checksum_uniffi_crate_name_checksum_func_handles_equal !== 30912) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_handles_equal\`: expected 30912, got ${_checksum_uniffi_crate_name_checksum_func_handles_equal}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_make_handle: number = (__bg as any).uniffi_crate_name_checksum_func_make_handle();
  if (_checksum_uniffi_crate_name_checksum_func_make_handle !== 46527) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_make_handle\`: expected 46527, got ${_checksum_uniffi_crate_name_checksum_func_make_handle}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_normalize_url: number = (__bg as any).uniffi_crate_name_checksum_func_normalize_url();
  if (_checksum_uniffi_crate_name_checksum_func_normalize_url !== 57623) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_normalize_url\`: expected 57623, got ${_checksum_uniffi_crate_name_checksum_func_normalize_url}`);
  }
}
export async function init(...args: Parameters<typeof __init>): Promise<ReturnType<typeof __init>> {
  const result = await __init(...args);
  _uniffiEnsureApiIntegrity();
  return result;
}

export type Handle = bigint;

export type Url = string;

export namespace CustomTypes {
  export function handlesEqual(a: Handle, b: Handle): boolean { return __bg.handles_equal(a, b); }
  export function makeHandle(seed: bigint): Handle { return __bg.make_handle(seed); }
  export function normalizeUrl(url: Url): Url { return __bg.normalize_url(url); }
}
