// Generated by uniffi-bindgen-js. DO NOT EDIT.
import { UniffiRuntime, UniFFIWriter, UniFFIReader } from './uniffi_runtime.js';

const _rt = await UniffiRuntime.load(new URL('./ffi_errors.wasm', import.meta.url), 'ffi_errors');

export class MathError extends Error {
  override readonly name = 'MathError' as const;
  constructor(public readonly tag: 'DivisionByZero' | 'Overflow') {
    super(tag);
  }
  static DivisionByZero(): MathError { return new MathError('DivisionByZero'); }
  static Overflow(): MathError { return new MathError('Overflow'); }
}

export type NetworkErrorVariant =
  | { tag: 'NotFound', url: string }
  | { tag: 'Timeout', afterMs: number }
  | { tag: 'ServerError', code: number, message: string };

export class NetworkError extends Error {
  override readonly name = 'NetworkError' as const;
  constructor(public readonly variant: NetworkErrorVariant) {
    super(variant.tag);
  }
  static NotFound(url: string): NetworkError { return new NetworkError({ tag: 'NotFound', url }); }
  static Timeout(afterMs: number): NetworkError { return new NetworkError({ tag: 'Timeout', afterMs }); }
  static ServerError(code: number, message: string): NetworkError { return new NetworkError({ tag: 'ServerError', code, message }); }
}

export class ParseError extends Error {
  override readonly name = 'ParseError' as const;
  constructor(public readonly tag: 'InvalidInput' | 'MissingSection' | 'SyntaxError') {
    super(tag);
  }
  static InvalidInput(): ParseError { return new ParseError('InvalidInput'); }
  static MissingSection(): ParseError { return new ParseError('MissingSection'); }
  static SyntaxError(): ParseError { return new ParseError('SyntaxError'); }
}

export class Parser {
  private readonly _handle: bigint;
  private _freed = false;
  private _assertLive(): void {
    if (this._freed) throw new Error('Parser object has been freed');
  }
  private constructor(handle: bigint) {
    this._handle = handle;
  }
  /** @internal */
  static _fromHandle(handle: bigint): Parser { return new Parser(handle); }
  /** @throws {ParseError} */
  static create(input: string): Parser {
    const _rb_input = _rt.lowerString(input);
    const _argPtr = _rt.scratchAlloc(3 * 8);
    _rt.writeRustBufferElements(_argPtr, _rb_input);
    const _retPtr = _rt.scratchAlloc(5 * 8);
    _rt.call('uniffi_ffibuffer_ffi_errors_fn_constructor_parser_new', _argPtr, _retPtr);
    _rt.checkCallStatus(_retPtr + 8, (rb) => _liftErrorParseError(rb));
    const _result = _rt.readHandleElement(_retPtr);
    _rt.scratchReset();
    return new Parser(_result);
  }
  /** @throws {ParseError} */
  parseSection(name: string): string {
    this._assertLive();
    const _rb_name = _rt.lowerString(name);
    const _argPtr = _rt.scratchAlloc(4 * 8);
    _rt.writeHandleElement(_argPtr, this._handle);
    _rt.writeRustBufferElements(_argPtr + 8, _rb_name);
    const _retPtr = _rt.scratchAlloc(7 * 8);
    _rt.call('uniffi_ffibuffer_ffi_errors_fn_method_parser_parse_section', _argPtr, _retPtr);
    _rt.checkCallStatus(_retPtr + 24, (rb) => _liftErrorParseError(rb));
    const _result = _rt.liftString(_rt.readRustBufferElements(_retPtr));
    _rt.scratchReset();
    return _result;
  }
  result(): string {
    this._assertLive();
    const _argPtr = _rt.scratchAlloc(1 * 8);
    _rt.writeHandleElement(_argPtr, this._handle);
    const _retPtr = _rt.scratchAlloc(7 * 8);
    _rt.call('uniffi_ffibuffer_ffi_errors_fn_method_parser_result', _argPtr, _retPtr);
    _rt.checkCallStatus(_retPtr + 24);
    const _result = _rt.liftString(_rt.readRustBufferElements(_retPtr));
    _rt.scratchReset();
    return _result;
  }
  /** Releases the underlying WASM resource. Safe to call more than once. */
  free(): void {
    if (this._freed) return;
    this._freed = true;
    _rt.callFree('uniffi_ffi_errors_fn_free_parser', this._handle);
  }
  [Symbol.dispose](): void { this.free(); }
}

// --- Serialization helpers ---

function _liftErrorMathError(rb: any): MathError {
  return _rt.liftFromBuffer(rb, (r) => {
    const ordinal = r.readI32();
    if (ordinal === 1) return new MathError('DivisionByZero');
    if (ordinal === 2) return new MathError('Overflow');
    throw new Error(`Unknown MathError ordinal: ${ordinal}`);
  });
}

function _liftErrorNetworkError(rb: any): NetworkError {
  return _rt.liftFromBuffer(rb, (r) => {
    const ordinal = r.readI32();
    if (ordinal === 1) {
      return new NetworkError({ tag: 'NotFound', url: r.readString() });
    }
    if (ordinal === 2) {
      return new NetworkError({ tag: 'Timeout', afterMs: r.readU32() });
    }
    if (ordinal === 3) {
      return new NetworkError({ tag: 'ServerError', code: r.readU16(), message: r.readString() });
    }
    throw new Error(`Unknown NetworkError ordinal: ${ordinal}`);
  });
}

function _liftErrorParseError(rb: any): ParseError {
  return _rt.liftFromBuffer(rb, (r) => {
    const ordinal = r.readI32();
    if (ordinal === 1) return new ParseError('InvalidInput');
    if (ordinal === 2) return new ParseError('MissingSection');
    if (ordinal === 3) return new ParseError('SyntaxError');
    throw new Error(`Unknown ParseError ordinal: ${ordinal}`);
  });
}

export namespace FfiErrors {
  /** @throws {NetworkError} */
  export function fetchData(url: string): string {
    const _rb_url = _rt.lowerString(url);
    const _argPtr = _rt.scratchAlloc(3 * 8);
    _rt.writeRustBufferElements(_argPtr, _rb_url);
    const _retPtr = _rt.scratchAlloc(7 * 8);
    _rt.call('uniffi_ffibuffer_ffi_errors_fn_func_fetch_data', _argPtr, _retPtr);
    _rt.checkCallStatus(_retPtr + 24, (rb) => _liftErrorNetworkError(rb));
    const _result = _rt.liftString(_rt.readRustBufferElements(_retPtr));
    _rt.scratchReset();
    return _result;
  }
  /** @throws {MathError} */
  export function safeDivide(a: number, b: number): string {
    const _argPtr = _rt.scratchAlloc(2 * 8);
    _rt.writeF64Element(_argPtr, a);
    _rt.writeF64Element(_argPtr + 8, b);
    const _retPtr = _rt.scratchAlloc(7 * 8);
    _rt.call('uniffi_ffibuffer_ffi_errors_fn_func_safe_divide', _argPtr, _retPtr);
    _rt.checkCallStatus(_retPtr + 24, (rb) => _liftErrorMathError(rb));
    const _result = _rt.liftString(_rt.readRustBufferElements(_retPtr));
    _rt.scratchReset();
    return _result;
  }
}
