// Generated by uniffi-bindgen-js. DO NOT EDIT.
import __init, * as __bg from './geometry_bg.js';
export { __init as init };

export interface Point {
  x: number;
  y: number;
}

export type Direction = 'North' | 'South' | 'East' | 'West';

export type Shape =
  | { tag: 'Circle'; radius: number }
  | { tag: 'Rectangle'; width: number; height: number }
  | { tag: 'Point' };

export namespace Geometry {
  export function area(shape: Shape): number { return __bg.area(shape); }
  export function step(p: Point, d: Direction): Point { return __bg.step(p, d); }
  export function translate(p: Point, dx: number, dy: number): Point { return __bg.translate(p, dx, dy); }
}
