// Generated by uniffi-bindgen-js. DO NOT EDIT.
import __init, * as __bg from './geometry_bg.js';

function _uniffiEnsureApiIntegrity(): void {
  const bindingsContractVersion = 30;
  const scaffoldingContractVersion: number = (__bg as any).ffi_crate_name_uniffi_contract_version();
  if (bindingsContractVersion !== scaffoldingContractVersion) {
    throw new Error(`UniFFI contract version mismatch: expected ${bindingsContractVersion}, got ${scaffoldingContractVersion}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_area: number = (__bg as any).uniffi_crate_name_checksum_func_area();
  if (_checksum_uniffi_crate_name_checksum_func_area !== 37837) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_area\`: expected 37837, got ${_checksum_uniffi_crate_name_checksum_func_area}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_step: number = (__bg as any).uniffi_crate_name_checksum_func_step();
  if (_checksum_uniffi_crate_name_checksum_func_step !== 59947) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_step\`: expected 59947, got ${_checksum_uniffi_crate_name_checksum_func_step}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_translate: number = (__bg as any).uniffi_crate_name_checksum_func_translate();
  if (_checksum_uniffi_crate_name_checksum_func_translate !== 31988) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_translate\`: expected 31988, got ${_checksum_uniffi_crate_name_checksum_func_translate}`);
  }
}
export async function init(...args: Parameters<typeof __init>): Promise<ReturnType<typeof __init>> {
  const result = await __init(...args);
  _uniffiEnsureApiIntegrity();
  return result;
}

export interface Config {
  name: string;
  timeout?: number;
  verbose?: boolean;
  label?: string | null;
}

export interface Point {
  x: number;
  y: number;
}

export type Direction = 'North' | 'South' | 'East' | 'West';

export type Shape =
  | { tag: 'Circle', radius: number }
  | { tag: 'Rectangle', width: number, height: number }
  | { tag: 'Point' };

export namespace Geometry {
  export function area(shape: Shape): number { return __bg.area(shape); }
  export function step(p: Point, d: Direction): Point { return __bg.step(p, d); }
  export function translate(p: Point, dx: number, dy: number): Point { return __bg.translate(p, dx, dy); }
}
