// Generated by uniffi-bindgen-js. DO NOT EDIT.
import __init, * as __bg from './callbacks_bg.js';

function _uniffiEnsureApiIntegrity(): void {
  const bindingsContractVersion = 30;
  const scaffoldingContractVersion: number = (__bg as any).ffi_crate_name_uniffi_contract_version();
  if (bindingsContractVersion !== scaffoldingContractVersion) {
    throw new Error(`UniFFI contract version mismatch: expected ${bindingsContractVersion}, got ${scaffoldingContractVersion}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_apply_formatter: number = (__bg as any).uniffi_crate_name_checksum_func_apply_formatter();
  if (_checksum_uniffi_crate_name_checksum_func_apply_formatter !== 41941) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_apply_formatter\`: expected 41941, got ${_checksum_uniffi_crate_name_checksum_func_apply_formatter}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_format_greeting: number = (__bg as any).uniffi_crate_name_checksum_func_format_greeting();
  if (_checksum_uniffi_crate_name_checksum_func_format_greeting !== 63522) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_format_greeting\`: expected 63522, got ${_checksum_uniffi_crate_name_checksum_func_format_greeting}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_formatter_format: number = (__bg as any).uniffi_crate_name_checksum_method_formatter_format();
  if (_checksum_uniffi_crate_name_checksum_method_formatter_format !== 42176) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_formatter_format\`: expected 42176, got ${_checksum_uniffi_crate_name_checksum_method_formatter_format}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_formatter_format_with_prefix: number = (__bg as any).uniffi_crate_name_checksum_method_formatter_format_with_prefix();
  if (_checksum_uniffi_crate_name_checksum_method_formatter_format_with_prefix !== 50743) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_formatter_format_with_prefix\`: expected 50743, got ${_checksum_uniffi_crate_name_checksum_method_formatter_format_with_prefix}`);
  }
}
export async function init(...args: Parameters<typeof __init>): Promise<ReturnType<typeof __init>> {
  const result = await __init(...args);
  _uniffiEnsureApiIntegrity();
  return result;
}

export interface Formatter {
  format(input: string): string;
  formatWithPrefix(prefix: string, input: string): string;
}

export namespace Callbacks {
  export function applyFormatter(fmt: Formatter, template: string): string { return __bg.apply_formatter(fmt, template); }
  export function formatGreeting(fmt: Formatter, name: string): string { return __bg.format_greeting(fmt, name); }
}
