// Generated by uniffi-bindgen-js. DO NOT EDIT.
import __init, * as __bg from './callbacks_bg.js';
export { __init as init };

export interface Formatter {
  format(input: string): string;
  formatWithPrefix(prefix: string, input: string): string;
}

export namespace Callbacks {
  export function applyFormatter(fmt: Formatter, template: string): string { return __bg.apply_formatter(fmt, template); }
  export function formatGreeting(fmt: Formatter, name: string): string { return __bg.format_greeting(fmt, name); }
}
