// Generated by uniffi-bindgen-js. DO NOT EDIT.
import __init, * as __bg from './rich_errors_bg.js';
export { __init as init };

export type NetworkErrorVariant =
  | { tag: 'NotFound', url: string }
  | { tag: 'Timeout', url: string, elapsedMs: number }
  | { tag: 'ServerError', statusCode: number }
  | { tag: 'Unknown' };

export class NetworkError extends Error {
  override readonly name = 'NetworkError' as const;
  constructor(public readonly variant: NetworkErrorVariant) {
    super(variant.tag);
  }
  static NotFound(url: string): NetworkError { return new NetworkError({ tag: 'NotFound', url }); }
  static Timeout(url: string, elapsedMs: number): NetworkError { return new NetworkError({ tag: 'Timeout', url, elapsedMs }); }
  static ServerError(statusCode: number): NetworkError { return new NetworkError({ tag: 'ServerError', statusCode }); }
  static Unknown(): NetworkError { return new NetworkError({ tag: 'Unknown' }); }
}

function _liftNetworkError(e: unknown): never {
  try {
    const raw = typeof e === 'string' ? JSON.parse(e) : (e instanceof Error ? JSON.parse(e.message) : e);
    const tag = raw?.tag as string | undefined;
    if (tag === 'NotFound') throw NetworkError.NotFound(raw.url);
    if (tag === 'Timeout') throw NetworkError.Timeout(raw.url, raw.elapsedMs);
    if (tag === 'ServerError') throw NetworkError.ServerError(raw.statusCode);
    if (tag === 'Unknown') throw NetworkError.Unknown();
  } catch (inner) {
    if (inner instanceof NetworkError) throw inner;
  }
  throw e;
}

export namespace RichErrors {
  export function fetchData(url: string): string {
    try { return __bg.fetch_data(url); } catch (e) { return _liftNetworkError(e); }
  }
  export async function fetchDataAsync(url: string): Promise<string> {
    try { return await __bg.fetch_data_async(url); } catch (e) { return _liftNetworkError(e); }
  }
  export async function fetchWithRetryAsync(url: string, maxRetries: number): Promise<string> {
    try { return await __bg.fetch_with_retry_async(url, maxRetries); } catch (e) { return _liftNetworkError(e); }
  }
  export function fetchWithTimeout(url: string, timeoutMs: number): string {
    try { return __bg.fetch_with_timeout(url, timeoutMs); } catch (e) { return _liftNetworkError(e); }
  }
}
