// Generated by uniffi-bindgen-js. DO NOT EDIT.
import __init, * as __bg from './counter_bg.js';
export { __init as init };

export class Counter {
  private readonly _inner: __bg.Counter;
  private constructor(inner: __bg.Counter) {
    this._inner = inner;
  }
  static new(start: bigint): Counter { return new Counter(new __bg.Counter(start)); }
  decrement(): void { this._inner.decrement(); }
  get(): bigint { return this._inner.get(); }
  increment(): void { this._inner.increment(); }
  resetTo(value: bigint): void { this._inner.resetTo(value); }
  free(): void { this._inner.free(); }
}
