// Generated by uniffi-bindgen-js. DO NOT EDIT.
import { UniffiRuntime, UniFFIWriter, UniFFIReader } from './uniffi_runtime.js';

const _rt = await UniffiRuntime.load(new URL('./counter.wasm', import.meta.url), 'counter');

export class Counter {
  /** @internal */
  readonly _handle: bigint;
  private _freed = false;
  private _assertLive(): void {
    if (this._freed) throw new Error('Counter object has been freed');
  }
  private constructor(handle: bigint) {
    this._handle = handle;
  }
  /** @internal */
  static _fromHandle(handle: bigint): Counter { return new Counter(handle); }
  static create(start: bigint): Counter {
    const _argPtr = _rt.scratchAlloc(1 * 8);
    _rt.writeI64Element(_argPtr, BigInt(start));
    const _retPtr = _rt.scratchAlloc(5 * 8);
    _rt.call('uniffi_ffibuffer_counter_fn_constructor_counter_new', _argPtr, _retPtr);
    _rt.checkCallStatus(_retPtr + 8);
    const _result = _rt.readHandleElement(_retPtr);
    _rt.scratchReset();
    return new Counter(_result);
  }
  decrement(): void {
    this._assertLive();
    const _clonedHandle = _rt.cloneObjectHandle('uniffi_counter_fn_clone_counter', this._handle);
    const _argPtr = _rt.scratchAlloc(1 * 8);
    _rt.writeHandleElement(_argPtr, _clonedHandle);
    const _retPtr = _rt.scratchAlloc(4 * 8);
    _rt.call('uniffi_ffibuffer_counter_fn_method_counter_decrement', _argPtr, _retPtr);
    _rt.checkCallStatus(_retPtr);
    _rt.scratchReset();
  }
  get(): bigint {
    this._assertLive();
    const _clonedHandle = _rt.cloneObjectHandle('uniffi_counter_fn_clone_counter', this._handle);
    const _argPtr = _rt.scratchAlloc(1 * 8);
    _rt.writeHandleElement(_argPtr, _clonedHandle);
    const _retPtr = _rt.scratchAlloc(5 * 8);
    _rt.call('uniffi_ffibuffer_counter_fn_method_counter_get', _argPtr, _retPtr);
    _rt.checkCallStatus(_retPtr + 8);
    const _result = _rt.readI64Element(_retPtr);
    _rt.scratchReset();
    return _result;
  }
  increment(): void {
    this._assertLive();
    const _clonedHandle = _rt.cloneObjectHandle('uniffi_counter_fn_clone_counter', this._handle);
    const _argPtr = _rt.scratchAlloc(1 * 8);
    _rt.writeHandleElement(_argPtr, _clonedHandle);
    const _retPtr = _rt.scratchAlloc(4 * 8);
    _rt.call('uniffi_ffibuffer_counter_fn_method_counter_increment', _argPtr, _retPtr);
    _rt.checkCallStatus(_retPtr);
    _rt.scratchReset();
  }
  resetTo(value: bigint): void {
    this._assertLive();
    const _clonedHandle = _rt.cloneObjectHandle('uniffi_counter_fn_clone_counter', this._handle);
    const _argPtr = _rt.scratchAlloc(2 * 8);
    _rt.writeHandleElement(_argPtr, _clonedHandle);
    _rt.writeI64Element(_argPtr + 8, BigInt(value));
    const _retPtr = _rt.scratchAlloc(4 * 8);
    _rt.call('uniffi_ffibuffer_counter_fn_method_counter_reset_to', _argPtr, _retPtr);
    _rt.checkCallStatus(_retPtr);
    _rt.scratchReset();
  }
  /** Releases the underlying WASM resource. Safe to call more than once. */
  free(): void {
    if (this._freed) return;
    this._freed = true;
    _rt.callFree('uniffi_counter_fn_free_counter', this._handle);
  }
  [Symbol.dispose](): void { this.free(); }
}

// --- Serialization helpers ---
