// Generated by uniffi-bindgen-js. DO NOT EDIT.
import __init, * as __bg from './arithmetic_bg.js';

function _uniffiEnsureApiIntegrity(): void {
  const bindingsContractVersion = 30;
  const scaffoldingContractVersion: number = (__bg as any).ffi_crate_name_uniffi_contract_version();
  if (bindingsContractVersion !== scaffoldingContractVersion) {
    throw new Error(`UniFFI contract version mismatch: expected ${bindingsContractVersion}, got ${scaffoldingContractVersion}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_divide: number = (__bg as any).uniffi_crate_name_checksum_func_divide();
  if (_checksum_uniffi_crate_name_checksum_func_divide !== 3121) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_divide\`: expected 3121, got ${_checksum_uniffi_crate_name_checksum_func_divide}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_sqrt: number = (__bg as any).uniffi_crate_name_checksum_func_sqrt();
  if (_checksum_uniffi_crate_name_checksum_func_sqrt !== 14219) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_sqrt\`: expected 14219, got ${_checksum_uniffi_crate_name_checksum_func_sqrt}`);
  }
}
export async function init(...args: Parameters<typeof __init>): Promise<ReturnType<typeof __init>> {
  const result = await __init(...args);
  _uniffiEnsureApiIntegrity();
  return result;
}

export class MathError extends Error {
  override readonly name = 'MathError' as const;
  constructor(public readonly tag: 'DivisionByZero' | 'NegativeSquareRoot') {
    super(tag);
  }
  static DivisionByZero(): MathError { return new MathError('DivisionByZero'); }
  static NegativeSquareRoot(): MathError { return new MathError('NegativeSquareRoot'); }
}

function _liftMathError(e: unknown): never {
  const tag = typeof e === 'string' ? e : (e instanceof Error ? e.message : null);
  if (tag === 'DivisionByZero') throw new MathError('DivisionByZero');
  if (tag === 'NegativeSquareRoot') throw new MathError('NegativeSquareRoot');
  throw e;
}

export namespace Arithmetic {
  export function divide(a: number, b: number): number {
    try { return __bg.divide(a, b); } catch (e) { return _liftMathError(e); }
  }
  export function sqrt(x: number): number {
    try { return __bg.sqrt(x); } catch (e) { return _liftMathError(e); }
  }
}
