// Generated by uniffi-bindgen-js. DO NOT EDIT.
import { UniffiRuntime, UniFFIWriter, UniFFIReader } from './uniffi_runtime.js';

const _rt = await UniffiRuntime.load(new URL('./arithmetic.wasm', import.meta.url), 'arithmetic');

export class MathError extends Error {
  override readonly name = 'MathError' as const;
  constructor(public readonly tag: 'DivisionByZero' | 'NegativeSquareRoot') {
    super(tag);
  }
  static DivisionByZero(): MathError { return new MathError('DivisionByZero'); }
  static NegativeSquareRoot(): MathError { return new MathError('NegativeSquareRoot'); }
}

// --- Serialization helpers ---

function _liftErrorMathError(rb: any): MathError {
  return _rt.liftFromBuffer(rb, (r) => {
    const ordinal = r.readI32();
    if (ordinal === 1) return new MathError('DivisionByZero');
    if (ordinal === 2) return new MathError('NegativeSquareRoot');
    throw new Error(`Unknown MathError ordinal: ${ordinal}`);
  });
}

export namespace Arithmetic {
  /** @throws {MathError} */
  export function divide(a: number, b: number): number {
    const _argPtr = _rt.scratchAlloc(2 * 8);
    _rt.writeF64Element(_argPtr, a);
    _rt.writeF64Element(_argPtr + 8, b);
    const _retPtr = _rt.scratchAlloc(5 * 8);
    try {
      _rt.call('uniffi_ffibuffer_arithmetic_fn_func_divide', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 8, (rb) => _liftErrorMathError(rb));
      const _result = _rt.readF64Element(_retPtr);
      return _result;
    } finally {
      _rt.scratchReset();
    }
  }
  /** @throws {MathError} */
  export function sqrt(x: number): number {
    const _argPtr = _rt.scratchAlloc(1 * 8);
    _rt.writeF64Element(_argPtr, x);
    const _retPtr = _rt.scratchAlloc(5 * 8);
    try {
      _rt.call('uniffi_ffibuffer_arithmetic_fn_func_sqrt', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 8, (rb) => _liftErrorMathError(rb));
      const _result = _rt.readF64Element(_retPtr);
      return _result;
    } finally {
      _rt.scratchReset();
    }
  }
}
