// Generated by uniffi-bindgen-js. DO NOT EDIT.
import __init, * as __bg from './arithmetic_bg.js';
export { __init as init };

export class MathError extends Error {
  readonly tag: 'DivisionByZero' | 'NegativeSquareRoot';
  constructor(tag: 'DivisionByZero' | 'NegativeSquareRoot') {
    super(tag);
    this.name = 'MathError';
    this.tag = tag;
  }
  static DivisionByZero(): MathError { return new MathError('DivisionByZero'); }
  static NegativeSquareRoot(): MathError { return new MathError('NegativeSquareRoot'); }
}

function _liftMathError(e: unknown): never {
  const tag = typeof e === 'string' ? e : (e instanceof Error ? e.message : null);
  if (tag === 'DivisionByZero') throw new MathError('DivisionByZero');
  if (tag === 'NegativeSquareRoot') throw new MathError('NegativeSquareRoot');
  throw e;
}

export namespace Arithmetic {
  export function divide(a: number, b: number): number {
    try { return __bg.divide(a, b); } catch (e) { return _liftMathError(e); }
  }
  export function sqrt(x: number): number {
    try { return __bg.sqrt(x); } catch (e) { return _liftMathError(e); }
  }
}
