// Generated by uniffi-bindgen-js. DO NOT EDIT.
import { UniffiRuntime, UniFFIWriter, UniFFIReader } from './uniffi_runtime.js';

const _rt = await UniffiRuntime.load(new URL('./ffi_async.wasm', import.meta.url), 'ffi_async');

// --- Serialization helpers ---

export namespace FfiAsync {
  export async function asyncAdd(a: number, b: number): Promise<number> {
    const _argPtr = _rt.scratchAlloc(2 * 8);
    _rt.writeU32Element(_argPtr, a);
    _rt.writeU32Element(_argPtr + 8, b);
    const _retPtr = _rt.scratchAlloc(1 * 8);
    _rt.call('uniffi_ffibuffer_ffi_async_fn_func_async_add', _argPtr, _retPtr);
    const _futureHandle = _rt.readHandleElement(_retPtr);
    try {
      await _rt.pollToReady(_futureHandle, 'ffi_ffi_async_rust_future_poll_u32');
      _rt.scratchReset();
      const _statusPtr = _rt.scratchAlloc(32);
      _rt._writeRustCallStatusStruct(_statusPtr);
      const _rawResult = (_rt.getExport('ffi_ffi_async_rust_future_complete_u32') as any)(_futureHandle, _statusPtr);
      _rt.checkCallStatus(_statusPtr);
      _rt.scratchReset();
      return _rawResult;
    } finally {
      (_rt.getExport('ffi_ffi_async_rust_future_free_u32') as any)(_futureHandle);
    }
  }
  export async function asyncGreet(name: string): Promise<string> {
    const _rb_name = _rt.lowerString(name);
    const _argPtr = _rt.scratchAlloc(3 * 8);
    _rt.writeRustBufferElements(_argPtr, _rb_name);
    const _retPtr = _rt.scratchAlloc(1 * 8);
    _rt.call('uniffi_ffibuffer_ffi_async_fn_func_async_greet', _argPtr, _retPtr);
    const _futureHandle = _rt.readHandleElement(_retPtr);
    try {
      await _rt.pollToReady(_futureHandle, 'ffi_ffi_async_rust_future_poll_rust_buffer');
      _rt.scratchReset();
      const _rbRetPtr = _rt.scratchAlloc(24);
      const _statusPtr = _rt.scratchAlloc(32);
      _rt._writeRustCallStatusStruct(_statusPtr);
      (_rt.getExport('ffi_ffi_async_rust_future_complete_rust_buffer') as any)(_rbRetPtr, _futureHandle, _statusPtr);
      _rt.checkCallStatus(_statusPtr);
      const _result = _rt.liftString(_rt._readRustBufferStruct(_rbRetPtr));
      _rt.scratchReset();
      return _result;
    } finally {
      (_rt.getExport('ffi_ffi_async_rust_future_free_rust_buffer') as any)(_futureHandle);
    }
  }
  export async function asyncNoop(): Promise<void> {
    const _argPtr = 0;
    const _retPtr = _rt.scratchAlloc(1 * 8);
    _rt.call('uniffi_ffibuffer_ffi_async_fn_func_async_noop', _argPtr, _retPtr);
    const _futureHandle = _rt.readHandleElement(_retPtr);
    try {
      await _rt.pollToReady(_futureHandle, 'ffi_ffi_async_rust_future_poll_void');
      _rt.scratchReset();
      const _statusPtr = _rt.scratchAlloc(32);
      _rt._writeRustCallStatusStruct(_statusPtr);
      (_rt.getExport('ffi_ffi_async_rust_future_complete_void') as any)(_futureHandle, _statusPtr);
      _rt.checkCallStatus(_statusPtr);
      _rt.scratchReset();
    } finally {
      (_rt.getExport('ffi_ffi_async_rust_future_free_void') as any)(_futureHandle);
    }
  }
}
