// Generated by uniffi-bindgen-js. DO NOT EDIT.
import __init, * as __bg from './traits_bg.js';
export { __init as init };

export class Drawable {
  private readonly _inner: __bg.Drawable;
  private constructor(inner: __bg.Drawable) {
    this._inner = inner;
  }
  static _fromInner(inner: __bg.Drawable): Drawable { return new Drawable(inner); }
  area(): number { return this._inner.area(); }
  describe(): string { return this._inner.describe(); }
  free(): void { this._inner.free(); }
}

export namespace Traits {
  export function makeCircle(radius: number): Drawable { return Drawable._fromInner(__bg.make_circle(radius)); }
  export function makeRect(width: number, height: number): Drawable { return Drawable._fromInner(__bg.make_rect(width, height)); }
}
