// Generated by uniffi-bindgen-js. DO NOT EDIT.
import { UniffiRuntime, UniFFIWriter, UniFFIReader } from './uniffi_runtime.js';

const _rt = await UniffiRuntime.load(new URL('./traits.wasm', import.meta.url), 'traits');

export interface TraitRecord {
  name: string;
  value: number;
}
export namespace TraitRecord {
  export function toString(value: TraitRecord): string {
    const _rb_value = _rt.lowerIntoBuffer((w) => { _lowerTraitRecord(w, value); });
    const _argPtr = _rt.scratchAlloc(3 * 8);
    _rt.writeRustBufferElements(_argPtr, _rb_value);
    const _retPtr = _rt.scratchAlloc(7 * 8);
    _rt.call('uniffi_ffibuffer_traits_fn_method_traitrecord_uniffi_trait_display', _argPtr, _retPtr);
    _rt.checkCallStatus(_retPtr + 24);
    const _result = _rt.liftString(_rt.readRustBufferElements(_retPtr));
    _rt.scratchReset();
    return _result;
  }
  export function equals(value: TraitRecord, other: TraitRecord): boolean {
    const _rb_value = _rt.lowerIntoBuffer((w) => { _lowerTraitRecord(w, value); });
    const _rb_other = _rt.lowerIntoBuffer((w) => { _lowerTraitRecord(w, other); });
    const _argPtr = _rt.scratchAlloc(6 * 8);
    _rt.writeRustBufferElements(_argPtr, _rb_value);
    _rt.writeRustBufferElements(_argPtr + 24, _rb_other);
    const _retPtr = _rt.scratchAlloc(5 * 8);
    _rt.call('uniffi_ffibuffer_traits_fn_method_traitrecord_uniffi_trait_eq_eq', _argPtr, _retPtr);
    _rt.checkCallStatus(_retPtr + 8);
    const _result = _rt.readBoolElement(_retPtr);
    _rt.scratchReset();
    return _result;
  }
  export function hashCode(value: TraitRecord): bigint {
    const _rb_value = _rt.lowerIntoBuffer((w) => { _lowerTraitRecord(w, value); });
    const _argPtr = _rt.scratchAlloc(3 * 8);
    _rt.writeRustBufferElements(_argPtr, _rb_value);
    const _retPtr = _rt.scratchAlloc(5 * 8);
    _rt.call('uniffi_ffibuffer_traits_fn_method_traitrecord_uniffi_trait_hash', _argPtr, _retPtr);
    _rt.checkCallStatus(_retPtr + 8);
    const _result = _rt.readU64Element(_retPtr);
    _rt.scratchReset();
    return _result;
  }
}

export type TraitColor = 'Red' | 'Green' | 'Blue';

export class Drawable {
  /** @internal */
  readonly _handle: bigint;
  private _freed = false;
  private _assertLive(): void {
    if (this._freed) throw new Error('Drawable object has been freed');
  }
  private constructor(handle: bigint) {
    this._handle = handle;
  }
  /** @internal */
  static _fromHandle(handle: bigint): Drawable { return new Drawable(handle); }
  area(): number {
    this._assertLive();
    const _clonedHandle = _rt.cloneObjectHandle('uniffi_traits_fn_clone_drawable', this._handle);
    const _argPtr = _rt.scratchAlloc(1 * 8);
    _rt.writeHandleElement(_argPtr, _clonedHandle);
    const _retPtr = _rt.scratchAlloc(5 * 8);
    _rt.call('uniffi_ffibuffer_traits_fn_method_drawable_area', _argPtr, _retPtr);
    _rt.checkCallStatus(_retPtr + 8);
    const _result = _rt.readF64Element(_retPtr);
    _rt.scratchReset();
    return _result;
  }
  describe(): string {
    this._assertLive();
    const _clonedHandle = _rt.cloneObjectHandle('uniffi_traits_fn_clone_drawable', this._handle);
    const _argPtr = _rt.scratchAlloc(1 * 8);
    _rt.writeHandleElement(_argPtr, _clonedHandle);
    const _retPtr = _rt.scratchAlloc(7 * 8);
    _rt.call('uniffi_ffibuffer_traits_fn_method_drawable_describe', _argPtr, _retPtr);
    _rt.checkCallStatus(_retPtr + 24);
    const _result = _rt.liftString(_rt.readRustBufferElements(_retPtr));
    _rt.scratchReset();
    return _result;
  }
  /** Releases the underlying WASM resource. Safe to call more than once. */
  free(): void {
    if (this._freed) return;
    this._freed = true;
    _rt.callFree('uniffi_traits_fn_free_drawable', this._handle);
  }
  [Symbol.dispose](): void { this.free(); }
}

// --- Serialization helpers ---

function _lowerTraitRecord(w: UniFFIWriter, value: TraitRecord): void {
  w.writeString(value.name);
  w.writeU32(value.value);
}
function _liftTraitRecord(r: UniFFIReader): TraitRecord {
  return {
    name: r.readString(),
    value: r.readU32(),
  };
}

function _lowerTraitColor(w: UniFFIWriter, value: TraitColor): void {
  if (value === 'Red') { w.writeI32(1); return; }
  if (value === 'Green') { w.writeI32(2); return; }
  if (value === 'Blue') { w.writeI32(3); return; }
  throw new Error(`Unknown TraitColor variant: ${value}`);
}
function _liftTraitColor(r: UniFFIReader): TraitColor {
  const ordinal = r.readI32();
  if (ordinal === 1) return 'Red';
  if (ordinal === 2) return 'Green';
  if (ordinal === 3) return 'Blue';
  throw new Error(`Unknown TraitColor ordinal: ${ordinal}`);
}

export namespace Traits {
  export function makeCircle(radius: number): Drawable {
    const _argPtr = _rt.scratchAlloc(1 * 8);
    _rt.writeF64Element(_argPtr, radius);
    const _retPtr = _rt.scratchAlloc(5 * 8);
    _rt.call('uniffi_ffibuffer_traits_fn_func_make_circle', _argPtr, _retPtr);
    _rt.checkCallStatus(_retPtr + 8);
    const _result = _rt.readHandleElement(_retPtr);
    _rt.scratchReset();
    return Drawable._fromHandle(_result);
  }
  export function makeRect(width: number, height: number): Drawable {
    const _argPtr = _rt.scratchAlloc(2 * 8);
    _rt.writeF64Element(_argPtr, width);
    _rt.writeF64Element(_argPtr + 8, height);
    const _retPtr = _rt.scratchAlloc(5 * 8);
    _rt.call('uniffi_ffibuffer_traits_fn_func_make_rect', _argPtr, _retPtr);
    _rt.checkCallStatus(_retPtr + 8);
    const _result = _rt.readHandleElement(_retPtr);
    _rt.scratchReset();
    return Drawable._fromHandle(_result);
  }
}
