// Generated by uniffi-bindgen-js. DO NOT EDIT.
import __init, * as __bg from './coverall_demo_bg.js';

function _uniffiEnsureApiIntegrity(): void {
  const bindingsContractVersion = 30;
  const scaffoldingContractVersion: number = (__bg as any).ffi_crate_name_uniffi_contract_version();
  if (bindingsContractVersion !== scaffoldingContractVersion) {
    throw new Error(`UniFFI contract version mismatch: expected ${bindingsContractVersion}, got ${scaffoldingContractVersion}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_ancestor_names: number = (__bg as any).uniffi_crate_name_checksum_func_ancestor_names();
  if (_checksum_uniffi_crate_name_checksum_func_ancestor_names !== 32092) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_ancestor_names\`: expected 32092, got ${_checksum_uniffi_crate_name_checksum_func_ancestor_names}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_create_none_dict: number = (__bg as any).uniffi_crate_name_checksum_func_create_none_dict();
  if (_checksum_uniffi_crate_name_checksum_func_create_none_dict !== 59197) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_create_none_dict\`: expected 59197, got ${_checksum_uniffi_crate_name_checksum_func_create_none_dict}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_create_patch: number = (__bg as any).uniffi_crate_name_checksum_func_create_patch();
  if (_checksum_uniffi_crate_name_checksum_func_create_patch !== 45585) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_create_patch\`: expected 45585, got ${_checksum_uniffi_crate_name_checksum_func_create_patch}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_create_some_dict: number = (__bg as any).uniffi_crate_name_checksum_func_create_some_dict();
  if (_checksum_uniffi_crate_name_checksum_func_create_some_dict !== 59765) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_create_some_dict\`: expected 59765, got ${_checksum_uniffi_crate_name_checksum_func_create_some_dict}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_divide_by_text: number = (__bg as any).uniffi_crate_name_checksum_func_divide_by_text();
  if (_checksum_uniffi_crate_name_checksum_func_divide_by_text !== 35670) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_divide_by_text\`: expected 35670, got ${_checksum_uniffi_crate_name_checksum_func_divide_by_text}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_get_int_map: number = (__bg as any).uniffi_crate_name_checksum_func_get_int_map();
  if (_checksum_uniffi_crate_name_checksum_func_get_int_map !== 13540) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_get_int_map\`: expected 13540, got ${_checksum_uniffi_crate_name_checksum_func_get_int_map}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_get_maybe_simple_dict: number = (__bg as any).uniffi_crate_name_checksum_func_get_maybe_simple_dict();
  if (_checksum_uniffi_crate_name_checksum_func_get_maybe_simple_dict !== 52642) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_get_maybe_simple_dict\`: expected 52642, got ${_checksum_uniffi_crate_name_checksum_func_get_maybe_simple_dict}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_get_num_alive: number = (__bg as any).uniffi_crate_name_checksum_func_get_num_alive();
  if (_checksum_uniffi_crate_name_checksum_func_get_num_alive !== 52390) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_get_num_alive\`: expected 52390, got ${_checksum_uniffi_crate_name_checksum_func_get_num_alive}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_make_rust_getters: number = (__bg as any).uniffi_crate_name_checksum_func_make_rust_getters();
  if (_checksum_uniffi_crate_name_checksum_func_make_rust_getters !== 31082) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_make_rust_getters\`: expected 31082, got ${_checksum_uniffi_crate_name_checksum_func_make_rust_getters}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_println: number = (__bg as any).uniffi_crate_name_checksum_func_println();
  if (_checksum_uniffi_crate_name_checksum_func_println !== 14318) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_println\`: expected 14318, got ${_checksum_uniffi_crate_name_checksum_func_println}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_reverse_bytes: number = (__bg as any).uniffi_crate_name_checksum_func_reverse_bytes();
  if (_checksum_uniffi_crate_name_checksum_func_reverse_bytes !== 20911) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_reverse_bytes\`: expected 20911, got ${_checksum_uniffi_crate_name_checksum_func_reverse_bytes}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_test_getters: number = (__bg as any).uniffi_crate_name_checksum_func_test_getters();
  if (_checksum_uniffi_crate_name_checksum_func_test_getters !== 40682) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_test_getters\`: expected 40682, got ${_checksum_uniffi_crate_name_checksum_func_test_getters}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_coveralls_clone_me: number = (__bg as any).uniffi_crate_name_checksum_method_coveralls_clone_me();
  if (_checksum_uniffi_crate_name_checksum_method_coveralls_clone_me !== 58508) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_coveralls_clone_me\`: expected 58508, got ${_checksum_uniffi_crate_name_checksum_method_coveralls_clone_me}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_coveralls_get_metadata: number = (__bg as any).uniffi_crate_name_checksum_method_coveralls_get_metadata();
  if (_checksum_uniffi_crate_name_checksum_method_coveralls_get_metadata !== 31141) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_coveralls_get_metadata\`: expected 31141, got ${_checksum_uniffi_crate_name_checksum_method_coveralls_get_metadata}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_coveralls_get_name: number = (__bg as any).uniffi_crate_name_checksum_method_coveralls_get_name();
  if (_checksum_uniffi_crate_name_checksum_method_coveralls_get_name !== 25929) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_coveralls_get_name\`: expected 25929, got ${_checksum_uniffi_crate_name_checksum_method_coveralls_get_name}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_coveralls_get_other: number = (__bg as any).uniffi_crate_name_checksum_method_coveralls_get_other();
  if (_checksum_uniffi_crate_name_checksum_method_coveralls_get_other !== 22943) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_coveralls_get_other\`: expected 22943, got ${_checksum_uniffi_crate_name_checksum_method_coveralls_get_other}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_coveralls_get_tags: number = (__bg as any).uniffi_crate_name_checksum_method_coveralls_get_tags();
  if (_checksum_uniffi_crate_name_checksum_method_coveralls_get_tags !== 58217) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_coveralls_get_tags\`: expected 58217, got ${_checksum_uniffi_crate_name_checksum_method_coveralls_get_tags}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_coveralls_maybe_throw: number = (__bg as any).uniffi_crate_name_checksum_method_coveralls_maybe_throw();
  if (_checksum_uniffi_crate_name_checksum_method_coveralls_maybe_throw !== 33331) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_coveralls_maybe_throw\`: expected 33331, got ${_checksum_uniffi_crate_name_checksum_method_coveralls_maybe_throw}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_coveralls_maybe_throw_complex: number = (__bg as any).uniffi_crate_name_checksum_method_coveralls_maybe_throw_complex();
  if (_checksum_uniffi_crate_name_checksum_method_coveralls_maybe_throw_complex !== 24041) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_coveralls_maybe_throw_complex\`: expected 24041, got ${_checksum_uniffi_crate_name_checksum_method_coveralls_maybe_throw_complex}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_coveralls_reverse_bytes: number = (__bg as any).uniffi_crate_name_checksum_method_coveralls_reverse_bytes();
  if (_checksum_uniffi_crate_name_checksum_method_coveralls_reverse_bytes !== 28911) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_coveralls_reverse_bytes\`: expected 28911, got ${_checksum_uniffi_crate_name_checksum_method_coveralls_reverse_bytes}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_coveralls_set_name: number = (__bg as any).uniffi_crate_name_checksum_method_coveralls_set_name();
  if (_checksum_uniffi_crate_name_checksum_method_coveralls_set_name !== 10857) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_coveralls_set_name\`: expected 10857, got ${_checksum_uniffi_crate_name_checksum_method_coveralls_set_name}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_coveralls_strong_count: number = (__bg as any).uniffi_crate_name_checksum_method_coveralls_strong_count();
  if (_checksum_uniffi_crate_name_checksum_method_coveralls_strong_count !== 23642) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_coveralls_strong_count\`: expected 23642, got ${_checksum_uniffi_crate_name_checksum_method_coveralls_strong_count}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_coveralls_take_other: number = (__bg as any).uniffi_crate_name_checksum_method_coveralls_take_other();
  if (_checksum_uniffi_crate_name_checksum_method_coveralls_take_other !== 64379) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_coveralls_take_other\`: expected 64379, got ${_checksum_uniffi_crate_name_checksum_method_coveralls_take_other}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_falliblepatch_get_color: number = (__bg as any).uniffi_crate_name_checksum_method_falliblepatch_get_color();
  if (_checksum_uniffi_crate_name_checksum_method_falliblepatch_get_color !== 47454) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_falliblepatch_get_color\`: expected 47454, got ${_checksum_uniffi_crate_name_checksum_method_falliblepatch_get_color}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_nodea_get_partner: number = (__bg as any).uniffi_crate_name_checksum_method_nodea_get_partner();
  if (_checksum_uniffi_crate_name_checksum_method_nodea_get_partner !== 50601) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_nodea_get_partner\`: expected 50601, got ${_checksum_uniffi_crate_name_checksum_method_nodea_get_partner}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_nodeb_get_partner: number = (__bg as any).uniffi_crate_name_checksum_method_nodeb_get_partner();
  if (_checksum_uniffi_crate_name_checksum_method_nodeb_get_partner !== 49612) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_nodeb_get_partner\`: expected 49612, got ${_checksum_uniffi_crate_name_checksum_method_nodeb_get_partner}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_patch_get_color: number = (__bg as any).uniffi_crate_name_checksum_method_patch_get_color();
  if (_checksum_uniffi_crate_name_checksum_method_patch_get_color !== 7243) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_patch_get_color\`: expected 7243, got ${_checksum_uniffi_crate_name_checksum_method_patch_get_color}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_threadsafecounter_get_count: number = (__bg as any).uniffi_crate_name_checksum_method_threadsafecounter_get_count();
  if (_checksum_uniffi_crate_name_checksum_method_threadsafecounter_get_count !== 36276) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_threadsafecounter_get_count\`: expected 36276, got ${_checksum_uniffi_crate_name_checksum_method_threadsafecounter_get_count}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_threadsafecounter_increment: number = (__bg as any).uniffi_crate_name_checksum_method_threadsafecounter_increment();
  if (_checksum_uniffi_crate_name_checksum_method_threadsafecounter_increment !== 17778) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_threadsafecounter_increment\`: expected 17778, got ${_checksum_uniffi_crate_name_checksum_method_threadsafecounter_increment}`);
  }
  const _checksum_uniffi_crate_name_checksum_constructor_coveralls_fallible_new: number = (__bg as any).uniffi_crate_name_checksum_constructor_coveralls_fallible_new();
  if (_checksum_uniffi_crate_name_checksum_constructor_coveralls_fallible_new !== 6836) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_constructor_coveralls_fallible_new\`: expected 6836, got ${_checksum_uniffi_crate_name_checksum_constructor_coveralls_fallible_new}`);
  }
  const _checksum_uniffi_crate_name_checksum_constructor_coveralls_new: number = (__bg as any).uniffi_crate_name_checksum_constructor_coveralls_new();
  if (_checksum_uniffi_crate_name_checksum_constructor_coveralls_new !== 1263) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_constructor_coveralls_new\`: expected 1263, got ${_checksum_uniffi_crate_name_checksum_constructor_coveralls_new}`);
  }
  const _checksum_uniffi_crate_name_checksum_constructor_falliblepatch_new: number = (__bg as any).uniffi_crate_name_checksum_constructor_falliblepatch_new();
  if (_checksum_uniffi_crate_name_checksum_constructor_falliblepatch_new !== 12136) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_constructor_falliblepatch_new\`: expected 12136, got ${_checksum_uniffi_crate_name_checksum_constructor_falliblepatch_new}`);
  }
  const _checksum_uniffi_crate_name_checksum_constructor_patch_new: number = (__bg as any).uniffi_crate_name_checksum_constructor_patch_new();
  if (_checksum_uniffi_crate_name_checksum_constructor_patch_new !== 2665) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_constructor_patch_new\`: expected 2665, got ${_checksum_uniffi_crate_name_checksum_constructor_patch_new}`);
  }
  const _checksum_uniffi_crate_name_checksum_constructor_threadsafecounter_new: number = (__bg as any).uniffi_crate_name_checksum_constructor_threadsafecounter_new();
  if (_checksum_uniffi_crate_name_checksum_constructor_threadsafecounter_new !== 57006) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_constructor_threadsafecounter_new\`: expected 57006, got ${_checksum_uniffi_crate_name_checksum_constructor_threadsafecounter_new}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_getters_get_bool: number = (__bg as any).uniffi_crate_name_checksum_method_getters_get_bool();
  if (_checksum_uniffi_crate_name_checksum_method_getters_get_bool !== 55542) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_getters_get_bool\`: expected 55542, got ${_checksum_uniffi_crate_name_checksum_method_getters_get_bool}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_getters_get_string: number = (__bg as any).uniffi_crate_name_checksum_method_getters_get_string();
  if (_checksum_uniffi_crate_name_checksum_method_getters_get_string !== 61353) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_getters_get_string\`: expected 61353, got ${_checksum_uniffi_crate_name_checksum_method_getters_get_string}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_getters_get_option: number = (__bg as any).uniffi_crate_name_checksum_method_getters_get_option();
  if (_checksum_uniffi_crate_name_checksum_method_getters_get_option !== 62176) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_getters_get_option\`: expected 62176, got ${_checksum_uniffi_crate_name_checksum_method_getters_get_option}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_getters_get_list: number = (__bg as any).uniffi_crate_name_checksum_method_getters_get_list();
  if (_checksum_uniffi_crate_name_checksum_method_getters_get_list !== 61896) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_getters_get_list\`: expected 61896, got ${_checksum_uniffi_crate_name_checksum_method_getters_get_list}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_getters_get_nothing: number = (__bg as any).uniffi_crate_name_checksum_method_getters_get_nothing();
  if (_checksum_uniffi_crate_name_checksum_method_getters_get_nothing !== 22876) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_getters_get_nothing\`: expected 22876, got ${_checksum_uniffi_crate_name_checksum_method_getters_get_nothing}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_nodetrait_name: number = (__bg as any).uniffi_crate_name_checksum_method_nodetrait_name();
  if (_checksum_uniffi_crate_name_checksum_method_nodetrait_name !== 46427) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_nodetrait_name\`: expected 46427, got ${_checksum_uniffi_crate_name_checksum_method_nodetrait_name}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_nodetrait_set_parent: number = (__bg as any).uniffi_crate_name_checksum_method_nodetrait_set_parent();
  if (_checksum_uniffi_crate_name_checksum_method_nodetrait_set_parent !== 14407) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_nodetrait_set_parent\`: expected 14407, got ${_checksum_uniffi_crate_name_checksum_method_nodetrait_set_parent}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_nodetrait_get_parent: number = (__bg as any).uniffi_crate_name_checksum_method_nodetrait_get_parent();
  if (_checksum_uniffi_crate_name_checksum_method_nodetrait_get_parent !== 18470) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_nodetrait_get_parent\`: expected 18470, got ${_checksum_uniffi_crate_name_checksum_method_nodetrait_get_parent}`);
  }
}
export async function init(...args: Parameters<typeof __init>): Promise<ReturnType<typeof __init>> {
  const result = await __init(...args);
  _uniffiEnsureApiIntegrity();
  return result;
}

export type ComplexErrorVariant =
  | { tag: 'OsError', code: number, extendedCode: number }
  | { tag: 'PermissionDenied', reason: string }
  | { tag: 'UnknownError' };

/** Rich error with structured variant data. */
export class ComplexError extends Error {
  override readonly name = 'ComplexError' as const;
  constructor(public readonly variant: ComplexErrorVariant) {
    super(variant.tag);
  }
  static OsError(code: number, extendedCode: number): ComplexError { return new ComplexError({ tag: 'OsError', code, extendedCode }); }
  static PermissionDenied(reason: string): ComplexError { return new ComplexError({ tag: 'PermissionDenied', reason }); }
  static UnknownError(): ComplexError { return new ComplexError({ tag: 'UnknownError' }); }
}

/** Simple flat error (single tag discriminator). */
export class CoverallError extends Error {
  override readonly name = 'CoverallError' as const;
  constructor(public readonly tag: 'TooManyHoles') {
    super(tag);
  }
  static TooManyHoles(): CoverallError { return new CoverallError('TooManyHoles'); }
}

/** Primary test record with a rich set of field types. */
export interface SimpleDict {
  text: string;
  maybeCount: bigint;
  flag: boolean;
  color: Color;
  tags: string[];
  counts: Map<string, bigint>;
  maybeText: string | null;
  maybePatch: Patch | null;
}

/** Simple three-variant flat enum. */
export type Color = 'Red' | 'Blue' | 'Green';

/** Enum wrapping a record — tests enum-with-associated-data. */
export type MaybeSimpleDict =
  | { tag: 'Yeah', value: SimpleDict }
  | { tag: 'Nah' };

/** Callback interface exercising multiple return types and error paths. */
export interface Getters {
  getBool(v: boolean, arg2: boolean): boolean;
  getString(v: string, arg2: boolean): string;
  getOption(v: string, arg2: boolean): string | null;
  getList(v: number[], arg2: boolean): number[];
  getNothing(v: string): void;
}

/** Callback interface for tree-like trait object graphs. */
export interface NodeTrait {
  name(): string;
  setParent(parent: NodeTrait | null): void;
  getParent(): NodeTrait | null;
}

/** Main object exercising self-references, state, errors, and Arc semantics. */
export class Coveralls {
  private readonly _inner: __bg.Coveralls;
  private _freed = false;
  private _assertLive(): void {
    if (this._freed) throw new Error('Coveralls object has been freed');
  }
  private constructor(inner: __bg.Coveralls) {
    this._inner = inner;
  }
  /** @internal */
  static _fromInner(inner: __bg.Coveralls): Coveralls { return new Coveralls(inner); }
  static new(name: string): Coveralls { return Coveralls._fromInner(new __bg.Coveralls(name)); }
  static fallibleNew(name: string, shouldFail: boolean): Coveralls {
    try { return Coveralls._fromInner(__bg.coveralls_fallible_new(name, shouldFail)); } catch (e) { return _liftCoverallError(e); }
  }
  /** Clone into a new instance (tests object return from method). */
  cloneMe(): Coveralls {
    this._assertLive();
    return Coveralls._fromInner(this._inner.clone_me());
  }
  /** Return a map with string keys and optional string values. */
  getMetadata(): Map<string, string | null> {
    this._assertLive();
    return this._inner.get_metadata();
  }
  getName(): string {
    this._assertLive();
    return this._inner.get_name();
  }
  getOther(): Coveralls | null {
    this._assertLive();
    return ((__v) => __v == null ? null : Coveralls._fromInner(__v))(this._inner.get_other());
  }
  /** Return a sequence of optional strings. */
  getTags(): (string | null)[] {
    this._assertLive();
    return this._inner.get_tags();
  }
  /** Method that always throws a simple error. */
  maybeThrow(shouldThrow: boolean): boolean {
    this._assertLive();
    try { return this._inner.maybe_throw(shouldThrow); } catch (e) { return _liftCoverallError(e); }
  }
  /** Method that throws a complex (rich) error. */
  maybeThrowComplex(selector: number): boolean {
    this._assertLive();
    try { return this._inner.maybe_throw_complex(selector); } catch (e) { return _liftComplexError(e); }
  }
  /** Reverse some bytes via a method (tests binary on object). */
  reverseBytes(input: Uint8Array): Uint8Array {
    this._assertLive();
    return this._inner.reverse_bytes(input);
  }
  setName(name: string): void {
    this._assertLive();
    this._inner.set_name(name);
  }
  /** Strong reference count (tests Self=ByArc on the Rust side). */
  strongCount(): bigint {
    this._assertLive();
    return this._inner.strong_count();
  }
  /** Take another Coveralls, creating a reference chain. */
  takeOther(other: Coveralls | null): void {
    this._assertLive();
    this._inner.take_other(other);
  }
  /** Releases the underlying WASM resource. Safe to call more than once. */
  free(): void {
    if (this._freed) return;
    this._freed = true;
    this._inner.free();
  }
  [Symbol.dispose](): void { this.free(); }
}
/** Object with fallible constructor only — no default constructor. */
export class FalliblePatch {
  private readonly _inner: __bg.FalliblePatch;
  private _freed = false;
  private _assertLive(): void {
    if (this._freed) throw new Error('FalliblePatch object has been freed');
  }
  private constructor(inner: __bg.FalliblePatch) {
    this._inner = inner;
  }
  /** @internal */
  static _fromInner(inner: __bg.FalliblePatch): FalliblePatch { return new FalliblePatch(inner); }
  static new(color: Color, shouldFail: boolean): FalliblePatch {
    try { return FalliblePatch._fromInner(new __bg.FalliblePatch(color, shouldFail)); } catch (e) { return _liftCoverallError(e); }
  }
  getColor(): Color {
    this._assertLive();
    return this._inner.get_color();
  }
  /** Releases the underlying WASM resource. Safe to call more than once. */
  free(): void {
    if (this._freed) return;
    this._freed = true;
    this._inner.free();
  }
  [Symbol.dispose](): void { this.free(); }
}
/** Forward-declaration test: NodeA references NodeB before it is declared. */
export class NodeA {
  private readonly _inner: __bg.NodeA;
  private _freed = false;
  private _assertLive(): void {
    if (this._freed) throw new Error('NodeA object has been freed');
  }
  private constructor(inner: __bg.NodeA) {
    this._inner = inner;
  }
  /** @internal */
  static _fromInner(inner: __bg.NodeA): NodeA { return new NodeA(inner); }
  getPartner(): NodeB | null {
    this._assertLive();
    return ((__v) => __v == null ? null : NodeB._fromInner(__v))(this._inner.get_partner());
  }
  /** Releases the underlying WASM resource. Safe to call more than once. */
  free(): void {
    if (this._freed) return;
    this._freed = true;
    this._inner.free();
  }
  [Symbol.dispose](): void { this.free(); }
}
/** Forward-declaration test: NodeB references NodeA (mutual reference). */
export class NodeB {
  private readonly _inner: __bg.NodeB;
  private _freed = false;
  private _assertLive(): void {
    if (this._freed) throw new Error('NodeB object has been freed');
  }
  private constructor(inner: __bg.NodeB) {
    this._inner = inner;
  }
  /** @internal */
  static _fromInner(inner: __bg.NodeB): NodeB { return new NodeB(inner); }
  getPartner(): NodeA | null {
    this._assertLive();
    return ((__v) => __v == null ? null : NodeA._fromInner(__v))(this._inner.get_partner());
  }
  /** Releases the underlying WASM resource. Safe to call more than once. */
  free(): void {
    if (this._freed) return;
    this._freed = true;
    this._inner.free();
  }
  [Symbol.dispose](): void { this.free(); }
}
/** A simple object that wraps a Color. */
export class Patch {
  private readonly _inner: __bg.Patch;
  private _freed = false;
  private _assertLive(): void {
    if (this._freed) throw new Error('Patch object has been freed');
  }
  private constructor(inner: __bg.Patch) {
    this._inner = inner;
  }
  /** @internal */
  static _fromInner(inner: __bg.Patch): Patch { return new Patch(inner); }
  static new(color: Color): Patch { return Patch._fromInner(new __bg.Patch(color)); }
  getColor(): Color {
    this._assertLive();
    return this._inner.get_color();
  }
  /** Releases the underlying WASM resource. Safe to call more than once. */
  free(): void {
    if (this._freed) return;
    this._freed = true;
    this._inner.free();
  }
  [Symbol.dispose](): void { this.free(); }
}
/** Thread-safe counter (tests atomic state and thread safety). */
export class ThreadsafeCounter {
  private readonly _inner: __bg.ThreadsafeCounter;
  private _freed = false;
  private _assertLive(): void {
    if (this._freed) throw new Error('ThreadsafeCounter object has been freed');
  }
  private constructor(inner: __bg.ThreadsafeCounter) {
    this._inner = inner;
  }
  /** @internal */
  static _fromInner(inner: __bg.ThreadsafeCounter): ThreadsafeCounter { return new ThreadsafeCounter(inner); }
  static new(): ThreadsafeCounter { return ThreadsafeCounter._fromInner(new __bg.ThreadsafeCounter()); }
  getCount(): bigint {
    this._assertLive();
    return this._inner.get_count();
  }
  increment(): void {
    this._assertLive();
    this._inner.increment();
  }
  /** Releases the underlying WASM resource. Safe to call more than once. */
  free(): void {
    if (this._freed) return;
    this._freed = true;
    this._inner.free();
  }
  [Symbol.dispose](): void { this.free(); }
}

function _liftComplexError(e: unknown): never {
  try {
    const raw = typeof e === 'string' ? JSON.parse(e) : (e instanceof Error ? JSON.parse(e.message) : e);
    const tag = raw?.tag as string | undefined;
    if (tag === 'OsError') throw ComplexError.OsError(raw.code, raw.extendedCode);
    if (tag === 'PermissionDenied') throw ComplexError.PermissionDenied(raw.reason);
    if (tag === 'UnknownError') throw ComplexError.UnknownError();
  } catch (inner) {
    if (inner instanceof ComplexError) throw inner;
  }
  throw e;
}
function _liftCoverallError(e: unknown): never {
  const tag = typeof e === 'string' ? e : (e instanceof Error ? e.message : null);
  if (tag === 'TooManyHoles') throw new CoverallError('TooManyHoles');
  throw e;
}

export namespace CoverallDemo {
  /** Walk up a NodeTrait tree, collecting ancestor names. */
  export function ancestorNames(node: NodeTrait): string[] { return __bg.ancestor_names(node); }
  /** Create a SimpleDict whose optional fields are all null. */
  export function createNoneDict(): SimpleDict { return __bg.create_none_dict(); }
  /** Create a Patch with a specific color. */
  export function createPatch(color: Color): Patch { return Patch._fromInner(__bg.create_patch(color)); }
  /** Create a SimpleDict with sample values filled in. */
  export function createSomeDict(): SimpleDict { return __bg.create_some_dict(); }
  /** Divide a float by a text-parsed divisor; exercises error paths. */
  export function divideByText(value: number, divisor: string): number {
    try { return __bg.divide_by_text(value, divisor); } catch (e) { return _liftComplexError(e); }
  }
  /** Round-trip a map with non-string keys (record<u32, u64>). */
  export function getIntMap(key: number, value: bigint): Map<number, bigint> { return __bg.get_int_map(key, value); }
  /** Return an enum variant based on a numeric selector. */
  export function getMaybeSimpleDict(index: number): MaybeSimpleDict { return __bg.get_maybe_simple_dict(index); }
  /**
   * Return the number of live Coveralls instances (tracking via constructor/destructor).
   */
  export function getNumAlive(): bigint { return __bg.get_num_alive(); }
  /** Create a Rust-implemented Getters for trait round-trip tests. */
  export function makeRustGetters(): Getters { return __bg.make_rust_getters(); }
  /** Round-trip a string; throws ComplexError on certain inputs. */
  export function println(value: string): string {
    try { return __bg.println(value); } catch (e) { return _liftComplexError(e); }
  }
  /** Reverse arbitrary bytes (binary data round-trip). */
  export function reverseBytes(input: Uint8Array): Uint8Array { return __bg.reverse_bytes(input); }
  /** Exercise a foreign-implemented Getters. */
  export function testGetters(getters: Getters): void {
    try { __bg.test_getters(getters); } catch (e) { _liftCoverallError(e); }
  }
}
