// Generated by uniffi-bindgen-js. DO NOT EDIT.
import __init, * as __bg from './coverall_demo_bg.js';

function _uniffiEnsureApiIntegrity(): void {
  const bindingsContractVersion = 30;
  const scaffoldingContractVersion: number = (__bg as any).ffi_crate_name_uniffi_contract_version();
  if (bindingsContractVersion !== scaffoldingContractVersion) {
    throw new Error(`UniFFI contract version mismatch: expected ${bindingsContractVersion}, got ${scaffoldingContractVersion}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_ancestor_names: number = (__bg as any).uniffi_crate_name_checksum_func_ancestor_names();
  if (_checksum_uniffi_crate_name_checksum_func_ancestor_names !== 32092) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_ancestor_names\`: expected 32092, got ${_checksum_uniffi_crate_name_checksum_func_ancestor_names}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_create_none_dict: number = (__bg as any).uniffi_crate_name_checksum_func_create_none_dict();
  if (_checksum_uniffi_crate_name_checksum_func_create_none_dict !== 59197) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_create_none_dict\`: expected 59197, got ${_checksum_uniffi_crate_name_checksum_func_create_none_dict}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_create_patch: number = (__bg as any).uniffi_crate_name_checksum_func_create_patch();
  if (_checksum_uniffi_crate_name_checksum_func_create_patch !== 45585) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_create_patch\`: expected 45585, got ${_checksum_uniffi_crate_name_checksum_func_create_patch}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_create_some_dict: number = (__bg as any).uniffi_crate_name_checksum_func_create_some_dict();
  if (_checksum_uniffi_crate_name_checksum_func_create_some_dict !== 59765) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_create_some_dict\`: expected 59765, got ${_checksum_uniffi_crate_name_checksum_func_create_some_dict}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_describe_maybe_color: number = (__bg as any).uniffi_crate_name_checksum_func_describe_maybe_color();
  if (_checksum_uniffi_crate_name_checksum_func_describe_maybe_color !== 34211) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_describe_maybe_color\`: expected 34211, got ${_checksum_uniffi_crate_name_checksum_func_describe_maybe_color}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_describe_maybe_dict: number = (__bg as any).uniffi_crate_name_checksum_func_describe_maybe_dict();
  if (_checksum_uniffi_crate_name_checksum_func_describe_maybe_dict !== 56361) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_describe_maybe_dict\`: expected 56361, got ${_checksum_uniffi_crate_name_checksum_func_describe_maybe_dict}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_divide_by_text: number = (__bg as any).uniffi_crate_name_checksum_func_divide_by_text();
  if (_checksum_uniffi_crate_name_checksum_func_divide_by_text !== 35670) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_divide_by_text\`: expected 35670, got ${_checksum_uniffi_crate_name_checksum_func_divide_by_text}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_get_int_map: number = (__bg as any).uniffi_crate_name_checksum_func_get_int_map();
  if (_checksum_uniffi_crate_name_checksum_func_get_int_map !== 13540) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_get_int_map\`: expected 13540, got ${_checksum_uniffi_crate_name_checksum_func_get_int_map}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_get_maybe_color: number = (__bg as any).uniffi_crate_name_checksum_func_get_maybe_color();
  if (_checksum_uniffi_crate_name_checksum_func_get_maybe_color !== 27958) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_get_maybe_color\`: expected 27958, got ${_checksum_uniffi_crate_name_checksum_func_get_maybe_color}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_get_maybe_count: number = (__bg as any).uniffi_crate_name_checksum_func_get_maybe_count();
  if (_checksum_uniffi_crate_name_checksum_func_get_maybe_count !== 58188) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_get_maybe_count\`: expected 58188, got ${_checksum_uniffi_crate_name_checksum_func_get_maybe_count}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_get_maybe_dict: number = (__bg as any).uniffi_crate_name_checksum_func_get_maybe_dict();
  if (_checksum_uniffi_crate_name_checksum_func_get_maybe_dict !== 50623) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_get_maybe_dict\`: expected 50623, got ${_checksum_uniffi_crate_name_checksum_func_get_maybe_dict}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_get_maybe_flag: number = (__bg as any).uniffi_crate_name_checksum_func_get_maybe_flag();
  if (_checksum_uniffi_crate_name_checksum_func_get_maybe_flag !== 59146) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_get_maybe_flag\`: expected 59146, got ${_checksum_uniffi_crate_name_checksum_func_get_maybe_flag}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_get_maybe_simple_dict: number = (__bg as any).uniffi_crate_name_checksum_func_get_maybe_simple_dict();
  if (_checksum_uniffi_crate_name_checksum_func_get_maybe_simple_dict !== 52642) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_get_maybe_simple_dict\`: expected 52642, got ${_checksum_uniffi_crate_name_checksum_func_get_maybe_simple_dict}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_get_num_alive: number = (__bg as any).uniffi_crate_name_checksum_func_get_num_alive();
  if (_checksum_uniffi_crate_name_checksum_func_get_num_alive !== 52390) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_get_num_alive\`: expected 52390, got ${_checksum_uniffi_crate_name_checksum_func_get_num_alive}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_make_rust_getters: number = (__bg as any).uniffi_crate_name_checksum_func_make_rust_getters();
  if (_checksum_uniffi_crate_name_checksum_func_make_rust_getters !== 31082) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_make_rust_getters\`: expected 31082, got ${_checksum_uniffi_crate_name_checksum_func_make_rust_getters}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_output_return_only_dict: number = (__bg as any).uniffi_crate_name_checksum_func_output_return_only_dict();
  if (_checksum_uniffi_crate_name_checksum_func_output_return_only_dict !== 25732) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_output_return_only_dict\`: expected 25732, got ${_checksum_uniffi_crate_name_checksum_func_output_return_only_dict}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_output_return_only_enum: number = (__bg as any).uniffi_crate_name_checksum_func_output_return_only_enum();
  if (_checksum_uniffi_crate_name_checksum_func_output_return_only_enum !== 17153) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_output_return_only_enum\`: expected 17153, got ${_checksum_uniffi_crate_name_checksum_func_output_return_only_enum}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_println: number = (__bg as any).uniffi_crate_name_checksum_func_println();
  if (_checksum_uniffi_crate_name_checksum_func_println !== 14318) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_println\`: expected 14318, got ${_checksum_uniffi_crate_name_checksum_func_println}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_reverse_bytes: number = (__bg as any).uniffi_crate_name_checksum_func_reverse_bytes();
  if (_checksum_uniffi_crate_name_checksum_func_reverse_bytes !== 20911) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_reverse_bytes\`: expected 20911, got ${_checksum_uniffi_crate_name_checksum_func_reverse_bytes}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_test_getters: number = (__bg as any).uniffi_crate_name_checksum_func_test_getters();
  if (_checksum_uniffi_crate_name_checksum_func_test_getters !== 40682) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_test_getters\`: expected 40682, got ${_checksum_uniffi_crate_name_checksum_func_test_getters}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_throw_flat_error: number = (__bg as any).uniffi_crate_name_checksum_func_throw_flat_error();
  if (_checksum_uniffi_crate_name_checksum_func_throw_flat_error !== 9433) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_throw_flat_error\`: expected 9433, got ${_checksum_uniffi_crate_name_checksum_func_throw_flat_error}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_validate_html: number = (__bg as any).uniffi_crate_name_checksum_func_validate_html();
  if (_checksum_uniffi_crate_name_checksum_func_validate_html !== 3368) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_validate_html\`: expected 3368, got ${_checksum_uniffi_crate_name_checksum_func_validate_html}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_coveralls_add_patch: number = (__bg as any).uniffi_crate_name_checksum_method_coveralls_add_patch();
  if (_checksum_uniffi_crate_name_checksum_method_coveralls_add_patch !== 39154) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_coveralls_add_patch\`: expected 39154, got ${_checksum_uniffi_crate_name_checksum_method_coveralls_add_patch}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_coveralls_add_repair: number = (__bg as any).uniffi_crate_name_checksum_method_coveralls_add_repair();
  if (_checksum_uniffi_crate_name_checksum_method_coveralls_add_repair !== 25033) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_coveralls_add_repair\`: expected 25033, got ${_checksum_uniffi_crate_name_checksum_method_coveralls_add_repair}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_coveralls_clone_me: number = (__bg as any).uniffi_crate_name_checksum_method_coveralls_clone_me();
  if (_checksum_uniffi_crate_name_checksum_method_coveralls_clone_me !== 58508) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_coveralls_clone_me\`: expected 58508, got ${_checksum_uniffi_crate_name_checksum_method_coveralls_clone_me}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_coveralls_get_dict2: number = (__bg as any).uniffi_crate_name_checksum_method_coveralls_get_dict2();
  if (_checksum_uniffi_crate_name_checksum_method_coveralls_get_dict2 !== 26919) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_coveralls_get_dict2\`: expected 26919, got ${_checksum_uniffi_crate_name_checksum_method_coveralls_get_dict2}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_coveralls_get_dict3: number = (__bg as any).uniffi_crate_name_checksum_method_coveralls_get_dict3();
  if (_checksum_uniffi_crate_name_checksum_method_coveralls_get_dict3 !== 4071) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_coveralls_get_dict3\`: expected 4071, got ${_checksum_uniffi_crate_name_checksum_method_coveralls_get_dict3}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_coveralls_get_metadata: number = (__bg as any).uniffi_crate_name_checksum_method_coveralls_get_metadata();
  if (_checksum_uniffi_crate_name_checksum_method_coveralls_get_metadata !== 31141) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_coveralls_get_metadata\`: expected 31141, got ${_checksum_uniffi_crate_name_checksum_method_coveralls_get_metadata}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_coveralls_get_name: number = (__bg as any).uniffi_crate_name_checksum_method_coveralls_get_name();
  if (_checksum_uniffi_crate_name_checksum_method_coveralls_get_name !== 25929) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_coveralls_get_name\`: expected 25929, got ${_checksum_uniffi_crate_name_checksum_method_coveralls_get_name}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_coveralls_get_other: number = (__bg as any).uniffi_crate_name_checksum_method_coveralls_get_other();
  if (_checksum_uniffi_crate_name_checksum_method_coveralls_get_other !== 22943) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_coveralls_get_other\`: expected 22943, got ${_checksum_uniffi_crate_name_checksum_method_coveralls_get_other}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_coveralls_get_repairs: number = (__bg as any).uniffi_crate_name_checksum_method_coveralls_get_repairs();
  if (_checksum_uniffi_crate_name_checksum_method_coveralls_get_repairs !== 40486) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_coveralls_get_repairs\`: expected 40486, got ${_checksum_uniffi_crate_name_checksum_method_coveralls_get_repairs}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_coveralls_get_status: number = (__bg as any).uniffi_crate_name_checksum_method_coveralls_get_status();
  if (_checksum_uniffi_crate_name_checksum_method_coveralls_get_status !== 19556) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_coveralls_get_status\`: expected 19556, got ${_checksum_uniffi_crate_name_checksum_method_coveralls_get_status}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_coveralls_get_tags: number = (__bg as any).uniffi_crate_name_checksum_method_coveralls_get_tags();
  if (_checksum_uniffi_crate_name_checksum_method_coveralls_get_tags !== 58217) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_coveralls_get_tags\`: expected 58217, got ${_checksum_uniffi_crate_name_checksum_method_coveralls_get_tags}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_coveralls_maybe_throw: number = (__bg as any).uniffi_crate_name_checksum_method_coveralls_maybe_throw();
  if (_checksum_uniffi_crate_name_checksum_method_coveralls_maybe_throw !== 33331) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_coveralls_maybe_throw\`: expected 33331, got ${_checksum_uniffi_crate_name_checksum_method_coveralls_maybe_throw}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_coveralls_maybe_throw_complex: number = (__bg as any).uniffi_crate_name_checksum_method_coveralls_maybe_throw_complex();
  if (_checksum_uniffi_crate_name_checksum_method_coveralls_maybe_throw_complex !== 24041) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_coveralls_maybe_throw_complex\`: expected 24041, got ${_checksum_uniffi_crate_name_checksum_method_coveralls_maybe_throw_complex}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_coveralls_maybe_throw_into: number = (__bg as any).uniffi_crate_name_checksum_method_coveralls_maybe_throw_into();
  if (_checksum_uniffi_crate_name_checksum_method_coveralls_maybe_throw_into !== 5009) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_coveralls_maybe_throw_into\`: expected 5009, got ${_checksum_uniffi_crate_name_checksum_method_coveralls_maybe_throw_into}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_coveralls_reverse_bytes: number = (__bg as any).uniffi_crate_name_checksum_method_coveralls_reverse_bytes();
  if (_checksum_uniffi_crate_name_checksum_method_coveralls_reverse_bytes !== 28911) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_coveralls_reverse_bytes\`: expected 28911, got ${_checksum_uniffi_crate_name_checksum_method_coveralls_reverse_bytes}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_coveralls_set_and_get_empty_struct: number = (__bg as any).uniffi_crate_name_checksum_method_coveralls_set_and_get_empty_struct();
  if (_checksum_uniffi_crate_name_checksum_method_coveralls_set_and_get_empty_struct !== 44611) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_coveralls_set_and_get_empty_struct\`: expected 44611, got ${_checksum_uniffi_crate_name_checksum_method_coveralls_set_and_get_empty_struct}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_coveralls_set_name: number = (__bg as any).uniffi_crate_name_checksum_method_coveralls_set_name();
  if (_checksum_uniffi_crate_name_checksum_method_coveralls_set_name !== 10857) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_coveralls_set_name\`: expected 10857, got ${_checksum_uniffi_crate_name_checksum_method_coveralls_set_name}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_coveralls_strong_count: number = (__bg as any).uniffi_crate_name_checksum_method_coveralls_strong_count();
  if (_checksum_uniffi_crate_name_checksum_method_coveralls_strong_count !== 23642) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_coveralls_strong_count\`: expected 23642, got ${_checksum_uniffi_crate_name_checksum_method_coveralls_strong_count}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_coveralls_take_other: number = (__bg as any).uniffi_crate_name_checksum_method_coveralls_take_other();
  if (_checksum_uniffi_crate_name_checksum_method_coveralls_take_other !== 64379) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_coveralls_take_other\`: expected 64379, got ${_checksum_uniffi_crate_name_checksum_method_coveralls_take_other}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_falliblepatch_get_color: number = (__bg as any).uniffi_crate_name_checksum_method_falliblepatch_get_color();
  if (_checksum_uniffi_crate_name_checksum_method_falliblepatch_get_color !== 47454) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_falliblepatch_get_color\`: expected 47454, got ${_checksum_uniffi_crate_name_checksum_method_falliblepatch_get_color}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_ifirst_compare: number = (__bg as any).uniffi_crate_name_checksum_method_ifirst_compare();
  if (_checksum_uniffi_crate_name_checksum_method_ifirst_compare !== 55948) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_ifirst_compare\`: expected 55948, got ${_checksum_uniffi_crate_name_checksum_method_ifirst_compare}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_isecond_compare: number = (__bg as any).uniffi_crate_name_checksum_method_isecond_compare();
  if (_checksum_uniffi_crate_name_checksum_method_isecond_compare !== 51747) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_isecond_compare\`: expected 51747, got ${_checksum_uniffi_crate_name_checksum_method_isecond_compare}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_nodea_get_partner: number = (__bg as any).uniffi_crate_name_checksum_method_nodea_get_partner();
  if (_checksum_uniffi_crate_name_checksum_method_nodea_get_partner !== 50601) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_nodea_get_partner\`: expected 50601, got ${_checksum_uniffi_crate_name_checksum_method_nodea_get_partner}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_nodeb_get_partner: number = (__bg as any).uniffi_crate_name_checksum_method_nodeb_get_partner();
  if (_checksum_uniffi_crate_name_checksum_method_nodeb_get_partner !== 49612) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_nodeb_get_partner\`: expected 49612, got ${_checksum_uniffi_crate_name_checksum_method_nodeb_get_partner}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_patch_get_color: number = (__bg as any).uniffi_crate_name_checksum_method_patch_get_color();
  if (_checksum_uniffi_crate_name_checksum_method_patch_get_color !== 7243) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_patch_get_color\`: expected 7243, got ${_checksum_uniffi_crate_name_checksum_method_patch_get_color}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_threadsafecounter_get_count: number = (__bg as any).uniffi_crate_name_checksum_method_threadsafecounter_get_count();
  if (_checksum_uniffi_crate_name_checksum_method_threadsafecounter_get_count !== 36276) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_threadsafecounter_get_count\`: expected 36276, got ${_checksum_uniffi_crate_name_checksum_method_threadsafecounter_get_count}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_threadsafecounter_increment: number = (__bg as any).uniffi_crate_name_checksum_method_threadsafecounter_increment();
  if (_checksum_uniffi_crate_name_checksum_method_threadsafecounter_increment !== 17778) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_threadsafecounter_increment\`: expected 17778, got ${_checksum_uniffi_crate_name_checksum_method_threadsafecounter_increment}`);
  }
  const _checksum_uniffi_crate_name_checksum_constructor_coveralls_fallible_new: number = (__bg as any).uniffi_crate_name_checksum_constructor_coveralls_fallible_new();
  if (_checksum_uniffi_crate_name_checksum_constructor_coveralls_fallible_new !== 6836) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_constructor_coveralls_fallible_new\`: expected 6836, got ${_checksum_uniffi_crate_name_checksum_constructor_coveralls_fallible_new}`);
  }
  const _checksum_uniffi_crate_name_checksum_constructor_coveralls_new: number = (__bg as any).uniffi_crate_name_checksum_constructor_coveralls_new();
  if (_checksum_uniffi_crate_name_checksum_constructor_coveralls_new !== 1263) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_constructor_coveralls_new\`: expected 1263, got ${_checksum_uniffi_crate_name_checksum_constructor_coveralls_new}`);
  }
  const _checksum_uniffi_crate_name_checksum_constructor_falliblepatch_new: number = (__bg as any).uniffi_crate_name_checksum_constructor_falliblepatch_new();
  if (_checksum_uniffi_crate_name_checksum_constructor_falliblepatch_new !== 12136) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_constructor_falliblepatch_new\`: expected 12136, got ${_checksum_uniffi_crate_name_checksum_constructor_falliblepatch_new}`);
  }
  const _checksum_uniffi_crate_name_checksum_constructor_falliblepatch_secondary: number = (__bg as any).uniffi_crate_name_checksum_constructor_falliblepatch_secondary();
  if (_checksum_uniffi_crate_name_checksum_constructor_falliblepatch_secondary !== 256) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_constructor_falliblepatch_secondary\`: expected 256, got ${_checksum_uniffi_crate_name_checksum_constructor_falliblepatch_secondary}`);
  }
  const _checksum_uniffi_crate_name_checksum_constructor_ifirst_new: number = (__bg as any).uniffi_crate_name_checksum_constructor_ifirst_new();
  if (_checksum_uniffi_crate_name_checksum_constructor_ifirst_new !== 41251) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_constructor_ifirst_new\`: expected 41251, got ${_checksum_uniffi_crate_name_checksum_constructor_ifirst_new}`);
  }
  const _checksum_uniffi_crate_name_checksum_constructor_isecond_new: number = (__bg as any).uniffi_crate_name_checksum_constructor_isecond_new();
  if (_checksum_uniffi_crate_name_checksum_constructor_isecond_new !== 16463) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_constructor_isecond_new\`: expected 16463, got ${_checksum_uniffi_crate_name_checksum_constructor_isecond_new}`);
  }
  const _checksum_uniffi_crate_name_checksum_constructor_patch_new: number = (__bg as any).uniffi_crate_name_checksum_constructor_patch_new();
  if (_checksum_uniffi_crate_name_checksum_constructor_patch_new !== 2665) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_constructor_patch_new\`: expected 2665, got ${_checksum_uniffi_crate_name_checksum_constructor_patch_new}`);
  }
  const _checksum_uniffi_crate_name_checksum_constructor_threadsafecounter_new: number = (__bg as any).uniffi_crate_name_checksum_constructor_threadsafecounter_new();
  if (_checksum_uniffi_crate_name_checksum_constructor_threadsafecounter_new !== 57006) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_constructor_threadsafecounter_new\`: expected 57006, got ${_checksum_uniffi_crate_name_checksum_constructor_threadsafecounter_new}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_getters_get_bool: number = (__bg as any).uniffi_crate_name_checksum_method_getters_get_bool();
  if (_checksum_uniffi_crate_name_checksum_method_getters_get_bool !== 55542) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_getters_get_bool\`: expected 55542, got ${_checksum_uniffi_crate_name_checksum_method_getters_get_bool}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_getters_get_string: number = (__bg as any).uniffi_crate_name_checksum_method_getters_get_string();
  if (_checksum_uniffi_crate_name_checksum_method_getters_get_string !== 61353) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_getters_get_string\`: expected 61353, got ${_checksum_uniffi_crate_name_checksum_method_getters_get_string}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_getters_get_option: number = (__bg as any).uniffi_crate_name_checksum_method_getters_get_option();
  if (_checksum_uniffi_crate_name_checksum_method_getters_get_option !== 62176) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_getters_get_option\`: expected 62176, got ${_checksum_uniffi_crate_name_checksum_method_getters_get_option}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_getters_get_list: number = (__bg as any).uniffi_crate_name_checksum_method_getters_get_list();
  if (_checksum_uniffi_crate_name_checksum_method_getters_get_list !== 61896) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_getters_get_list\`: expected 61896, got ${_checksum_uniffi_crate_name_checksum_method_getters_get_list}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_getters_get_nothing: number = (__bg as any).uniffi_crate_name_checksum_method_getters_get_nothing();
  if (_checksum_uniffi_crate_name_checksum_method_getters_get_nothing !== 22876) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_getters_get_nothing\`: expected 22876, got ${_checksum_uniffi_crate_name_checksum_method_getters_get_nothing}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_getters_round_trip_object: number = (__bg as any).uniffi_crate_name_checksum_method_getters_round_trip_object();
  if (_checksum_uniffi_crate_name_checksum_method_getters_round_trip_object !== 42475) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_getters_round_trip_object\`: expected 42475, got ${_checksum_uniffi_crate_name_checksum_method_getters_round_trip_object}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_nodetrait_name: number = (__bg as any).uniffi_crate_name_checksum_method_nodetrait_name();
  if (_checksum_uniffi_crate_name_checksum_method_nodetrait_name !== 46427) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_nodetrait_name\`: expected 46427, got ${_checksum_uniffi_crate_name_checksum_method_nodetrait_name}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_nodetrait_set_parent: number = (__bg as any).uniffi_crate_name_checksum_method_nodetrait_set_parent();
  if (_checksum_uniffi_crate_name_checksum_method_nodetrait_set_parent !== 14407) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_nodetrait_set_parent\`: expected 14407, got ${_checksum_uniffi_crate_name_checksum_method_nodetrait_set_parent}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_nodetrait_get_parent: number = (__bg as any).uniffi_crate_name_checksum_method_nodetrait_get_parent();
  if (_checksum_uniffi_crate_name_checksum_method_nodetrait_get_parent !== 18470) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_nodetrait_get_parent\`: expected 18470, got ${_checksum_uniffi_crate_name_checksum_method_nodetrait_get_parent}`);
  }
}
export async function init(...args: Parameters<typeof __init>): Promise<ReturnType<typeof __init>> {
  const result = await __init(...args);
  _uniffiEnsureApiIntegrity();
  return result;
}

export type ComplexErrorVariant =
  | { tag: 'OsError', code: number, extendedCode: number }
  | { tag: 'PermissionDenied', reason: string }
  | { tag: 'UnknownError' };

/** Rich error with structured variant data. */
export class ComplexError extends Error {
  override readonly name = 'ComplexError' as const;
  constructor(public readonly variant: ComplexErrorVariant) {
    super(variant.tag);
  }
  static OsError(code: number, extendedCode: number): ComplexError { return new ComplexError({ tag: 'OsError', code, extendedCode }); }
  static PermissionDenied(reason: string): ComplexError { return new ComplexError({ tag: 'PermissionDenied', reason }); }
  static UnknownError(): ComplexError { return new ComplexError({ tag: 'UnknownError' }); }
}

/** Simple flat error (single tag discriminator). */
export class CoverallError extends Error {
  override readonly name = 'CoverallError' as const;
  constructor(public readonly tag: 'TooManyHoles') {
    super(tag);
  }
  static TooManyHoles(): CoverallError { return new CoverallError('TooManyHoles'); }
}

/** Flat error with case-testing variant names. */
export class CoverallFlatError extends Error {
  override readonly name = 'CoverallFlatError' as const;
  constructor(public readonly tag: 'TooManyVariants') {
    super(tag);
  }
  static TooManyVariants(): CoverallFlatError { return new CoverallFlatError('TooManyVariants'); }
}

/** Flat error with non-standard casing. */
export class HTMLError extends Error {
  override readonly name = 'HTMLError' as const;
  constructor(public readonly tag: 'InvalidHTML') {
    super(tag);
  }
  static InvalidHTML(): HTMLError { return new HTMLError('InvalidHTML'); }
}

/** Record with default values — tests default field generation. */
export interface DictWithDefaults {
  name?: string;
  category?: string | null;
  integer?: bigint;
  itemList?: string[];
  itemMap?: Map<string, string>;
}

/** Empty record — tests zero-field record generation. */
export interface EmptyStruct {
}

/** Record with an object field — tests object-in-record via JSON codec. */
export interface Repair {
  when: Date;
  patch: Patch;
}

/** Return-only record type with an error enum as a field. */
export interface ReturnOnlyDict {
  e: CoverallFlatError;
}

/** Primary test record with a rich set of field types. */
export interface SimpleDict {
  text: string;
  maybeCount: bigint;
  flag: boolean;
  color: Color;
  tags: string[];
  counts: Map<string, bigint>;
  maybeText: string | null;
  maybePatch: Patch | null;
  maybeU8: number | null;
  maybeU16: number | null;
  maybeU64: bigint | null;
  maybeI8: number | null;
  maybeI64: bigint | null;
  maybeF32: number | null;
  maybeF64: number | null;
  maybeBool: boolean | null;
  maybeBytes: Uint8Array | null;
  someBytes: Uint8Array;
  coveralls: Coveralls | null;
}

/** Simple three-variant flat enum. */
export type Color = 'Red' | 'Blue' | 'Green';

/** Enum wrapping an object — tests object in data enum variant. */
export type MaybeObject =
  | { tag: 'Obj', p: Patch }
  | { tag: 'Nah' };

/** Enum wrapping a record — tests enum-with-associated-data. */
export type MaybeSimpleDict =
  | { tag: 'Yeah', value: SimpleDict }
  | { tag: 'Nah' };

/** Return-only enum with nested error and record types. */
export type ReturnOnlyEnum =
  | { tag: 'One', e: CoverallFlatError }
  | { tag: 'Two', d: ReturnOnlyDict }
  | { tag: 'Three', l: CoverallFlatError[] }
  | { tag: 'Four', m: Map<string, CoverallFlatError> };

/** Callback interface exercising multiple return types and error paths. */
export interface Getters {
  getBool(v: boolean, arg2: boolean): boolean;
  getString(v: string, arg2: boolean): string;
  getOption(v: string, arg2: boolean): string | null;
  getList(v: number[], arg2: boolean): number[];
  getNothing(v: string): void;
  roundTripObject(coveralls: Coveralls): Coveralls;
}

/** Callback interface for tree-like trait object graphs. */
export interface NodeTrait {
  name(): string;
  setParent(parent: NodeTrait | null): void;
  getParent(): NodeTrait | null;
}

/** Main object exercising self-references, state, errors, and Arc semantics. */
export class Coveralls {
  private readonly _inner: __bg.Coveralls;
  private _freed = false;
  private _assertLive(): void {
    if (this._freed) throw new Error('Coveralls object has been freed');
  }
  private constructor(inner: __bg.Coveralls) {
    this._inner = inner;
  }
  /** @internal */
  static _fromInner(inner: __bg.Coveralls): Coveralls { return new Coveralls(inner); }
  static new(name: string): Coveralls { return Coveralls._fromInner(new __bg.Coveralls(name)); }
  static fallibleNew(name: string, shouldFail: boolean): Coveralls {
    try { return Coveralls._fromInner(__bg.coveralls_fallible_new(name, shouldFail)); } catch (e) { return _liftCoverallError(e); }
  }
  /** Add a patch to this coveralls. */
  addPatch(patch: Patch): void {
    this._assertLive();
    this._inner.add_patch(patch);
  }
  /** Add a repair record. */
  addRepair(repair: Repair): void {
    this._assertLive();
    this._inner.add_repair(repair);
  }
  /** Clone into a new instance (tests object return from method). */
  cloneMe(): Coveralls {
    this._assertLive();
    return Coveralls._fromInner(this._inner.clone_me());
  }
  /** Return a string-keyed map. */
  getDict2(key: string, value: bigint): Map<string, bigint> {
    this._assertLive();
    return this._inner.get_dict2(key, value);
  }
  /** Return a non-string-keyed map. */
  getDict3(key: number, value: bigint): Map<number, bigint> {
    this._assertLive();
    return this._inner.get_dict3(key, value);
  }
  /** Return a map with string keys and optional string values. */
  getMetadata(): Map<string, string | null> {
    this._assertLive();
    return this._inner.get_metadata();
  }
  getName(): string {
    this._assertLive();
    return this._inner.get_name();
  }
  getOther(): Coveralls | null {
    this._assertLive();
    return ((__v) => __v == null ? null : Coveralls._fromInner(__v))(this._inner.get_other());
  }
  /** Return all stored repairs. */
  getRepairs(): Repair[] {
    this._assertLive();
    return this._inner.get_repairs();
  }
  /** Simple pass-through returning the status string. */
  getStatus(status: string): string {
    this._assertLive();
    return this._inner.get_status(status);
  }
  /** Return a sequence of optional strings. */
  getTags(): (string | null)[] {
    this._assertLive();
    return this._inner.get_tags();
  }
  /** Method that always throws a simple error. */
  maybeThrow(shouldThrow: boolean): boolean {
    this._assertLive();
    try { return this._inner.maybe_throw(shouldThrow); } catch (e) { return _liftCoverallError(e); }
  }
  /** Method that throws a complex (rich) error. */
  maybeThrowComplex(selector: number): boolean {
    this._assertLive();
    try { return this._inner.maybe_throw_complex(selector); } catch (e) { return _liftComplexError(e); }
  }
  /** Another throws variant — returns boolean. */
  maybeThrowInto(shouldThrow: boolean): boolean {
    this._assertLive();
    try { return this._inner.maybe_throw_into(shouldThrow); } catch (e) { return _liftCoverallError(e); }
  }
  /** Reverse some bytes via a method (tests binary on object). */
  reverseBytes(input: Uint8Array): Uint8Array {
    this._assertLive();
    return this._inner.reverse_bytes(input);
  }
  /** Empty record round-trip. */
  setAndGetEmptyStruct(emptyStruct: EmptyStruct): EmptyStruct {
    this._assertLive();
    return this._inner.set_and_get_empty_struct(emptyStruct);
  }
  setName(name: string): void {
    this._assertLive();
    this._inner.set_name(name);
  }
  /** Strong reference count (tests Self=ByArc on the Rust side). */
  strongCount(): bigint {
    this._assertLive();
    return this._inner.strong_count();
  }
  /** Take another Coveralls, creating a reference chain. */
  takeOther(other: Coveralls | null): void {
    this._assertLive();
    this._inner.take_other(other);
  }
  /** Releases the underlying WASM resource. Safe to call more than once. */
  free(): void {
    if (this._freed) return;
    this._freed = true;
    this._inner.free();
  }
  [Symbol.dispose](): void { this.free(); }
}
/** Object with fallible constructors — tests error on construction. */
export class FalliblePatch {
  private readonly _inner: __bg.FalliblePatch;
  private _freed = false;
  private _assertLive(): void {
    if (this._freed) throw new Error('FalliblePatch object has been freed');
  }
  private constructor(inner: __bg.FalliblePatch) {
    this._inner = inner;
  }
  /** @internal */
  static _fromInner(inner: __bg.FalliblePatch): FalliblePatch { return new FalliblePatch(inner); }
  static new(color: Color, shouldFail: boolean): FalliblePatch {
    try { return FalliblePatch._fromInner(new __bg.FalliblePatch(color, shouldFail)); } catch (e) { return _liftCoverallError(e); }
  }
  static secondary(color: Color, shouldFail: boolean): FalliblePatch {
    try { return FalliblePatch._fromInner(__bg.fallible_patch_secondary(color, shouldFail)); } catch (e) { return _liftCoverallError(e); }
  }
  getColor(): Color {
    this._assertLive();
    return this._inner.get_color();
  }
  /** Releases the underlying WASM resource. Safe to call more than once. */
  free(): void {
    if (this._freed) return;
    this._freed = true;
    this._inner.free();
  }
  [Symbol.dispose](): void { this.free(); }
}
/** Forward-reference test: IFirst refers to ISecond and vice versa. */
export class IFirst {
  private readonly _inner: __bg.IFirst;
  private _freed = false;
  private _assertLive(): void {
    if (this._freed) throw new Error('IFirst object has been freed');
  }
  private constructor(inner: __bg.IFirst) {
    this._inner = inner;
  }
  /** @internal */
  static _fromInner(inner: __bg.IFirst): IFirst { return new IFirst(inner); }
  static new(): IFirst { return IFirst._fromInner(new __bg.IFirst()); }
  compare(other: ISecond | null = null): boolean {
    this._assertLive();
    return this._inner.compare(other);
  }
  /** Releases the underlying WASM resource. Safe to call more than once. */
  free(): void {
    if (this._freed) return;
    this._freed = true;
    this._inner.free();
  }
  [Symbol.dispose](): void { this.free(); }
}
/** Counterpart to IFirst in the forward-reference pair. */
export class ISecond {
  private readonly _inner: __bg.ISecond;
  private _freed = false;
  private _assertLive(): void {
    if (this._freed) throw new Error('ISecond object has been freed');
  }
  private constructor(inner: __bg.ISecond) {
    this._inner = inner;
  }
  /** @internal */
  static _fromInner(inner: __bg.ISecond): ISecond { return new ISecond(inner); }
  static new(): ISecond { return ISecond._fromInner(new __bg.ISecond()); }
  compare(other: IFirst | null): boolean {
    this._assertLive();
    return this._inner.compare(other);
  }
  /** Releases the underlying WASM resource. Safe to call more than once. */
  free(): void {
    if (this._freed) return;
    this._freed = true;
    this._inner.free();
  }
  [Symbol.dispose](): void { this.free(); }
}
/** Forward-declaration test: NodeA references NodeB before it is declared. */
export class NodeA {
  private readonly _inner: __bg.NodeA;
  private _freed = false;
  private _assertLive(): void {
    if (this._freed) throw new Error('NodeA object has been freed');
  }
  private constructor(inner: __bg.NodeA) {
    this._inner = inner;
  }
  /** @internal */
  static _fromInner(inner: __bg.NodeA): NodeA { return new NodeA(inner); }
  getPartner(): NodeB | null {
    this._assertLive();
    return ((__v) => __v == null ? null : NodeB._fromInner(__v))(this._inner.get_partner());
  }
  /** Releases the underlying WASM resource. Safe to call more than once. */
  free(): void {
    if (this._freed) return;
    this._freed = true;
    this._inner.free();
  }
  [Symbol.dispose](): void { this.free(); }
}
/** Forward-declaration test: NodeB references NodeA (mutual reference). */
export class NodeB {
  private readonly _inner: __bg.NodeB;
  private _freed = false;
  private _assertLive(): void {
    if (this._freed) throw new Error('NodeB object has been freed');
  }
  private constructor(inner: __bg.NodeB) {
    this._inner = inner;
  }
  /** @internal */
  static _fromInner(inner: __bg.NodeB): NodeB { return new NodeB(inner); }
  getPartner(): NodeA | null {
    this._assertLive();
    return ((__v) => __v == null ? null : NodeA._fromInner(__v))(this._inner.get_partner());
  }
  /** Releases the underlying WASM resource. Safe to call more than once. */
  free(): void {
    if (this._freed) return;
    this._freed = true;
    this._inner.free();
  }
  [Symbol.dispose](): void { this.free(); }
}
/** A simple object that wraps a Color. */
export class Patch {
  private readonly _inner: __bg.Patch;
  private _freed = false;
  private _assertLive(): void {
    if (this._freed) throw new Error('Patch object has been freed');
  }
  private constructor(inner: __bg.Patch) {
    this._inner = inner;
  }
  /** @internal */
  static _fromInner(inner: __bg.Patch): Patch { return new Patch(inner); }
  static new(color: Color): Patch { return Patch._fromInner(new __bg.Patch(color)); }
  getColor(): Color {
    this._assertLive();
    return this._inner.get_color();
  }
  /** Releases the underlying WASM resource. Safe to call more than once. */
  free(): void {
    if (this._freed) return;
    this._freed = true;
    this._inner.free();
  }
  [Symbol.dispose](): void { this.free(); }
}
/** Thread-safe counter (tests atomic state and thread safety). */
export class ThreadsafeCounter {
  private readonly _inner: __bg.ThreadsafeCounter;
  private _freed = false;
  private _assertLive(): void {
    if (this._freed) throw new Error('ThreadsafeCounter object has been freed');
  }
  private constructor(inner: __bg.ThreadsafeCounter) {
    this._inner = inner;
  }
  /** @internal */
  static _fromInner(inner: __bg.ThreadsafeCounter): ThreadsafeCounter { return new ThreadsafeCounter(inner); }
  static new(): ThreadsafeCounter { return ThreadsafeCounter._fromInner(new __bg.ThreadsafeCounter()); }
  getCount(): bigint {
    this._assertLive();
    return this._inner.get_count();
  }
  increment(): void {
    this._assertLive();
    this._inner.increment();
  }
  /** Releases the underlying WASM resource. Safe to call more than once. */
  free(): void {
    if (this._freed) return;
    this._freed = true;
    this._inner.free();
  }
  [Symbol.dispose](): void { this.free(); }
}

function _liftComplexError(e: unknown): never {
  try {
    const raw = typeof e === 'string' ? JSON.parse(e) : (e instanceof Error ? JSON.parse(e.message) : e);
    const tag = raw?.tag as string | undefined;
    if (tag === 'OsError') throw ComplexError.OsError(raw.code, raw.extendedCode);
    if (tag === 'PermissionDenied') throw ComplexError.PermissionDenied(raw.reason);
    if (tag === 'UnknownError') throw ComplexError.UnknownError();
  } catch (inner) {
    if (inner instanceof ComplexError) throw inner;
  }
  throw e;
}
function _liftCoverallError(e: unknown): never {
  const tag = typeof e === 'string' ? e : (e instanceof Error ? e.message : null);
  if (tag === 'TooManyHoles') throw new CoverallError('TooManyHoles');
  throw e;
}
function _liftCoverallFlatError(e: unknown): never {
  const tag = typeof e === 'string' ? e : (e instanceof Error ? e.message : null);
  if (tag === 'TooManyVariants') throw new CoverallFlatError('TooManyVariants');
  throw e;
}
function _liftHTMLError(e: unknown): never {
  const tag = typeof e === 'string' ? e : (e instanceof Error ? e.message : null);
  if (tag === 'InvalidHTML') throw new HTMLError('InvalidHTML');
  throw e;
}

export namespace CoverallDemo {
  /** Walk up a NodeTrait tree, collecting ancestor names. */
  export function ancestorNames(node: NodeTrait): string[] { return __bg.ancestor_names(node); }
  /** Create a SimpleDict whose optional fields are all null. */
  export function createNoneDict(): SimpleDict { return __bg.create_none_dict(); }
  /** Create a Patch with a specific color. */
  export function createPatch(color: Color): Patch { return Patch._fromInner(__bg.create_patch(color)); }
  /** Create a SimpleDict with sample values filled in. */
  export function createSomeDict(): SimpleDict { return __bg.create_some_dict(); }
  /** Accept an optional Color enum parameter. */
  export function describeMaybeColor(input: Color | null): string { return __bg.describe_maybe_color(input); }
  /** Accept an optional SimpleDict parameter. */
  export function describeMaybeDict(input: SimpleDict | null): string { return __bg.describe_maybe_dict(input); }
  /** Divide a float by a text-parsed divisor; exercises error paths. */
  export function divideByText(value: number, divisor: string): number {
    try { return __bg.divide_by_text(value, divisor); } catch (e) { return _liftComplexError(e); }
  }
  /** Round-trip a map with non-string keys (record<u32, u64>). */
  export function getIntMap(key: number, value: bigint): Map<number, bigint> { return __bg.get_int_map(key, value); }
  /** Return an optional Color enum based on a flag. */
  export function getMaybeColor(returnValue: boolean): Color | null { return __bg.get_maybe_color(returnValue) ?? null; }
  /** Return an optional u32 based on a flag. */
  export function getMaybeCount(returnValue: boolean): number | null { return __bg.get_maybe_count(returnValue) ?? null; }
  /** Return an optional SimpleDict based on a flag. */
  export function getMaybeDict(returnValue: boolean): SimpleDict | null { return __bg.get_maybe_dict(returnValue) ?? null; }
  /** Return an optional boolean based on a flag. */
  export function getMaybeFlag(returnValue: boolean): boolean | null { return __bg.get_maybe_flag(returnValue) ?? null; }
  /** Return an enum variant based on a numeric selector. */
  export function getMaybeSimpleDict(index: number): MaybeSimpleDict { return __bg.get_maybe_simple_dict(index); }
  /**
   * Return the number of live Coveralls instances (tracking via constructor/destructor).
   */
  export function getNumAlive(): bigint { return __bg.get_num_alive(); }
  /** Create a Rust-implemented Getters for trait round-trip tests. */
  export function makeRustGetters(): Getters { return __bg.make_rust_getters(); }
  /** Return a ReturnOnlyDict (tests return-only record type). */
  export function outputReturnOnlyDict(): ReturnOnlyDict { return __bg.output_return_only_dict(); }
  /** Return a ReturnOnlyEnum (tests return-only enum type). */
  export function outputReturnOnlyEnum(): ReturnOnlyEnum { return __bg.output_return_only_enum(); }
  /** Round-trip a string; throws ComplexError on certain inputs. */
  export function println(value: string): string {
    try { return __bg.println(value); } catch (e) { return _liftComplexError(e); }
  }
  /** Reverse arbitrary bytes (binary data round-trip). */
  export function reverseBytes(input: Uint8Array): Uint8Array { return __bg.reverse_bytes(input); }
  /** Exercise a foreign-implemented Getters. */
  export function testGetters(getters: Getters): void {
    try { __bg.test_getters(getters); } catch (e) { _liftCoverallError(e); }
  }
  /** Throw a CoverallFlatError. */
  export function throwFlatError(): void {
    try { __bg.throw_flat_error(); } catch (e) { _liftCoverallFlatError(e); }
  }
  /** Validate HTML source; throws HTMLError on invalid input. */
  export function validateHtml(source: string): void {
    try { __bg.validate_html(source); } catch (e) { _liftHTMLError(e); }
  }
}
