// Generated by uniffi-bindgen-js. DO NOT EDIT.
import __init, * as __bg from './coverall_demo_bg.js';
export { __init as init };

export type ComplexErrorVariant =
  | { tag: 'OsError', code: number, extendedCode: number }
  | { tag: 'PermissionDenied', reason: string }
  | { tag: 'UnknownError' };

/** Rich error with structured variant data. */
export class ComplexError extends Error {
  override readonly name = 'ComplexError' as const;
  constructor(public readonly variant: ComplexErrorVariant) {
    super(variant.tag);
  }
  static OsError(code: number, extendedCode: number): ComplexError { return new ComplexError({ tag: 'OsError', code, extendedCode }); }
  static PermissionDenied(reason: string): ComplexError { return new ComplexError({ tag: 'PermissionDenied', reason }); }
  static UnknownError(): ComplexError { return new ComplexError({ tag: 'UnknownError' }); }
}

/** Simple flat error (single tag discriminator). */
export class CoverallError extends Error {
  override readonly name = 'CoverallError' as const;
  constructor(public readonly tag: 'TooManyHoles') {
    super(tag);
  }
  static TooManyHoles(): CoverallError { return new CoverallError('TooManyHoles'); }
}

/** Flat error with case-testing variant names. */
export class CoverallFlatError extends Error {
  override readonly name = 'CoverallFlatError' as const;
  constructor(public readonly tag: 'TooManyVariants') {
    super(tag);
  }
  static TooManyVariants(): CoverallFlatError { return new CoverallFlatError('TooManyVariants'); }
}

/** Flat error with non-standard casing. */
export class HTMLError extends Error {
  override readonly name = 'HTMLError' as const;
  constructor(public readonly tag: 'InvalidHTML') {
    super(tag);
  }
  static InvalidHTML(): HTMLError { return new HTMLError('InvalidHTML'); }
}

/** Record with default values — tests default field generation. */
export interface DictWithDefaults {
  name?: string;
  category?: string | null;
  integer?: bigint;
  itemList?: string[];
  itemMap?: Map<string, string>;
}

/** Empty record — tests zero-field record generation. */
export interface EmptyStruct {
}

/** Record with an object field — tests object-in-record via JSON codec. */
export interface Repair {
  when: Date;
  patch: Patch;
}

/** Return-only record type with an error enum as a field. */
export interface ReturnOnlyDict {
  e: CoverallFlatError;
}

/** Primary test record with a rich set of field types. */
export interface SimpleDict {
  text: string;
  maybeCount: bigint;
  flag: boolean;
  color: Color;
  tags: string[];
  counts: Map<string, bigint>;
  maybeText: string | null;
  maybePatch: Patch | null;
  maybeU8: number | null;
  maybeU16: number | null;
  maybeU64: bigint | null;
  maybeI8: number | null;
  maybeI64: bigint | null;
  maybeF32: number | null;
  maybeF64: number | null;
  maybeBool: boolean | null;
  maybeBytes: Uint8Array | null;
  someBytes: Uint8Array;
  coveralls: Coveralls | null;
}

/** Simple three-variant flat enum. */
export type Color = 'Red' | 'Blue' | 'Green';

/** Enum wrapping an object — tests object in data enum variant. */
export type MaybeObject =
  | { tag: 'Obj', p: Patch }
  | { tag: 'Nah' };

/** Enum wrapping a record — tests enum-with-associated-data. */
export type MaybeSimpleDict =
  | { tag: 'Yeah', value: SimpleDict }
  | { tag: 'Nah' };

/** Return-only enum with nested error and record types. */
export type ReturnOnlyEnum =
  | { tag: 'One', e: CoverallFlatError }
  | { tag: 'Two', d: ReturnOnlyDict }
  | { tag: 'Three', l: CoverallFlatError[] }
  | { tag: 'Four', m: Map<string, CoverallFlatError> };

/** Callback interface exercising multiple return types and error paths. */
export interface Getters {
  getBool(v: boolean, arg2: boolean): boolean;
  getString(v: string, arg2: boolean): string;
  getOption(v: string, arg2: boolean): string | null;
  getList(v: number[], arg2: boolean): number[];
  getNothing(v: string): void;
  roundTripObject(coveralls: Coveralls): Coveralls;
}

/** Callback interface for tree-like trait object graphs. */
export interface NodeTrait {
  name(): string;
  setParent(parent: NodeTrait | null): void;
  getParent(): NodeTrait | null;
}

/** Main object exercising self-references, state, errors, and Arc semantics. */
export class Coveralls {
  private readonly _inner: __bg.Coveralls;
  private _freed = false;
  private _assertLive(): void {
    if (this._freed) throw new Error('Coveralls object has been freed');
  }
  private constructor(inner: __bg.Coveralls) {
    this._inner = inner;
  }
  /** @internal */
  static _fromInner(inner: __bg.Coveralls): Coveralls { return new Coveralls(inner); }
  static create(name: string): Coveralls { return Coveralls._fromInner(new __bg.Coveralls(name)); }
  /** @throws {CoverallError} */
  static fallibleNew(name: string, shouldFail: boolean): Coveralls {
    try { return Coveralls._fromInner(__bg.coveralls_fallible_new(name, shouldFail)); } catch (e) { return _liftCoverallError(e); }
  }
  /** Add a patch to this coveralls. */
  addPatch(patch: Patch): void {
    this._assertLive();
    this._inner.add_patch(patch);
  }
  /** Add a repair record. */
  addRepair(repair: Repair): void {
    this._assertLive();
    this._inner.add_repair(repair);
  }
  /** Clone into a new instance (tests object return from method). */
  cloneMe(): Coveralls {
    this._assertLive();
    return Coveralls._fromInner(this._inner.clone_me());
  }
  /** Return a string-keyed map. */
  getDict2(key: string, value: bigint): Map<string, bigint> {
    this._assertLive();
    return this._inner.get_dict2(key, value);
  }
  /** Return a non-string-keyed map. */
  getDict3(key: number, value: bigint): Map<number, bigint> {
    this._assertLive();
    return this._inner.get_dict3(key, value);
  }
  /** Return a map with string keys and optional string values. */
  getMetadata(): Map<string, string | null> {
    this._assertLive();
    return this._inner.get_metadata();
  }
  getName(): string {
    this._assertLive();
    return this._inner.get_name();
  }
  getOther(): Coveralls | null {
    this._assertLive();
    const __v = this._inner.get_other();
    return __v == null ? null : Coveralls._fromInner(__v);
  }
  /** Return all stored repairs. */
  getRepairs(): Repair[] {
    this._assertLive();
    return this._inner.get_repairs();
  }
  /** Simple pass-through returning the status string. */
  getStatus(status: string): string {
    this._assertLive();
    return this._inner.get_status(status);
  }
  /** Return a sequence of optional strings. */
  getTags(): (string | null)[] {
    this._assertLive();
    return this._inner.get_tags();
  }
  /**
   * Method that always throws a simple error.
   * @throws {CoverallError}
   */
  maybeThrow(shouldThrow: boolean): boolean {
    this._assertLive();
    try { return this._inner.maybe_throw(shouldThrow); } catch (e) { return _liftCoverallError(e); }
  }
  /**
   * Method that throws a complex (rich) error.
   * @throws {ComplexError}
   */
  maybeThrowComplex(selector: number): boolean {
    this._assertLive();
    try { return this._inner.maybe_throw_complex(selector); } catch (e) { return _liftComplexError(e); }
  }
  /**
   * Another throws variant — returns boolean.
   * @throws {CoverallError}
   */
  maybeThrowInto(shouldThrow: boolean): boolean {
    this._assertLive();
    try { return this._inner.maybe_throw_into(shouldThrow); } catch (e) { return _liftCoverallError(e); }
  }
  /** Reverse some bytes via a method (tests binary on object). */
  reverseBytes(input: Uint8Array): Uint8Array {
    this._assertLive();
    return this._inner.reverse_bytes(input);
  }
  /** Empty record round-trip. */
  setAndGetEmptyStruct(emptyStruct: EmptyStruct): EmptyStruct {
    this._assertLive();
    return this._inner.set_and_get_empty_struct(emptyStruct);
  }
  setName(name: string): void {
    this._assertLive();
    this._inner.set_name(name);
  }
  /** Strong reference count (tests Self=ByArc on the Rust side). */
  strongCount(): bigint {
    this._assertLive();
    return this._inner.strong_count();
  }
  /** Take another Coveralls, creating a reference chain. */
  takeOther(other: Coveralls | null): void {
    this._assertLive();
    this._inner.take_other(other);
  }
  /** Releases the underlying WASM resource. Safe to call more than once. */
  free(): void {
    if (this._freed) return;
    this._freed = true;
    this._inner.free();
  }
  [Symbol.dispose](): void { this.free(); }
}

/** Object with fallible constructors — tests error on construction. */
export class FalliblePatch {
  private readonly _inner: __bg.FalliblePatch;
  private _freed = false;
  private _assertLive(): void {
    if (this._freed) throw new Error('FalliblePatch object has been freed');
  }
  private constructor(inner: __bg.FalliblePatch) {
    this._inner = inner;
  }
  /** @internal */
  static _fromInner(inner: __bg.FalliblePatch): FalliblePatch { return new FalliblePatch(inner); }
  /** @throws {CoverallError} */
  static create(color: Color, shouldFail: boolean): FalliblePatch {
    try { return FalliblePatch._fromInner(new __bg.FalliblePatch(color, shouldFail)); } catch (e) { return _liftCoverallError(e); }
  }
  /** @throws {CoverallError} */
  static secondary(color: Color, shouldFail: boolean): FalliblePatch {
    try { return FalliblePatch._fromInner(__bg.fallible_patch_secondary(color, shouldFail)); } catch (e) { return _liftCoverallError(e); }
  }
  getColor(): Color {
    this._assertLive();
    return this._inner.get_color();
  }
  /** Releases the underlying WASM resource. Safe to call more than once. */
  free(): void {
    if (this._freed) return;
    this._freed = true;
    this._inner.free();
  }
  [Symbol.dispose](): void { this.free(); }
}

/** Forward-reference test: IFirst refers to ISecond and vice versa. */
export class IFirst {
  private readonly _inner: __bg.IFirst;
  private _freed = false;
  private _assertLive(): void {
    if (this._freed) throw new Error('IFirst object has been freed');
  }
  private constructor(inner: __bg.IFirst) {
    this._inner = inner;
  }
  /** @internal */
  static _fromInner(inner: __bg.IFirst): IFirst { return new IFirst(inner); }
  static create(): IFirst { return IFirst._fromInner(new __bg.IFirst()); }
  compare(other: ISecond | null = null): boolean {
    this._assertLive();
    return this._inner.compare(other);
  }
  /** Releases the underlying WASM resource. Safe to call more than once. */
  free(): void {
    if (this._freed) return;
    this._freed = true;
    this._inner.free();
  }
  [Symbol.dispose](): void { this.free(); }
}

/** Counterpart to IFirst in the forward-reference pair. */
export class ISecond {
  private readonly _inner: __bg.ISecond;
  private _freed = false;
  private _assertLive(): void {
    if (this._freed) throw new Error('ISecond object has been freed');
  }
  private constructor(inner: __bg.ISecond) {
    this._inner = inner;
  }
  /** @internal */
  static _fromInner(inner: __bg.ISecond): ISecond { return new ISecond(inner); }
  static create(): ISecond { return ISecond._fromInner(new __bg.ISecond()); }
  compare(other: IFirst | null): boolean {
    this._assertLive();
    return this._inner.compare(other);
  }
  /** Releases the underlying WASM resource. Safe to call more than once. */
  free(): void {
    if (this._freed) return;
    this._freed = true;
    this._inner.free();
  }
  [Symbol.dispose](): void { this.free(); }
}

/** Forward-declaration test: NodeA references NodeB before it is declared. */
export class NodeA {
  private readonly _inner: __bg.NodeA;
  private _freed = false;
  private _assertLive(): void {
    if (this._freed) throw new Error('NodeA object has been freed');
  }
  private constructor(inner: __bg.NodeA) {
    this._inner = inner;
  }
  /** @internal */
  static _fromInner(inner: __bg.NodeA): NodeA { return new NodeA(inner); }
  getPartner(): NodeB | null {
    this._assertLive();
    const __v = this._inner.get_partner();
    return __v == null ? null : NodeB._fromInner(__v);
  }
  /** Releases the underlying WASM resource. Safe to call more than once. */
  free(): void {
    if (this._freed) return;
    this._freed = true;
    this._inner.free();
  }
  [Symbol.dispose](): void { this.free(); }
}

/** Forward-declaration test: NodeB references NodeA (mutual reference). */
export class NodeB {
  private readonly _inner: __bg.NodeB;
  private _freed = false;
  private _assertLive(): void {
    if (this._freed) throw new Error('NodeB object has been freed');
  }
  private constructor(inner: __bg.NodeB) {
    this._inner = inner;
  }
  /** @internal */
  static _fromInner(inner: __bg.NodeB): NodeB { return new NodeB(inner); }
  getPartner(): NodeA | null {
    this._assertLive();
    const __v = this._inner.get_partner();
    return __v == null ? null : NodeA._fromInner(__v);
  }
  /** Releases the underlying WASM resource. Safe to call more than once. */
  free(): void {
    if (this._freed) return;
    this._freed = true;
    this._inner.free();
  }
  [Symbol.dispose](): void { this.free(); }
}

/** A simple object that wraps a Color. */
export class Patch {
  private readonly _inner: __bg.Patch;
  private _freed = false;
  private _assertLive(): void {
    if (this._freed) throw new Error('Patch object has been freed');
  }
  private constructor(inner: __bg.Patch) {
    this._inner = inner;
  }
  /** @internal */
  static _fromInner(inner: __bg.Patch): Patch { return new Patch(inner); }
  static create(color: Color): Patch { return Patch._fromInner(new __bg.Patch(color)); }
  getColor(): Color {
    this._assertLive();
    return this._inner.get_color();
  }
  /** Releases the underlying WASM resource. Safe to call more than once. */
  free(): void {
    if (this._freed) return;
    this._freed = true;
    this._inner.free();
  }
  [Symbol.dispose](): void { this.free(); }
}

/** Thread-safe counter (tests atomic state and thread safety). */
export class ThreadsafeCounter {
  private readonly _inner: __bg.ThreadsafeCounter;
  private _freed = false;
  private _assertLive(): void {
    if (this._freed) throw new Error('ThreadsafeCounter object has been freed');
  }
  private constructor(inner: __bg.ThreadsafeCounter) {
    this._inner = inner;
  }
  /** @internal */
  static _fromInner(inner: __bg.ThreadsafeCounter): ThreadsafeCounter { return new ThreadsafeCounter(inner); }
  static create(): ThreadsafeCounter { return ThreadsafeCounter._fromInner(new __bg.ThreadsafeCounter()); }
  getCount(): bigint {
    this._assertLive();
    return this._inner.get_count();
  }
  increment(): void {
    this._assertLive();
    this._inner.increment();
  }
  /** Releases the underlying WASM resource. Safe to call more than once. */
  free(): void {
    if (this._freed) return;
    this._freed = true;
    this._inner.free();
  }
  [Symbol.dispose](): void { this.free(); }
}

function _liftComplexError(e: unknown): never {
  try {
    const raw = typeof e === 'string' ? JSON.parse(e) : (e instanceof Error ? JSON.parse(e.message) : e);
    const tag = raw?.tag as string | undefined;
    if (tag === 'OsError') throw ComplexError.OsError(raw.code, raw.extendedCode);
    if (tag === 'PermissionDenied') throw ComplexError.PermissionDenied(raw.reason);
    if (tag === 'UnknownError') throw ComplexError.UnknownError();
  } catch (inner) {
    if (inner instanceof ComplexError) throw inner;
  }
  throw e;
}

function _liftCoverallError(e: unknown): never {
  const tag = typeof e === 'string' ? e : (e instanceof Error ? e.message : null);
  if (tag === 'TooManyHoles') throw new CoverallError('TooManyHoles');
  throw e;
}

function _liftCoverallFlatError(e: unknown): never {
  const tag = typeof e === 'string' ? e : (e instanceof Error ? e.message : null);
  if (tag === 'TooManyVariants') throw new CoverallFlatError('TooManyVariants');
  throw e;
}

function _liftHTMLError(e: unknown): never {
  const tag = typeof e === 'string' ? e : (e instanceof Error ? e.message : null);
  if (tag === 'InvalidHTML') throw new HTMLError('InvalidHTML');
  throw e;
}

export namespace CoverallDemo {
  /** Walk up a NodeTrait tree, collecting ancestor names. */
  export function ancestorNames(node: NodeTrait): string[] { return __bg.ancestor_names(node); }
  /** Create a SimpleDict whose optional fields are all null. */
  export function createNoneDict(): SimpleDict { return __bg.create_none_dict(); }
  /** Create a Patch with a specific color. */
  export function createPatch(color: Color): Patch { return Patch._fromInner(__bg.create_patch(color)); }
  /** Create a SimpleDict with sample values filled in. */
  export function createSomeDict(): SimpleDict { return __bg.create_some_dict(); }
  /** Accept an optional Color enum parameter. */
  export function describeMaybeColor(input: Color | null): string { return __bg.describe_maybe_color(input); }
  /** Accept an optional SimpleDict parameter. */
  export function describeMaybeDict(input: SimpleDict | null): string { return __bg.describe_maybe_dict(input); }
  /**
   * Divide a float by a text-parsed divisor; exercises error paths.
   * @throws {ComplexError}
   */
  export function divideByText(value: number, divisor: string): number {
    try { return __bg.divide_by_text(value, divisor); } catch (e) { return _liftComplexError(e); }
  }
  /** Round-trip a map with non-string keys (record<u32, u64>). */
  export function getIntMap(key: number, value: bigint): Map<number, bigint> { return __bg.get_int_map(key, value); }
  /** Return an optional Color enum based on a flag. */
  export function getMaybeColor(returnValue: boolean): Color | null { return __bg.get_maybe_color(returnValue) ?? null; }
  /** Return an optional u32 based on a flag. */
  export function getMaybeCount(returnValue: boolean): number | null { return __bg.get_maybe_count(returnValue) ?? null; }
  /** Return an optional SimpleDict based on a flag. */
  export function getMaybeDict(returnValue: boolean): SimpleDict | null { return __bg.get_maybe_dict(returnValue) ?? null; }
  /** Return an optional boolean based on a flag. */
  export function getMaybeFlag(returnValue: boolean): boolean | null { return __bg.get_maybe_flag(returnValue) ?? null; }
  /** Return an enum variant based on a numeric selector. */
  export function getMaybeSimpleDict(index: number): MaybeSimpleDict { return __bg.get_maybe_simple_dict(index); }
  /**
   * Return the number of live Coveralls instances (tracking via constructor/destructor).
   */
  export function getNumAlive(): bigint { return __bg.get_num_alive(); }
  /** Create a Rust-implemented Getters for trait round-trip tests. */
  export function makeRustGetters(): Getters { return __bg.make_rust_getters(); }
  /** Return a ReturnOnlyDict (tests return-only record type). */
  export function outputReturnOnlyDict(): ReturnOnlyDict { return __bg.output_return_only_dict(); }
  /** Return a ReturnOnlyEnum (tests return-only enum type). */
  export function outputReturnOnlyEnum(): ReturnOnlyEnum { return __bg.output_return_only_enum(); }
  /**
   * Round-trip a string; throws ComplexError on certain inputs.
   * @throws {ComplexError}
   */
  export function println(value: string): string {
    try { return __bg.println(value); } catch (e) { return _liftComplexError(e); }
  }
  /** Reverse arbitrary bytes (binary data round-trip). */
  export function reverseBytes(input: Uint8Array): Uint8Array { return __bg.reverse_bytes(input); }
  /**
   * Exercise a foreign-implemented Getters.
   * @throws {CoverallError}
   */
  export function testGetters(getters: Getters): void {
    try { __bg.test_getters(getters); } catch (e) { _liftCoverallError(e); }
  }
  /**
   * Throw a CoverallFlatError.
   * @throws {CoverallFlatError}
   */
  export function throwFlatError(): void {
    try { __bg.throw_flat_error(); } catch (e) { _liftCoverallFlatError(e); }
  }
  /**
   * Validate HTML source; throws HTMLError on invalid input.
   * @throws {HTMLError}
   */
  export function validateHtml(source: string): void {
    try { __bg.validate_html(source); } catch (e) { _liftHTMLError(e); }
  }
}
