// Generated by uniffi-bindgen-js. DO NOT EDIT.

import koffi from 'koffi';

const _RustBuffer = koffi.struct('_RustBuffer', {
  capacity: 'uint64',
  len: 'uint64',
  data: koffi.pointer('uint8'),
});

const _RustCallStatus = koffi.struct('_RustCallStatus', {
  code: 'int8',
  error_buf: '_RustBuffer',
});

function _liftString(buf: { len: bigint; data: unknown }): string {
  if (buf.len === 0n) return '';
  const bytes = koffi.decode(buf.data, 'uint8', Number(buf.len));
  return Buffer.from(bytes as Uint8Array).toString('utf8');
}

function _lowerString(s: string): { capacity: bigint; len: bigint; data: Buffer } {
  const bytes = Buffer.from(s, 'utf8');
  return { capacity: BigInt(bytes.length), len: BigInt(bytes.length), data: bytes };
}

const _lib = (() => {
  const ext = process.platform === 'darwin' ? 'dylib' : 'so';
  return koffi.load(`libuniffi_simple.${ext}`);
})();

const _fn_ping = _lib.func('uniffi_simple_fn_func_ping', '_RustBuffer', [
  '_RustBuffer',
  koffi.out(koffi.pointer('_RustCallStatus')),
]);

export namespace Simple {
  export function ping(input: string): string {
    const _cs = { code: 0, error_buf: { capacity: 0n, len: 0n, data: null } };
    const _result = _fn_ping(_lowerString(input), _cs);
    if (_cs.code !== 0) {
      throw new Error(`uniffi: ping failed (status ${_cs.code})`);
    }
    return _liftString(_result as { len: bigint; data: unknown });
  }
}
