// Generated by uniffi-bindgen-js. DO NOT EDIT.
import __init, * as __bg from './simple_bg.js';

function _uniffiEnsureApiIntegrity(): void {
  const bindingsContractVersion = 30;
  const scaffoldingContractVersion: number = (__bg as any).ffi_crate_name_uniffi_contract_version();
  if (bindingsContractVersion !== scaffoldingContractVersion) {
    throw new Error(`UniFFI contract version mismatch: expected ${bindingsContractVersion}, got ${scaffoldingContractVersion}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_ping: number = (__bg as any).uniffi_crate_name_checksum_func_ping();
  if (_checksum_uniffi_crate_name_checksum_func_ping !== 32653) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_ping\`: expected 32653, got ${_checksum_uniffi_crate_name_checksum_func_ping}`);
  }
}
export async function init(...args: Parameters<typeof __init>): Promise<ReturnType<typeof __init>> {
  const result = await __init(...args);
  _uniffiEnsureApiIntegrity();
  return result;
}

export namespace Simple {
  export function ping(input: string): string { return __bg.ping(input); }
}
