// Generated by uniffi-bindgen-js. DO NOT EDIT.
import { UniffiRuntime, UniFFIWriter, UniFFIReader } from './uniffi_runtime.js';

const _rt = await UniffiRuntime.load(new URL('./ffi_traits.wasm', import.meta.url), 'ffi_traits');

export class Circle {
  /** @internal */
  readonly _handle: bigint;
  private _freed = false;
  private _assertLive(): void {
    if (this._freed) throw new Error('Circle object has been freed');
  }
  private constructor(handle: bigint) {
    this._handle = handle;
    _rt.registerPointer(this, 'uniffi_ffi_traits_fn_free_circle', handle);
  }
  /** @internal */
  static _fromHandle(handle: bigint): Circle { return new Circle(handle); }
  static create(radius: number): Circle {
    const _argPtr = _rt.scratchAlloc(1 * 8);
    _rt.writeF64Element(_argPtr, radius);
    const _retPtr = _rt.scratchAlloc(5 * 8);
    try {
      _rt.call('uniffi_ffibuffer_ffi_traits_fn_constructor_circle_new', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 8);
      const _result = _rt.readHandleElement(_retPtr);
      return new Circle(_result);
    } finally {
      _rt.scratchReset();
    }
  }
  radius(): number {
    this._assertLive();
    const _clonedHandle = _rt.cloneObjectHandle('uniffi_ffi_traits_fn_clone_circle', this._handle);
    const _argPtr = _rt.scratchAlloc(1 * 8);
    _rt.writeHandleElement(_argPtr, _clonedHandle);
    const _retPtr = _rt.scratchAlloc(5 * 8);
    try {
      _rt.call('uniffi_ffibuffer_ffi_traits_fn_method_circle_radius', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 8);
      const _result = _rt.readF64Element(_retPtr);
      return _result;
    } finally {
      _rt.scratchReset();
    }
  }
  /** Releases the underlying WASM resource. Safe to call more than once. */
  free(): void {
    if (this._freed) return;
    this._freed = true;
    _rt.unregisterPointer(this);
    _rt.callFree('uniffi_ffi_traits_fn_free_circle', this._handle);
  }
}
if (Symbol.dispose) (Circle as any).prototype[Symbol.dispose] = Circle.prototype.free;

export class Drawable {
  /** @internal */
  readonly _handle: bigint;
  private _freed = false;
  private _assertLive(): void {
    if (this._freed) throw new Error('Drawable object has been freed');
  }
  private constructor(handle: bigint) {
    this._handle = handle;
    _rt.registerPointer(this, 'uniffi_ffi_traits_fn_free_drawable', handle);
  }
  /** @internal */
  static _fromHandle(handle: bigint): Drawable { return new Drawable(handle); }
  area(): number {
    this._assertLive();
    const _clonedHandle = _rt.cloneObjectHandle('uniffi_ffi_traits_fn_clone_drawable', this._handle);
    const _argPtr = _rt.scratchAlloc(1 * 8);
    _rt.writeHandleElement(_argPtr, _clonedHandle);
    const _retPtr = _rt.scratchAlloc(5 * 8);
    try {
      _rt.call('uniffi_ffibuffer_ffi_traits_fn_method_drawable_area', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 8);
      const _result = _rt.readF64Element(_retPtr);
      return _result;
    } finally {
      _rt.scratchReset();
    }
  }
  describe(): string {
    this._assertLive();
    const _clonedHandle = _rt.cloneObjectHandle('uniffi_ffi_traits_fn_clone_drawable', this._handle);
    const _argPtr = _rt.scratchAlloc(1 * 8);
    _rt.writeHandleElement(_argPtr, _clonedHandle);
    const _retPtr = _rt.scratchAlloc(7 * 8);
    try {
      _rt.call('uniffi_ffibuffer_ffi_traits_fn_method_drawable_describe', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 24);
      const _result = _rt.liftString(_rt.readRustBufferElements(_retPtr));
      return _result;
    } finally {
      _rt.scratchReset();
    }
  }
  /** Releases the underlying WASM resource. Safe to call more than once. */
  free(): void {
    if (this._freed) return;
    this._freed = true;
    _rt.unregisterPointer(this);
    _rt.callFree('uniffi_ffi_traits_fn_free_drawable', this._handle);
  }
}
if (Symbol.dispose) (Drawable as any).prototype[Symbol.dispose] = Drawable.prototype.free;

export class Rect {
  /** @internal */
  readonly _handle: bigint;
  private _freed = false;
  private _assertLive(): void {
    if (this._freed) throw new Error('Rect object has been freed');
  }
  private constructor(handle: bigint) {
    this._handle = handle;
    _rt.registerPointer(this, 'uniffi_ffi_traits_fn_free_rect', handle);
  }
  /** @internal */
  static _fromHandle(handle: bigint): Rect { return new Rect(handle); }
  static create(width: number, height: number): Rect {
    const _argPtr = _rt.scratchAlloc(2 * 8);
    _rt.writeF64Element(_argPtr, width);
    _rt.writeF64Element(_argPtr + 8, height);
    const _retPtr = _rt.scratchAlloc(5 * 8);
    try {
      _rt.call('uniffi_ffibuffer_ffi_traits_fn_constructor_rect_new', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 8);
      const _result = _rt.readHandleElement(_retPtr);
      return new Rect(_result);
    } finally {
      _rt.scratchReset();
    }
  }
  height(): number {
    this._assertLive();
    const _clonedHandle = _rt.cloneObjectHandle('uniffi_ffi_traits_fn_clone_rect', this._handle);
    const _argPtr = _rt.scratchAlloc(1 * 8);
    _rt.writeHandleElement(_argPtr, _clonedHandle);
    const _retPtr = _rt.scratchAlloc(5 * 8);
    try {
      _rt.call('uniffi_ffibuffer_ffi_traits_fn_method_rect_height', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 8);
      const _result = _rt.readF64Element(_retPtr);
      return _result;
    } finally {
      _rt.scratchReset();
    }
  }
  width(): number {
    this._assertLive();
    const _clonedHandle = _rt.cloneObjectHandle('uniffi_ffi_traits_fn_clone_rect', this._handle);
    const _argPtr = _rt.scratchAlloc(1 * 8);
    _rt.writeHandleElement(_argPtr, _clonedHandle);
    const _retPtr = _rt.scratchAlloc(5 * 8);
    try {
      _rt.call('uniffi_ffibuffer_ffi_traits_fn_method_rect_width', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 8);
      const _result = _rt.readF64Element(_retPtr);
      return _result;
    } finally {
      _rt.scratchReset();
    }
  }
  /** Releases the underlying WASM resource. Safe to call more than once. */
  free(): void {
    if (this._freed) return;
    this._freed = true;
    _rt.unregisterPointer(this);
    _rt.callFree('uniffi_ffi_traits_fn_free_rect', this._handle);
  }
}
if (Symbol.dispose) (Rect as any).prototype[Symbol.dispose] = Rect.prototype.free;

// --- Serialization helpers ---

export namespace FfiTraits {
  export function describeAll(shapes: Drawable[]): string {
    const _rb_shapes = _rt.lowerIntoBuffer((w) => { w.writeSequence(shapes, (_w, _v) => { _w.writeU64(_rt.cloneObjectHandle('uniffi_ffi_traits_fn_clone_drawable', _v._handle)); }); });
    const _argPtr = _rt.scratchAlloc(3 * 8);
    _rt.writeRustBufferElements(_argPtr, _rb_shapes);
    const _retPtr = _rt.scratchAlloc(7 * 8);
    try {
      _rt.call('uniffi_ffibuffer_ffi_traits_fn_func_describe_all', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 24);
      const _result = _rt.liftString(_rt.readRustBufferElements(_retPtr));
      return _result;
    } finally {
      _rt.scratchReset();
    }
  }
  export function makeShapes(): Drawable[] {
    const _argPtr = 0;
    const _retPtr = _rt.scratchAlloc(7 * 8);
    try {
      _rt.call('uniffi_ffibuffer_ffi_traits_fn_func_make_shapes', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 24);
      const _result = _rt.liftFromBuffer(_rt.readRustBufferElements(_retPtr), (r) => { return r.readSequence((_r) => Drawable._fromHandle(_r.readU64())); });
      return _result;
    } finally {
      _rt.scratchReset();
    }
  }
  export function totalArea(shapes: Drawable[]): number {
    const _rb_shapes = _rt.lowerIntoBuffer((w) => { w.writeSequence(shapes, (_w, _v) => { _w.writeU64(_rt.cloneObjectHandle('uniffi_ffi_traits_fn_clone_drawable', _v._handle)); }); });
    const _argPtr = _rt.scratchAlloc(3 * 8);
    _rt.writeRustBufferElements(_argPtr, _rb_shapes);
    const _retPtr = _rt.scratchAlloc(5 * 8);
    try {
      _rt.call('uniffi_ffibuffer_ffi_traits_fn_func_total_area', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 8);
      const _result = _rt.readF64Element(_retPtr);
      return _result;
    } finally {
      _rt.scratchReset();
    }
  }
}
