// Generated by uniffi-bindgen-js. DO NOT EDIT.
import { UniffiRuntime, UniFFIWriter, UniFFIReader } from './uniffi_runtime.js';

const _rt = await UniffiRuntime.load(new URL('./keywords_demo.wasm', import.meta.url), 'crate_name');

export class ThrowKind extends Error {
  override readonly name = 'ThrowKind' as const;
  constructor(public readonly tag: 'catch' | 'finally') {
    super(tag);
  }
  static catch_(): ThrowKind { return new ThrowKind('catch'); }
  static finally_(): ThrowKind { return new ThrowKind('finally'); }
}

export interface ReturnValue {
  class_: string;
  return_: number;
  typeof_: boolean;
}

export type AsyncKind = 'void' | 'yield' | 'await';

export class SuperWidget {
  /** @internal */
  readonly _handle: bigint;
  private _freed = false;
  private _assertLive(): void {
    if (this._freed) throw new Error('SuperWidget object has been freed');
  }
  private constructor(handle: bigint) {
    this._handle = handle;
    _rt.registerPointer(this, 'uniffi_crate_name_fn_free_superwidget', handle);
  }
  /** @internal */
  static _fromHandle(handle: bigint): SuperWidget { return new SuperWidget(handle); }
  static create(): SuperWidget {
    const _argPtr = 0;
    const _retPtr = _rt.scratchAlloc(5 * 8);
    try {
      _rt.call('uniffi_ffibuffer_crate_name_fn_constructor_superwidget_new', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 8);
      const _result = _rt.readHandleElement(_retPtr);
      return new SuperWidget(_result);
    } finally {
      _rt.scratchReset();
    }
  }
  class_(var_: string): string {
    this._assertLive();
    const _clonedHandle = _rt.cloneObjectHandle('uniffi_crate_name_fn_clone_superwidget', this._handle);
    const _rb_var_ = _rt.lowerString(var_);
    const _argPtr = _rt.scratchAlloc(4 * 8);
    _rt.writeHandleElement(_argPtr, _clonedHandle);
    _rt.writeRustBufferElements(_argPtr + 8, _rb_var_);
    const _retPtr = _rt.scratchAlloc(7 * 8);
    try {
      _rt.call('uniffi_ffibuffer_crate_name_fn_method_superwidget_class', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 24);
      const _result = _rt.liftString(_rt.readRustBufferElements(_retPtr));
      return _result;
    } finally {
      _rt.scratchReset();
    }
  }
  return_(): number {
    this._assertLive();
    const _clonedHandle = _rt.cloneObjectHandle('uniffi_crate_name_fn_clone_superwidget', this._handle);
    const _argPtr = _rt.scratchAlloc(1 * 8);
    _rt.writeHandleElement(_argPtr, _clonedHandle);
    const _retPtr = _rt.scratchAlloc(5 * 8);
    try {
      _rt.call('uniffi_ffibuffer_crate_name_fn_method_superwidget_return', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 8);
      const _result = _rt.readU32Element(_retPtr);
      return _result;
    } finally {
      _rt.scratchReset();
    }
  }
  /** Releases the underlying WASM resource. Safe to call more than once. */
  free(): void {
    if (this._freed) return;
    this._freed = true;
    _rt.unregisterPointer(this);
    _rt.callFree('uniffi_crate_name_fn_free_superwidget', this._handle);
  }
}
if (Symbol.dispose) (SuperWidget as any).prototype[Symbol.dispose] = SuperWidget.prototype.free;

// --- Serialization helpers ---

function _lowerReturnValue(w: UniFFIWriter, value: ReturnValue): void {
  w.writeString(value.class_);
  w.writeU32(value.return_);
  w.writeBool(value.typeof_);
}
function _liftReturnValue(r: UniFFIReader): ReturnValue {
  return {
    class_: r.readString(),
    return_: r.readU32(),
    typeof_: r.readBool(),
  };
}

function _lowerAsyncKind(w: UniFFIWriter, value: AsyncKind): void {
  if (value === 'void') { w.writeI32(1); return; }
  if (value === 'yield') { w.writeI32(2); return; }
  if (value === 'await') { w.writeI32(3); return; }
  throw new Error(`Unknown AsyncKind variant: ${value}`);
}
function _liftAsyncKind(r: UniFFIReader): AsyncKind {
  const ordinal = r.readI32();
  if (ordinal === 1) return 'void';
  if (ordinal === 2) return 'yield';
  if (ordinal === 3) return 'await';
  throw new Error(`Unknown AsyncKind ordinal: ${ordinal}`);
}

export namespace KeywordsDemo {
  export function class_(switch_: number): number {
    const _argPtr = _rt.scratchAlloc(1 * 8);
    _rt.writeU32Element(_argPtr, switch_);
    const _retPtr = _rt.scratchAlloc(5 * 8);
    try {
      _rt.call('uniffi_ffibuffer_crate_name_fn_func_class', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 8);
      const _result = _rt.readU32Element(_retPtr);
      return _result;
    } finally {
      _rt.scratchReset();
    }
  }
  export function delete_(static_: boolean): boolean {
    const _argPtr = _rt.scratchAlloc(1 * 8);
    _rt.writeBoolElement(_argPtr, static_);
    const _retPtr = _rt.scratchAlloc(5 * 8);
    try {
      _rt.call('uniffi_ffibuffer_crate_name_fn_func_delete', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 8);
      const _result = _rt.readBoolElement(_retPtr);
      return _result;
    } finally {
      _rt.scratchReset();
    }
  }
  export function return_(var_: string): string {
    const _rb_var_ = _rt.lowerString(var_);
    const _argPtr = _rt.scratchAlloc(3 * 8);
    _rt.writeRustBufferElements(_argPtr, _rb_var_);
    const _retPtr = _rt.scratchAlloc(7 * 8);
    try {
      _rt.call('uniffi_ffibuffer_crate_name_fn_func_return', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 24);
      const _result = _rt.liftString(_rt.readRustBufferElements(_retPtr));
      return _result;
    } finally {
      _rt.scratchReset();
    }
  }
}
