// Generated by uniffi-bindgen-js. DO NOT EDIT.
import __init, * as __bg from './keywords_demo_bg.js';
export { __init as init };

export class ThrowKind extends Error {
  override readonly name = 'ThrowKind' as const;
  constructor(public readonly tag: 'catch' | 'finally') {
    super(tag);
  }
  static catch_(): ThrowKind { return new ThrowKind('catch'); }
  static finally_(): ThrowKind { return new ThrowKind('finally'); }
}

export interface ReturnValue {
  class_: string;
  return_: number;
  typeof_: boolean;
}

export type AsyncKind = 'void' | 'yield' | 'await';

export class SuperWidget {
  private readonly _inner: __bg.SuperWidget;
  private _freed = false;
  private _assertLive(): void {
    if (this._freed) throw new Error('SuperWidget object has been freed');
  }
  private constructor(inner: __bg.SuperWidget) {
    this._inner = inner;
  }
  /** @internal */
  static _fromInner(inner: __bg.SuperWidget): SuperWidget { return new SuperWidget(inner); }
  static new(): SuperWidget { return SuperWidget._fromInner(new __bg.SuperWidget()); }
  class_(var_: string): string {
    this._assertLive();
    return this._inner["class"](var_);
  }
  return_(): number {
    this._assertLive();
    return this._inner["return"]();
  }
  /** Releases the underlying WASM resource. Safe to call more than once. */
  free(): void {
    if (this._freed) return;
    this._freed = true;
    this._inner.free();
  }
  [Symbol.dispose](): void { this.free(); }
}

export namespace KeywordsDemo {
  export function class_(switch_: number): number { return __bg._class(switch_); }
  export function delete_(static_: boolean): boolean { return __bg._delete(static_); }
  export function return_(var_: string): string { return __bg._return(var_); }
}
