// Generated by uniffi-bindgen-js. DO NOT EDIT.
import __init, * as __bg from './keywords_demo_bg.js';

function _uniffiEnsureApiIntegrity(): void {
  const bindingsContractVersion = 30;
  const scaffoldingContractVersion: number = (__bg as any).ffi_crate_name_uniffi_contract_version();
  if (bindingsContractVersion !== scaffoldingContractVersion) {
    throw new Error(`UniFFI contract version mismatch: expected ${bindingsContractVersion}, got ${scaffoldingContractVersion}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_class: number = (__bg as any).uniffi_crate_name_checksum_func_class();
  if (_checksum_uniffi_crate_name_checksum_func_class !== 18179) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_class\`: expected 18179, got ${_checksum_uniffi_crate_name_checksum_func_class}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_delete: number = (__bg as any).uniffi_crate_name_checksum_func_delete();
  if (_checksum_uniffi_crate_name_checksum_func_delete !== 19332) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_delete\`: expected 19332, got ${_checksum_uniffi_crate_name_checksum_func_delete}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_return: number = (__bg as any).uniffi_crate_name_checksum_func_return();
  if (_checksum_uniffi_crate_name_checksum_func_return !== 19859) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_return\`: expected 19859, got ${_checksum_uniffi_crate_name_checksum_func_return}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_superwidget_class: number = (__bg as any).uniffi_crate_name_checksum_method_superwidget_class();
  if (_checksum_uniffi_crate_name_checksum_method_superwidget_class !== 51245) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_superwidget_class\`: expected 51245, got ${_checksum_uniffi_crate_name_checksum_method_superwidget_class}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_superwidget_return: number = (__bg as any).uniffi_crate_name_checksum_method_superwidget_return();
  if (_checksum_uniffi_crate_name_checksum_method_superwidget_return !== 38599) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_superwidget_return\`: expected 38599, got ${_checksum_uniffi_crate_name_checksum_method_superwidget_return}`);
  }
  const _checksum_uniffi_crate_name_checksum_constructor_superwidget_new: number = (__bg as any).uniffi_crate_name_checksum_constructor_superwidget_new();
  if (_checksum_uniffi_crate_name_checksum_constructor_superwidget_new !== 33809) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_constructor_superwidget_new\`: expected 33809, got ${_checksum_uniffi_crate_name_checksum_constructor_superwidget_new}`);
  }
}
export async function init(...args: Parameters<typeof __init>): Promise<ReturnType<typeof __init>> {
  const result = await __init(...args);
  _uniffiEnsureApiIntegrity();
  return result;
}

export class ThrowKind extends Error {
  override readonly name = 'ThrowKind' as const;
  constructor(public readonly tag: 'catch' | 'finally') {
    super(tag);
  }
  static catch_(): ThrowKind { return new ThrowKind('catch'); }
  static finally_(): ThrowKind { return new ThrowKind('finally'); }
}

export interface ReturnValue {
  class_: string;
  return_: number;
  typeof_: boolean;
}

export type AsyncKind = 'void' | 'yield' | 'await';

export class SuperWidget {
  private readonly _inner: __bg.SuperWidget;
  private _freed = false;
  private _assertLive(): void {
    if (this._freed) throw new Error('SuperWidget object has been freed');
  }
  private constructor(inner: __bg.SuperWidget) {
    this._inner = inner;
  }
  /** @internal */
  static _fromInner(inner: __bg.SuperWidget): SuperWidget { return new SuperWidget(inner); }
  static new(): SuperWidget { return SuperWidget._fromInner(new __bg.SuperWidget()); }
  class_(var_: string): string {
    this._assertLive();
    return this._inner.class(var_);
  }
  return_(): number {
    this._assertLive();
    return this._inner.return();
  }
  /** Releases the underlying WASM resource. Safe to call more than once. */
  free(): void {
    if (this._freed) return;
    this._freed = true;
    this._inner.free();
  }
  [Symbol.dispose](): void { this.free(); }
}

export namespace KeywordsDemo {
  export function class_(switch_: number): number { return __bg.class(switch_); }
  export function delete_(static_: boolean): boolean { return __bg.delete(static_); }
  export function return_(var_: string): string { return __bg.return(var_); }
}
