// Generated by uniffi-bindgen-js. DO NOT EDIT.
import __init, * as __bg from './error_types_demo_bg.js';
export { __init as init };

export class ErrorInterface extends Error {
  private readonly _inner: __bg.ErrorInterface;
  private _freed = false;
  private _assertLive(): void {
    if (this._freed) throw new Error('ErrorInterface object has been freed');
  }
  private constructor(inner: __bg.ErrorInterface) {
    super('ErrorInterface');
    Object.defineProperty(this, 'name', { value: 'ErrorInterface' });
    this._inner = inner;
  }
  /** @internal */
  static _fromInner(inner: __bg.ErrorInterface): ErrorInterface { return new ErrorInterface(inner); }
  chain(): string[] {
    this._assertLive();
    return this._inner.chain();
  }
  link(index: bigint): string | null {
    this._assertLive();
    return this._inner.link(index) ?? null;
  }
  toString(): string { this._assertLive(); return __bg.error_interface_uniffi_trait_display(this._inner); }
  toDebugString(): string { this._assertLive(); return __bg.error_interface_uniffi_trait_debug(this._inner); }
  /** Releases the underlying WASM resource. Safe to call more than once. */
  free(): void {
    if (this._freed) return;
    this._freed = true;
    this._inner.free();
  }
  [Symbol.dispose](): void { this.free(); }
}
export class TestInterface {
  private readonly _inner: __bg.TestInterface;
  private _freed = false;
  private _assertLive(): void {
    if (this._freed) throw new Error('TestInterface object has been freed');
  }
  private constructor(inner: __bg.TestInterface) {
    this._inner = inner;
  }
  /** @internal */
  static _fromInner(inner: __bg.TestInterface): TestInterface { return new TestInterface(inner); }
  static new(): TestInterface { return TestInterface._fromInner(new __bg.TestInterface()); }
  oops(): void {
    this._assertLive();
    try { this._inner.oops(); } catch (e) { _liftErrorInterface(e); }
  }
  /** Releases the underlying WASM resource. Safe to call more than once. */
  free(): void {
    if (this._freed) return;
    this._freed = true;
    this._inner.free();
  }
  [Symbol.dispose](): void { this.free(); }
}

function _liftErrorInterface(e: unknown): never {
  if (e instanceof ErrorInterface) throw e;
  if (e instanceof __bg.ErrorInterface) throw ErrorInterface._fromInner(e);
  throw e;
}

export namespace ErrorTypesDemo {
  export function getError(message: string): ErrorInterface { return ErrorInterface._fromInner(__bg.get_error(message)); }
  export function oops(): void {
    try { __bg.oops(); } catch (e) { _liftErrorInterface(e); }
  }
}
