// Generated by uniffi-bindgen-js. DO NOT EDIT.
import { UniffiRuntime, UniFFIWriter, UniFFIReader } from './uniffi_runtime.js';

const _rt = await UniffiRuntime.load(new URL('./error_types_demo.wasm', import.meta.url), 'crate_name');

export class ErrorInterface extends Error {
  /** @internal */
  readonly _handle: bigint;
  private _freed = false;
  private _assertLive(): void {
    if (this._freed) throw new Error('ErrorInterface object has been freed');
  }
  private constructor(handle: bigint) {
    super('ErrorInterface');
    Object.defineProperty(this, 'name', { value: 'ErrorInterface' });
    this._handle = handle;
    _rt.registerPointer(this, 'uniffi_crate_name_fn_free_errorinterface', handle);
  }
  /** @internal */
  static _fromHandle(handle: bigint): ErrorInterface { return new ErrorInterface(handle); }
  chain(): string[] {
    this._assertLive();
    const _clonedHandle = _rt.cloneObjectHandle('uniffi_crate_name_fn_clone_errorinterface', this._handle);
    const _argPtr = _rt.scratchAlloc(1 * 8);
    _rt.writeHandleElement(_argPtr, _clonedHandle);
    const _retPtr = _rt.scratchAlloc(7 * 8);
    try {
      _rt.call('uniffi_ffibuffer_crate_name_fn_method_errorinterface_chain', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 24);
      const _result = _rt.liftFromBuffer(_rt.readRustBufferElements(_retPtr), (r) => { return r.readSequence((_r) => _r.readString()); });
      return _result;
    } finally {
      _rt.scratchReset();
    }
  }
  link(index: bigint): string | null {
    this._assertLive();
    const _clonedHandle = _rt.cloneObjectHandle('uniffi_crate_name_fn_clone_errorinterface', this._handle);
    const _argPtr = _rt.scratchAlloc(2 * 8);
    _rt.writeHandleElement(_argPtr, _clonedHandle);
    _rt.writeU64Element(_argPtr + 8, BigInt(index));
    const _retPtr = _rt.scratchAlloc(7 * 8);
    try {
      _rt.call('uniffi_ffibuffer_crate_name_fn_method_errorinterface_link', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 24);
      const _result = _rt.liftFromBuffer(_rt.readRustBufferElements(_retPtr), (r) => { return r.readOptional((_r) => _r.readString()); });
      return _result;
    } finally {
      _rt.scratchReset();
    }
  }
  toString(): string {
    this._assertLive();
    const _clonedHandle = _rt.cloneObjectHandle('uniffi_crate_name_fn_clone_errorinterface', this._handle);
    const _argPtr = _rt.scratchAlloc(1 * 8);
    _rt.writeHandleElement(_argPtr, _clonedHandle);
    const _retPtr = _rt.scratchAlloc(7 * 8);
    try {
      _rt.call('uniffi_ffibuffer_crate_name_fn_method_errorinterface_uniffi_trait_display', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 24);
      const _result = _rt.liftString(_rt.readRustBufferElements(_retPtr));
      return _result;
    } finally {
      _rt.scratchReset();
    }
  }
  toDebugString(): string {
    this._assertLive();
    const _clonedHandle = _rt.cloneObjectHandle('uniffi_crate_name_fn_clone_errorinterface', this._handle);
    const _argPtr = _rt.scratchAlloc(1 * 8);
    _rt.writeHandleElement(_argPtr, _clonedHandle);
    const _retPtr = _rt.scratchAlloc(7 * 8);
    try {
      _rt.call('uniffi_ffibuffer_crate_name_fn_method_errorinterface_uniffi_trait_debug', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 24);
      const _result = _rt.liftString(_rt.readRustBufferElements(_retPtr));
      return _result;
    } finally {
      _rt.scratchReset();
    }
  }
  /** Releases the underlying WASM resource. Safe to call more than once. */
  free(): void {
    if (this._freed) return;
    this._freed = true;
    _rt.unregisterPointer(this);
    _rt.callFree('uniffi_crate_name_fn_free_errorinterface', this._handle);
  }
}
if (Symbol.dispose) (ErrorInterface as any).prototype[Symbol.dispose] = ErrorInterface.prototype.free;

export class TestInterface {
  /** @internal */
  readonly _handle: bigint;
  private _freed = false;
  private _assertLive(): void {
    if (this._freed) throw new Error('TestInterface object has been freed');
  }
  private constructor(handle: bigint) {
    this._handle = handle;
    _rt.registerPointer(this, 'uniffi_crate_name_fn_free_testinterface', handle);
  }
  /** @internal */
  static _fromHandle(handle: bigint): TestInterface { return new TestInterface(handle); }
  static create(): TestInterface {
    const _argPtr = 0;
    const _retPtr = _rt.scratchAlloc(5 * 8);
    try {
      _rt.call('uniffi_ffibuffer_crate_name_fn_constructor_testinterface_new', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 8);
      const _result = _rt.readHandleElement(_retPtr);
      return new TestInterface(_result);
    } finally {
      _rt.scratchReset();
    }
  }
  /** @throws {ErrorInterface} */
  oops(): void {
    this._assertLive();
    const _clonedHandle = _rt.cloneObjectHandle('uniffi_crate_name_fn_clone_testinterface', this._handle);
    const _argPtr = _rt.scratchAlloc(1 * 8);
    _rt.writeHandleElement(_argPtr, _clonedHandle);
    const _retPtr = _rt.scratchAlloc(4 * 8);
    try {
      _rt.call('uniffi_ffibuffer_crate_name_fn_method_testinterface_oops', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr, (rb) => _liftErrorErrorInterface(rb));
    } finally {
      _rt.scratchReset();
    }
  }
  /** Releases the underlying WASM resource. Safe to call more than once. */
  free(): void {
    if (this._freed) return;
    this._freed = true;
    _rt.unregisterPointer(this);
    _rt.callFree('uniffi_crate_name_fn_free_testinterface', this._handle);
  }
}
if (Symbol.dispose) (TestInterface as any).prototype[Symbol.dispose] = TestInterface.prototype.free;

// --- Serialization helpers ---

function _liftErrorErrorInterface(rb: any): ErrorInterface {
  return _rt.liftFromBuffer(rb, (r) => {
    return ErrorInterface._fromHandle(r.readU64());
  });
}

export namespace ErrorTypesDemo {
  export function getError(message: string): ErrorInterface {
    const _rb_message = _rt.lowerString(message);
    const _argPtr = _rt.scratchAlloc(3 * 8);
    _rt.writeRustBufferElements(_argPtr, _rb_message);
    const _retPtr = _rt.scratchAlloc(5 * 8);
    try {
      _rt.call('uniffi_ffibuffer_crate_name_fn_func_get_error', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 8);
      const _result = _rt.readHandleElement(_retPtr);
      return ErrorInterface._fromHandle(_result);
    } finally {
      _rt.scratchReset();
    }
  }
  /** @throws {ErrorInterface} */
  export function oops(): void {
    const _argPtr = 0;
    const _retPtr = _rt.scratchAlloc(4 * 8);
    try {
      _rt.call('uniffi_ffibuffer_crate_name_fn_func_oops', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr, (rb) => _liftErrorErrorInterface(rb));
    } finally {
      _rt.scratchReset();
    }
  }
}
