// Generated by uniffi-bindgen-js. DO NOT EDIT.
import __init, * as __bg from './library_mode_bg.js';
export { __init as init };

export type MathErrorVariant =
  | { tag: 'DivisionByZero' }
  | { tag: 'Overflow' };

export class MathError extends Error {
  override readonly name = 'MathError' as const;
  constructor(public readonly variant: MathErrorVariant) {
    super(variant.tag);
  }
  static DivisionByZero(): MathError { return new MathError({ tag: 'DivisionByZero' }); }
  static Overflow(): MathError { return new MathError({ tag: 'Overflow' }); }
}

export interface Point {
  x: number;
  y: number;
}

export type Direction = 'North' | 'South' | 'East' | 'West';

function _liftMathError(e: unknown): never {
  try {
    const raw = typeof e === 'string' ? JSON.parse(e) : (e instanceof Error ? JSON.parse(e.message) : e);
    const tag = raw?.tag as string | undefined;
    if (tag === 'DivisionByZero') throw MathError.DivisionByZero();
    if (tag === 'Overflow') throw MathError.Overflow();
  } catch (inner) {
    if (inner instanceof MathError) throw inner;
  }
  throw e;
}

export namespace LibraryMode {
  export function add(a: number, b: number): number { return __bg.add(a, b); }
  /** @throws {MathError} */
  export function safeDivide(a: number, b: number): number {
    try { return __bg.safe_divide(a, b); } catch (e) { return _liftMathError(e); }
  }
  export function translate(point: Point, direction: Direction): Point { return __bg.translate(point, direction); }
}
