// Generated by uniffi-bindgen-js. DO NOT EDIT.
import { UniffiRuntime, UniFFIWriter, UniFFIReader } from './uniffi_runtime.js';

const _rt = await UniffiRuntime.load(new URL('./library_mode.wasm', import.meta.url), 'library_mode');

export type MathErrorVariant =
  | { tag: 'DivisionByZero' }
  | { tag: 'Overflow' };

export class MathError extends Error {
  override readonly name = 'MathError' as const;
  constructor(public readonly variant: MathErrorVariant) {
    super(variant.tag);
  }
  static DivisionByZero(): MathError { return new MathError({ tag: 'DivisionByZero' }); }
  static Overflow(): MathError { return new MathError({ tag: 'Overflow' }); }
}

export interface Point {
  x: number;
  y: number;
}

export type Direction = 'North' | 'South' | 'East' | 'West';

// --- Serialization helpers ---

function _lowerPoint(w: UniFFIWriter, value: Point): void {
  w.writeF64(value.x);
  w.writeF64(value.y);
}
function _liftPoint(r: UniFFIReader): Point {
  return {
    x: r.readF64(),
    y: r.readF64(),
  };
}

function _lowerDirection(w: UniFFIWriter, value: Direction): void {
  if (value === 'North') { w.writeI32(1); return; }
  if (value === 'South') { w.writeI32(2); return; }
  if (value === 'East') { w.writeI32(3); return; }
  if (value === 'West') { w.writeI32(4); return; }
  throw new Error(`Unknown Direction variant: ${value}`);
}
function _liftDirection(r: UniFFIReader): Direction {
  const ordinal = r.readI32();
  if (ordinal === 1) return 'North';
  if (ordinal === 2) return 'South';
  if (ordinal === 3) return 'East';
  if (ordinal === 4) return 'West';
  throw new Error(`Unknown Direction ordinal: ${ordinal}`);
}

function _liftErrorMathError(rb: any): MathError {
  return _rt.liftFromBuffer(rb, (r) => {
    const ordinal = r.readI32();
    if (ordinal === 1) {
      return new MathError({ tag: 'DivisionByZero' });
    }
    if (ordinal === 2) {
      return new MathError({ tag: 'Overflow' });
    }
    throw new Error(`Unknown MathError ordinal: ${ordinal}`);
  });
}

export namespace LibraryMode {
  export function add(a: number, b: number): number {
    const _argPtr = _rt.scratchAlloc(2 * 8);
    _rt.writeU32Element(_argPtr, a);
    _rt.writeU32Element(_argPtr + 8, b);
    const _retPtr = _rt.scratchAlloc(5 * 8);
    try {
      _rt.call('uniffi_ffibuffer_library_mode_fn_func_add', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 8);
      const _result = _rt.readU32Element(_retPtr);
      return _result;
    } finally {
      _rt.scratchReset();
    }
  }
  /** @throws {MathError} */
  export function safeDivide(a: number, b: number): number {
    const _argPtr = _rt.scratchAlloc(2 * 8);
    _rt.writeU32Element(_argPtr, a);
    _rt.writeU32Element(_argPtr + 8, b);
    const _retPtr = _rt.scratchAlloc(5 * 8);
    try {
      _rt.call('uniffi_ffibuffer_library_mode_fn_func_safe_divide', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 8, (rb) => _liftErrorMathError(rb));
      const _result = _rt.readU32Element(_retPtr);
      return _result;
    } finally {
      _rt.scratchReset();
    }
  }
  export function translate(point: Point, direction: Direction): Point {
    const _rb_point = _rt.lowerIntoBuffer((w) => { _lowerPoint(w, point); });
    const _rb_direction = _rt.lowerIntoBuffer((w) => { _lowerDirection(w, direction); });
    const _argPtr = _rt.scratchAlloc(6 * 8);
    _rt.writeRustBufferElements(_argPtr, _rb_point);
    _rt.writeRustBufferElements(_argPtr + 24, _rb_direction);
    const _retPtr = _rt.scratchAlloc(7 * 8);
    try {
      _rt.call('uniffi_ffibuffer_library_mode_fn_func_translate', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 24);
      const _result = _rt.liftFromBuffer(_rt.readRustBufferElements(_retPtr), (r) => { return _liftPoint(r); });
      return _result;
    } finally {
      _rt.scratchReset();
    }
  }
}
