// Generated by uniffi-bindgen-js. DO NOT EDIT.
import __init, * as __bg from './non_exhaustive_demo_bg.js';
export { __init as init };

export class AppError extends Error {
  override readonly name = 'AppError' as const;
  constructor(public readonly tag: 'NotFound' | 'PermissionDenied' | string) {
    super(tag);
  }
  static NotFound(): AppError { return new AppError('NotFound'); }
  static PermissionDenied(): AppError { return new AppError('PermissionDenied'); }
}

export type Status = 'Active' | 'Inactive' | string;
