// Generated by uniffi-bindgen-js. DO NOT EDIT.
import __init, * as __bg from './non_exhaustive_demo_bg.js';

function _uniffiEnsureApiIntegrity(): void {
  const bindingsContractVersion = 30;
  const scaffoldingContractVersion: number = (__bg as any).ffi_crate_name_uniffi_contract_version();
  if (bindingsContractVersion !== scaffoldingContractVersion) {
    throw new Error(`UniFFI contract version mismatch: expected ${bindingsContractVersion}, got ${scaffoldingContractVersion}`);
  }
}
export async function init(...args: Parameters<typeof __init>): Promise<ReturnType<typeof __init>> {
  const result = await __init(...args);
  _uniffiEnsureApiIntegrity();
  return result;
}

export class AppError extends Error {
  override readonly name = 'AppError' as const;
  constructor(public readonly tag: 'NotFound' | 'PermissionDenied' | string) {
    super(tag);
  }
  static NotFound(): AppError { return new AppError('NotFound'); }
  static PermissionDenied(): AppError { return new AppError('PermissionDenied'); }
}

export type Status = 'Active' | 'Inactive' | string;
