// Generated by uniffi-bindgen-js. DO NOT EDIT.
import { UniffiRuntime, UniFFIWriter, UniFFIReader } from './uniffi_runtime.js';

const _rt = await UniffiRuntime.load(new URL('./non_exhaustive_demo.wasm', import.meta.url), 'crate_name');

export class AppError extends Error {
  override readonly name = 'AppError' as const;
  constructor(public readonly tag: 'NotFound' | 'PermissionDenied' | (string & {})) {
    super(tag);
  }
  static NotFound(): AppError { return new AppError('NotFound'); }
  static PermissionDenied(): AppError { return new AppError('PermissionDenied'); }
}

export type Status = 'Active' | 'Inactive' | (string & {});

// --- Serialization helpers ---

function _lowerStatus(w: UniFFIWriter, value: Status): void {
  if (value === 'Active') { w.writeI32(1); return; }
  if (value === 'Inactive') { w.writeI32(2); return; }
  throw new Error(`Unknown Status variant: ${value}`);
}
function _liftStatus(r: UniFFIReader): Status {
  const ordinal = r.readI32();
  if (ordinal === 1) return 'Active';
  if (ordinal === 2) return 'Inactive';
  return `variant_${ordinal}` as Status;
}
