// Generated by uniffi-bindgen-js. DO NOT EDIT.
import { UniffiRuntime, UniFFIWriter, UniFFIReader } from './uniffi_runtime.js';

const _rt = await UniffiRuntime.load(new URL('./ext_types_demo.wasm', import.meta.url), 'ext_types_demo');
import { RemoteCounter, RemoteState, RemoteThing } from './other_bindings.js';

// --- Serialization helpers ---

export namespace ExtTypesDemo {
  /** Echo a RemoteThing back to the caller. */
  export function echoRemote(input: RemoteThing): RemoteThing {
    const _rb_input = _rt.lowerIntoBuffer((w) => { _lowerRemoteThing(w, input); });
    const _argPtr = _rt.scratchAlloc(3 * 8);
    _rt.writeRustBufferElements(_argPtr, _rb_input);
    const _retPtr = _rt.scratchAlloc(7 * 8);
    _rt.call('uniffi_ffibuffer_ext_types_demo_fn_func_echo_remote', _argPtr, _retPtr);
    _rt.checkCallStatus(_retPtr + 24);
    const _result = _rt.liftFromBuffer(_rt.readRustBufferElements(_retPtr), (r) => { return _liftRemoteThing(r); });
    _rt.scratchReset();
    return _result;
  }
  /** Echo a RemoteCounter back to the caller. */
  export function echoRemoteCounter(input: RemoteCounter): RemoteCounter {
    const _clone_input = _rt.cloneObjectHandle('uniffi_ext_types_demo_fn_clone_remotecounter', input._handle);
    const _argPtr = _rt.scratchAlloc(1 * 8);
    _rt.writeHandleElement(_argPtr, _clone_input);
    const _retPtr = _rt.scratchAlloc(5 * 8);
    _rt.call('uniffi_ffibuffer_ext_types_demo_fn_func_echo_remote_counter', _argPtr, _retPtr);
    _rt.checkCallStatus(_retPtr + 8);
    const _result = _rt.readHandleElement(_retPtr);
    _rt.scratchReset();
    return RemoteCounter._fromHandle(_result);
  }
  /** Echo a RemoteState back to the caller. */
  export function echoRemoteState(input: RemoteState): RemoteState {
    const _rb_input = _rt.lowerIntoBuffer((w) => { _lowerRemoteState(w, input); });
    const _argPtr = _rt.scratchAlloc(3 * 8);
    _rt.writeRustBufferElements(_argPtr, _rb_input);
    const _retPtr = _rt.scratchAlloc(7 * 8);
    _rt.call('uniffi_ffibuffer_ext_types_demo_fn_func_echo_remote_state', _argPtr, _retPtr);
    _rt.checkCallStatus(_retPtr + 24);
    const _result = _rt.liftFromBuffer(_rt.readRustBufferElements(_retPtr), (r) => { return _liftRemoteState(r); });
    _rt.scratchReset();
    return _result;
  }
  /**
   * Echo a list of RemoteThings (tests Sequence<ExternalRecord> recursive visitor).
   */
  export function listRemote(input: RemoteThing[]): RemoteThing[] {
    const _rb_input = _rt.lowerIntoBuffer((w) => { w.writeSequence(input, (_w, _v) => { _lowerRemoteThing(_w, _v); }); });
    const _argPtr = _rt.scratchAlloc(3 * 8);
    _rt.writeRustBufferElements(_argPtr, _rb_input);
    const _retPtr = _rt.scratchAlloc(7 * 8);
    _rt.call('uniffi_ffibuffer_ext_types_demo_fn_func_list_remote', _argPtr, _retPtr);
    _rt.checkCallStatus(_retPtr + 24);
    const _result = _rt.liftFromBuffer(_rt.readRustBufferElements(_retPtr), (r) => { return r.readSequence((_r) => _liftRemoteThing(_r)); });
    _rt.scratchReset();
    return _result;
  }
  /**
   * Echo a nullable RemoteThing (tests Optional<ExternalRecord> import deduplication).
   */
  export function maybeRemote(input: RemoteThing | null): RemoteThing | null {
    const _rb_input = _rt.lowerIntoBuffer((w) => { w.writeOptional(input, (_w, _v) => { _lowerRemoteThing(_w, _v); }); });
    const _argPtr = _rt.scratchAlloc(3 * 8);
    _rt.writeRustBufferElements(_argPtr, _rb_input);
    const _retPtr = _rt.scratchAlloc(7 * 8);
    _rt.call('uniffi_ffibuffer_ext_types_demo_fn_func_maybe_remote', _argPtr, _retPtr);
    _rt.checkCallStatus(_retPtr + 24);
    const _result = _rt.liftFromBuffer(_rt.readRustBufferElements(_retPtr), (r) => { return r.readOptional((_r) => _liftRemoteThing(_r)); });
    _rt.scratchReset();
    return _result;
  }
}
