// Generated by uniffi-bindgen-js. DO NOT EDIT.
import { UniffiRuntime, UniFFIWriter, UniFFIReader } from './uniffi_runtime.js';

const _rt = await UniffiRuntime.load(new URL('./regression.wasm', import.meta.url), 'regression');

/** Error raised by the safe divider. */
export class DivError extends Error {
  override readonly name = 'DivError' as const;
  constructor(public readonly tag: 'DivByZero' | 'Overflow') {
    super(tag);
  }
  static DivByZero(): DivError { return new DivError('DivByZero'); }
  static Overflow(): DivError { return new DivError('Overflow'); }
}

/**
 * An async transform callback — exercises [Async] on a callback interface method.
 */
export interface Transformer {
  /** Synchronous transform. */
  transform(input: string): string;
  /**
   * Asynchronous transform — return type must be Promise<string> in generated TS.
   */
  transformAsync(input: string): Promise<string>;
}

// --- VTable for callback interface Transformer ---
_rt.registerCallbackVTable('Transformer', 'uniffi_regression_fn_init_callback_vtable_transformer', [
  {
    params: ['i64'], results: [],
    fn: (handle: bigint) => { _rt.removeCallbackHandle(handle); },
  },
  {
    params: ['i64'], results: ['i64'],
    fn: (handle: bigint) => { return _rt.cloneCallbackHandle(handle); },
  },
  {
    params: ['i64', 'i32', 'i32', 'i32'], results: [],
    fn: (_handle: bigint, _arg0: number, _outPtr: number, _statusPtr: number) => {
      const _savedScratch = _rt.scratchSave();
      try {
        const _obj = _rt.getCallbackHandle(_handle) as any;
        const _lifted0 = (() => { const _rb = _rt._readRustBufferStruct(_arg0); return _rt._readUtf8(_rb.dataPtr, _rb.len); })();
        const _result = _obj.transform(_lifted0);
        const _retRb = _rt.lowerString(_result); _rt._writeRustBufferStruct(_outPtr, _retRb);
        _rt._writeCallStatusSuccess(_statusPtr);
      } catch (_e) {
        _rt._writeCallStatusPanic(_statusPtr, _e);
      } finally {
        _rt.scratchRestore(_savedScratch);
      }
    },
  },
  {
    params: ['i64', 'i32', 'i32', 'i32'], results: [],
    fn: (_handle: bigint, _arg0: number, _outPtr: number, _statusPtr: number) => {
      const _savedScratch = _rt.scratchSave();
      try {
        const _obj = _rt.getCallbackHandle(_handle) as any;
        const _lifted0 = (() => { const _rb = _rt._readRustBufferStruct(_arg0); return _rt._readUtf8(_rb.dataPtr, _rb.len); })();
        const _result = _obj.transformAsync(_lifted0);
        const _retRb = _rt.lowerString(_result); _rt._writeRustBufferStruct(_outPtr, _retRb);
        _rt._writeCallStatusSuccess(_statusPtr);
      } catch (_e) {
        _rt._writeCallStatusPanic(_statusPtr, _e);
      } finally {
        _rt.scratchRestore(_savedScratch);
      }
    },
  },
]);

/**
 * Exercises three regression cases on a single object:
 * 1. A named constructor with [Throws].
 * 2. A method that throws AND returns a value (the try-return branch).
 * 3. An [Async] method.
 */
export class SafeDivider {
  /** @internal */
  readonly _handle: bigint;
  private _freed = false;
  private _assertLive(): void {
    if (this._freed) throw new Error('SafeDivider object has been freed');
  }
  private constructor(handle: bigint) {
    this._handle = handle;
    _rt.registerPointer(this, 'uniffi_regression_fn_free_safedivider', handle);
  }
  /** @internal */
  static _fromHandle(handle: bigint): SafeDivider { return new SafeDivider(handle); }
  /** Default constructor — always succeeds. */
  static create(initial: number): SafeDivider {
    const _argPtr = _rt.scratchAlloc(1 * 8);
    _rt.writeI32Element(_argPtr, initial);
    const _retPtr = _rt.scratchAlloc(5 * 8);
    try {
      _rt.call('uniffi_ffibuffer_regression_fn_constructor_safedivider_new', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 8);
      const _result = _rt.readHandleElement(_retPtr);
      return new SafeDivider(_result);
    } finally {
      _rt.scratchReset();
    }
  }
  /**
   * Named constructor that can fail — exercises named-ctor [Throws] path.
   * @throws {DivError}
   */
  static fromPositive(initial: number): SafeDivider {
    const _argPtr = _rt.scratchAlloc(1 * 8);
    _rt.writeI32Element(_argPtr, initial);
    const _retPtr = _rt.scratchAlloc(5 * 8);
    try {
      _rt.call('uniffi_ffibuffer_regression_fn_constructor_safedivider_from_positive', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 8, (rb) => _liftErrorDivError(rb));
      const _result = _rt.readHandleElement(_retPtr);
      return new SafeDivider(_result);
    } finally {
      _rt.scratchReset();
    }
  }
  /**
   * Divide and return the result — exercises method [Throws] + return branch.
   * @throws {DivError}
   */
  divide(divisor: number): number {
    this._assertLive();
    const _clonedHandle = _rt.cloneObjectHandle('uniffi_regression_fn_clone_safedivider', this._handle);
    const _argPtr = _rt.scratchAlloc(2 * 8);
    _rt.writeHandleElement(_argPtr, _clonedHandle);
    _rt.writeI32Element(_argPtr + 8, divisor);
    const _retPtr = _rt.scratchAlloc(5 * 8);
    try {
      _rt.call('uniffi_ffibuffer_regression_fn_method_safedivider_divide', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 8, (rb) => _liftErrorDivError(rb));
      const _result = _rt.readI32Element(_retPtr);
      return _result;
    } finally {
      _rt.scratchReset();
    }
  }
  /**
   * Asynchronously compute the square — exercises [Async] method on interface.
   */
  async squareAsync(): Promise<number> {
    this._assertLive();
    const _clonedHandle = _rt.cloneObjectHandle('uniffi_regression_fn_clone_safedivider', this._handle);
    const _argPtr = _rt.scratchAlloc(1 * 8);
    _rt.writeHandleElement(_argPtr, _clonedHandle);
    const _retPtr = _rt.scratchAlloc(1 * 8);
    _rt.call('uniffi_ffibuffer_regression_fn_method_safedivider_square_async', _argPtr, _retPtr);
    const _futureHandle = _rt.readHandleElement(_retPtr);
    try {
      await _rt.pollToReady(_futureHandle, 'ffi_regression_rust_future_poll_i32');
      _rt.scratchReset();
      const _statusPtr = _rt.scratchAlloc(32);
      _rt._writeRustCallStatusStruct(_statusPtr);
      const _result = (_rt.getExport('ffi_regression_rust_future_complete_i32') as any)(_futureHandle, _statusPtr);
      _rt.checkCallStatus(_statusPtr);
      return _result;
    } finally {
      _rt.scratchReset();
      (_rt.getExport('ffi_regression_rust_future_free_i32') as any)(_futureHandle);
    }
  }
  /** Releases the underlying WASM resource. Safe to call more than once. */
  free(): void {
    if (this._freed) return;
    this._freed = true;
    _rt.unregisterPointer(this);
    _rt.callFree('uniffi_regression_fn_free_safedivider', this._handle);
  }
}
if (Symbol.dispose) (SafeDivider as any).prototype[Symbol.dispose] = SafeDivider.prototype.free;

// --- Serialization helpers ---

function _liftErrorDivError(rb: any): DivError {
  return _rt.liftFromBuffer(rb, (r) => {
    const ordinal = r.readI32();
    if (ordinal === 1) return new DivError('DivByZero');
    if (ordinal === 2) return new DivError('Overflow');
    throw new Error(`Unknown DivError ordinal: ${ordinal}`);
  });
}

export namespace Regression {
  /** Apply a transformer to a value. */
  export function apply(t: Transformer, value: string): string {
    const _rb_value = _rt.lowerString(value);
    const _argPtr = _rt.scratchAlloc(4 * 8);
    _rt.writeHandleElement(_argPtr, _rt.insertCallbackHandle(t));
    _rt.writeRustBufferElements(_argPtr + 8, _rb_value);
    const _retPtr = _rt.scratchAlloc(7 * 8);
    try {
      _rt.call('uniffi_ffibuffer_regression_fn_func_apply', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 24);
      const _result = _rt.liftString(_rt.readRustBufferElements(_retPtr));
      return _result;
    } finally {
      _rt.scratchReset();
    }
  }
}
