// Generated by uniffi-bindgen-js. DO NOT EDIT.
import __init, * as __bg from './regression_bg.js';
export { __init as init };

/** Error raised by the safe divider. */
export class DivError extends Error {
  override readonly name = 'DivError' as const;
  constructor(public readonly tag: 'DivByZero' | 'Overflow') {
    super(tag);
  }
  static DivByZero(): DivError { return new DivError('DivByZero'); }
  static Overflow(): DivError { return new DivError('Overflow'); }
}

/**
 * An async transform callback — exercises [Async] on a callback interface method.
 */
export interface Transformer {
  /** Synchronous transform. */
  transform(input: string): string;
  /**
   * Asynchronous transform — return type must be Promise<string> in generated TS.
   */
  transformAsync(input: string): Promise<string>;
}

/**
 * Exercises three regression cases on a single object:
 * 1. A named constructor with [Throws].
 * 2. A method that throws AND returns a value (the try-return branch).
 * 3. An [Async] method.
 */
export class SafeDivider {
  private readonly _inner: __bg.SafeDivider;
  private _freed = false;
  private _assertLive(): void {
    if (this._freed) throw new Error('SafeDivider object has been freed');
  }
  private constructor(inner: __bg.SafeDivider) {
    this._inner = inner;
  }
  /** @internal */
  static _fromInner(inner: __bg.SafeDivider): SafeDivider { return new SafeDivider(inner); }
  /** Default constructor — always succeeds. */
  static new(initial: number): SafeDivider { return SafeDivider._fromInner(new __bg.SafeDivider(initial)); }
  /** Named constructor that can fail — exercises named-ctor [Throws] path. */
  static fromPositive(initial: number): SafeDivider {
    try { return SafeDivider._fromInner(__bg.safe_divider_from_positive(initial)); } catch (e) { return _liftDivError(e); }
  }
  /**
   * Divide and return the result — exercises method [Throws] + return branch.
   */
  divide(divisor: number): number {
    this._assertLive();
    try { return this._inner.divide(divisor); } catch (e) { return _liftDivError(e); }
  }
  /**
   * Asynchronously compute the square — exercises [Async] method on interface.
   */
  async squareAsync(): Promise<number> {
    this._assertLive();
    return await this._inner.square_async();
  }
  /** Releases the underlying WASM resource. Safe to call more than once. */
  free(): void {
    if (this._freed) return;
    this._freed = true;
    this._inner.free();
  }
  [Symbol.dispose](): void { this.free(); }
}

function _liftDivError(e: unknown): never {
  const tag = typeof e === 'string' ? e : (e instanceof Error ? e.message : null);
  if (tag === 'DivByZero') throw new DivError('DivByZero');
  if (tag === 'Overflow') throw new DivError('Overflow');
  throw e;
}

export namespace Regression {
  /** Apply a transformer to a value. */
  export function apply(t: Transformer, value: string): string { return __bg.apply(t, value); }
}
