// Generated by uniffi-bindgen-js. DO NOT EDIT.
import __init, * as __bg from './type_zoo_bg.js';

function _uniffiEnsureApiIntegrity(): void {
  const bindingsContractVersion = 30;
  const scaffoldingContractVersion: number = (__bg as any).ffi_crate_name_uniffi_contract_version();
  if (bindingsContractVersion !== scaffoldingContractVersion) {
    throw new Error(`UniFFI contract version mismatch: expected ${bindingsContractVersion}, got ${scaffoldingContractVersion}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_echo_bigints: number = (__bg as any).uniffi_crate_name_checksum_func_echo_bigints();
  if (_checksum_uniffi_crate_name_checksum_func_echo_bigints !== 11489) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_echo_bigints\`: expected 11489, got ${_checksum_uniffi_crate_name_checksum_func_echo_bigints}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_echo_bool: number = (__bg as any).uniffi_crate_name_checksum_func_echo_bool();
  if (_checksum_uniffi_crate_name_checksum_func_echo_bool !== 52878) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_echo_bool\`: expected 52878, got ${_checksum_uniffi_crate_name_checksum_func_echo_bool}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_echo_bool_map: number = (__bg as any).uniffi_crate_name_checksum_func_echo_bool_map();
  if (_checksum_uniffi_crate_name_checksum_func_echo_bool_map !== 4456) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_echo_bool_map\`: expected 4456, got ${_checksum_uniffi_crate_name_checksum_func_echo_bool_map}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_echo_bytes: number = (__bg as any).uniffi_crate_name_checksum_func_echo_bytes();
  if (_checksum_uniffi_crate_name_checksum_func_echo_bytes !== 63941) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_echo_bytes\`: expected 63941, got ${_checksum_uniffi_crate_name_checksum_func_echo_bytes}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_echo_duration: number = (__bg as any).uniffi_crate_name_checksum_func_echo_duration();
  if (_checksum_uniffi_crate_name_checksum_func_echo_duration !== 18770) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_echo_duration\`: expected 18770, got ${_checksum_uniffi_crate_name_checksum_func_echo_duration}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_echo_f32: number = (__bg as any).uniffi_crate_name_checksum_func_echo_f32();
  if (_checksum_uniffi_crate_name_checksum_func_echo_f32 !== 9340) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_echo_f32\`: expected 9340, got ${_checksum_uniffi_crate_name_checksum_func_echo_f32}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_echo_f64: number = (__bg as any).uniffi_crate_name_checksum_func_echo_f64();
  if (_checksum_uniffi_crate_name_checksum_func_echo_f64 !== 27151) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_echo_f64\`: expected 27151, got ${_checksum_uniffi_crate_name_checksum_func_echo_f64}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_echo_i16: number = (__bg as any).uniffi_crate_name_checksum_func_echo_i16();
  if (_checksum_uniffi_crate_name_checksum_func_echo_i16 !== 39702) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_echo_i16\`: expected 39702, got ${_checksum_uniffi_crate_name_checksum_func_echo_i16}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_echo_i32: number = (__bg as any).uniffi_crate_name_checksum_func_echo_i32();
  if (_checksum_uniffi_crate_name_checksum_func_echo_i32 !== 41236) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_echo_i32\`: expected 41236, got ${_checksum_uniffi_crate_name_checksum_func_echo_i32}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_echo_i64: number = (__bg as any).uniffi_crate_name_checksum_func_echo_i64();
  if (_checksum_uniffi_crate_name_checksum_func_echo_i64 !== 17012) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_echo_i64\`: expected 17012, got ${_checksum_uniffi_crate_name_checksum_func_echo_i64}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_echo_i8: number = (__bg as any).uniffi_crate_name_checksum_func_echo_i8();
  if (_checksum_uniffi_crate_name_checksum_func_echo_i8 !== 13263) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_echo_i8\`: expected 13263, got ${_checksum_uniffi_crate_name_checksum_func_echo_i8}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_echo_map: number = (__bg as any).uniffi_crate_name_checksum_func_echo_map();
  if (_checksum_uniffi_crate_name_checksum_func_echo_map !== 26903) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_echo_map\`: expected 26903, got ${_checksum_uniffi_crate_name_checksum_func_echo_map}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_echo_string: number = (__bg as any).uniffi_crate_name_checksum_func_echo_string();
  if (_checksum_uniffi_crate_name_checksum_func_echo_string !== 33107) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_echo_string\`: expected 33107, got ${_checksum_uniffi_crate_name_checksum_func_echo_string}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_echo_strings: number = (__bg as any).uniffi_crate_name_checksum_func_echo_strings();
  if (_checksum_uniffi_crate_name_checksum_func_echo_strings !== 5389) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_echo_strings\`: expected 5389, got ${_checksum_uniffi_crate_name_checksum_func_echo_strings}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_echo_timestamp: number = (__bg as any).uniffi_crate_name_checksum_func_echo_timestamp();
  if (_checksum_uniffi_crate_name_checksum_func_echo_timestamp !== 43624) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_echo_timestamp\`: expected 43624, got ${_checksum_uniffi_crate_name_checksum_func_echo_timestamp}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_echo_u16: number = (__bg as any).uniffi_crate_name_checksum_func_echo_u16();
  if (_checksum_uniffi_crate_name_checksum_func_echo_u16 !== 32979) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_echo_u16\`: expected 32979, got ${_checksum_uniffi_crate_name_checksum_func_echo_u16}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_echo_u32: number = (__bg as any).uniffi_crate_name_checksum_func_echo_u32();
  if (_checksum_uniffi_crate_name_checksum_func_echo_u32 !== 52574) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_echo_u32\`: expected 52574, got ${_checksum_uniffi_crate_name_checksum_func_echo_u32}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_echo_u64: number = (__bg as any).uniffi_crate_name_checksum_func_echo_u64();
  if (_checksum_uniffi_crate_name_checksum_func_echo_u64 !== 32337) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_echo_u64\`: expected 32337, got ${_checksum_uniffi_crate_name_checksum_func_echo_u64}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_echo_u8: number = (__bg as any).uniffi_crate_name_checksum_func_echo_u8();
  if (_checksum_uniffi_crate_name_checksum_func_echo_u8 !== 2252) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_echo_u8\`: expected 2252, got ${_checksum_uniffi_crate_name_checksum_func_echo_u8}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_maybe_string: number = (__bg as any).uniffi_crate_name_checksum_func_maybe_string();
  if (_checksum_uniffi_crate_name_checksum_func_maybe_string !== 25945) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_maybe_string\`: expected 25945, got ${_checksum_uniffi_crate_name_checksum_func_maybe_string}`);
  }
}
export async function init(...args: Parameters<typeof __init>): Promise<ReturnType<typeof __init>> {
  const result = await __init(...args);
  _uniffiEnsureApiIntegrity();
  return result;
}

export namespace TypeZoo {
  export function echoBigints(items: bigint[]): bigint[] { return __bg.echo_bigints(items); }
  export function echoBool(v: boolean): boolean { return __bg.echo_bool(v); }
  export function echoBoolMap(m: Map<string, boolean>): Map<string, boolean> { return __bg.echo_bool_map(m); }
  export function echoBytes(data: Uint8Array): Uint8Array { return __bg.echo_bytes(data); }
  export function echoDuration(d: number): number { return __bg.echo_duration(d); }
  export function echoF32(v: number): number { return __bg.echo_f32(v); }
  export function echoF64(v: number): number { return __bg.echo_f64(v); }
  export function echoI16(v: number): number { return __bg.echo_i16(v); }
  export function echoI32(v: number): number { return __bg.echo_i32(v); }
  export function echoI64(v: bigint): bigint { return __bg.echo_i64(v); }
  export function echoI8(v: number): number { return __bg.echo_i8(v); }
  export function echoMap(m: Map<string, number>): Map<string, number> { return __bg.echo_map(m); }
  export function echoString(v: string): string { return __bg.echo_string(v); }
  export function echoStrings(items: string[]): string[] { return __bg.echo_strings(items); }
  export function echoTimestamp(t: Date): Date { return __bg.echo_timestamp(t); }
  export function echoU16(v: number): number { return __bg.echo_u16(v); }
  export function echoU32(v: number): number { return __bg.echo_u32(v); }
  export function echoU64(v: bigint): bigint { return __bg.echo_u64(v); }
  export function echoU8(v: number): number { return __bg.echo_u8(v); }
  export function maybeString(input: string | null): string | null { return __bg.maybe_string(input); }
}
