// Generated by uniffi-bindgen-js. DO NOT EDIT.
import __init, * as __bg from './type_zoo_bg.js';
export { __init as init };

export namespace TypeZoo {
  export function echoBigints(items: BigInt64Array): BigInt64Array { return __bg.echo_bigints(items); }
  export function echoBool(v: boolean): boolean { return __bg.echo_bool(v); }
  export function echoBoolMap(m: Map<string, boolean>): Map<string, boolean> { return __bg.echo_bool_map(m); }
  export function echoBytes(data: Uint8Array): Uint8Array { return __bg.echo_bytes(data); }
  /**
   * @param d - Duration in seconds.
   * @returns Duration in seconds.
   */
  export function echoDuration(d: number): number { return __bg.echo_duration(d); }
  export function echoF32(v: number): number { return __bg.echo_f32(v); }
  export function echoF64(v: number): number { return __bg.echo_f64(v); }
  export function echoI16(v: number): number { return __bg.echo_i16(v); }
  export function echoI32(v: number): number { return __bg.echo_i32(v); }
  export function echoI64(v: bigint): bigint { return __bg.echo_i64(v); }
  export function echoI8(v: number): number { return __bg.echo_i8(v); }
  export function echoMap(m: Map<string, number>): Map<string, number> { return __bg.echo_map(m); }
  export function echoString(v: string): string { return __bg.echo_string(v); }
  export function echoStrings(items: string[]): string[] { return __bg.echo_strings(items); }
  export function echoTimestamp(t: Date): Date { return __bg.echo_timestamp(t); }
  export function echoU16(v: number): number { return __bg.echo_u16(v); }
  export function echoU32(v: number): number { return __bg.echo_u32(v); }
  export function echoU64(v: bigint): bigint { return __bg.echo_u64(v); }
  export function echoU8(v: number): number { return __bg.echo_u8(v); }
  export function maybeString(input: string | null): string | null { return __bg.maybe_string(input) ?? null; }
}
