// Generated by uniffi-bindgen-js. DO NOT EDIT.
import __init, * as __bg from './simple_fns_bg.js';
export { __init as init };

export namespace SimpleFns {
  export function addMaybe(a: number, b: number | null = null): number { return __bg.add_maybe(a, b); }
  export function greet(name: string): string { return __bg.greet(name); }
  export async function greetAsync(name: string): Promise<string> { return await __bg.greet_async(name); }
  export function greetOptional(name: string | null = null): string { return __bg.greet_optional(name); }
}
