// Generated by uniffi-bindgen-js. DO NOT EDIT.
import __init, * as __bg from './simple_fns_bg.js';

function _uniffiEnsureApiIntegrity(): void {
  const bindingsContractVersion = 30;
  const scaffoldingContractVersion: number = (__bg as any).ffi_crate_name_uniffi_contract_version();
  if (bindingsContractVersion !== scaffoldingContractVersion) {
    throw new Error(`UniFFI contract version mismatch: expected ${bindingsContractVersion}, got ${scaffoldingContractVersion}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_greet: number = (__bg as any).uniffi_crate_name_checksum_func_greet();
  if (_checksum_uniffi_crate_name_checksum_func_greet !== 51217) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_greet\`: expected 51217, got ${_checksum_uniffi_crate_name_checksum_func_greet}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_greet_async: number = (__bg as any).uniffi_crate_name_checksum_func_greet_async();
  if (_checksum_uniffi_crate_name_checksum_func_greet_async !== 22773) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_greet_async\`: expected 22773, got ${_checksum_uniffi_crate_name_checksum_func_greet_async}`);
  }
}
export async function init(...args: Parameters<typeof __init>): Promise<ReturnType<typeof __init>> {
  const result = await __init(...args);
  _uniffiEnsureApiIntegrity();
  return result;
}

export namespace SimpleFns {
  export function greet(name: string): string { return __bg.greet(name); }
  export async function greetAsync(name: string): Promise<string> { return await __bg.greet_async(name); }
}
