// Generated by uniffi-bindgen-js. DO NOT EDIT.
import __init, * as __bg from './simple_fns_bg.js';
export { __init as init };

export namespace SimpleFns {
  export function greet(name: string): string {
    return __bg.greet(name);
  }
}
