// Generated by uniffi-bindgen-js. DO NOT EDIT.
import { UniffiRuntime, UniFFIWriter, UniFFIReader } from './uniffi_runtime.js';

const _rt = await UniffiRuntime.load(new URL('./type_limits_demo.wasm', import.meta.url), 'crate_name');

export class LargeError extends Error {
  override readonly name = 'LargeError' as const;
  constructor(public readonly tag: 'Case1' | 'Case2' | 'Case3' | 'Case4' | 'Case5' | 'Case6' | 'Case7' | 'Case8' | 'Case9' | 'Case10' | 'Case11' | 'Case12' | 'Case13' | 'Case14' | 'Case15' | 'Case16' | 'Case17' | 'Case18' | 'Case19' | 'Case20' | 'Case21' | 'Case22' | 'Case23' | 'Case24' | 'Case25' | 'Case26' | 'Case27' | 'Case28' | 'Case29' | 'Case30') {
    super(tag);
  }
  static Case1(): LargeError { return new LargeError('Case1'); }
  static Case2(): LargeError { return new LargeError('Case2'); }
  static Case3(): LargeError { return new LargeError('Case3'); }
  static Case4(): LargeError { return new LargeError('Case4'); }
  static Case5(): LargeError { return new LargeError('Case5'); }
  static Case6(): LargeError { return new LargeError('Case6'); }
  static Case7(): LargeError { return new LargeError('Case7'); }
  static Case8(): LargeError { return new LargeError('Case8'); }
  static Case9(): LargeError { return new LargeError('Case9'); }
  static Case10(): LargeError { return new LargeError('Case10'); }
  static Case11(): LargeError { return new LargeError('Case11'); }
  static Case12(): LargeError { return new LargeError('Case12'); }
  static Case13(): LargeError { return new LargeError('Case13'); }
  static Case14(): LargeError { return new LargeError('Case14'); }
  static Case15(): LargeError { return new LargeError('Case15'); }
  static Case16(): LargeError { return new LargeError('Case16'); }
  static Case17(): LargeError { return new LargeError('Case17'); }
  static Case18(): LargeError { return new LargeError('Case18'); }
  static Case19(): LargeError { return new LargeError('Case19'); }
  static Case20(): LargeError { return new LargeError('Case20'); }
  static Case21(): LargeError { return new LargeError('Case21'); }
  static Case22(): LargeError { return new LargeError('Case22'); }
  static Case23(): LargeError { return new LargeError('Case23'); }
  static Case24(): LargeError { return new LargeError('Case24'); }
  static Case25(): LargeError { return new LargeError('Case25'); }
  static Case26(): LargeError { return new LargeError('Case26'); }
  static Case27(): LargeError { return new LargeError('Case27'); }
  static Case28(): LargeError { return new LargeError('Case28'); }
  static Case29(): LargeError { return new LargeError('Case29'); }
  static Case30(): LargeError { return new LargeError('Case30'); }
}

export type LargeEnum = 'Variant1' | 'Variant2' | 'Variant3' | 'Variant4' | 'Variant5' | 'Variant6' | 'Variant7' | 'Variant8' | 'Variant9' | 'Variant10' | 'Variant11' | 'Variant12' | 'Variant13' | 'Variant14' | 'Variant15' | 'Variant16' | 'Variant17' | 'Variant18' | 'Variant19' | 'Variant20' | 'Variant21' | 'Variant22' | 'Variant23' | 'Variant24' | 'Variant25' | 'Variant26' | 'Variant27' | 'Variant28' | 'Variant29' | 'Variant30' | 'Variant31' | 'Variant32' | 'Variant33' | 'Variant34' | 'Variant35' | 'Variant36' | 'Variant37' | 'Variant38' | 'Variant39' | 'Variant40' | 'Variant41' | 'Variant42' | 'Variant43' | 'Variant44' | 'Variant45' | 'Variant46' | 'Variant47' | 'Variant48' | 'Variant49' | 'Variant50';

// --- Serialization helpers ---

function _lowerLargeEnum(w: UniFFIWriter, value: LargeEnum): void {
  if (value === 'Variant1') { w.writeI32(1); return; }
  if (value === 'Variant2') { w.writeI32(2); return; }
  if (value === 'Variant3') { w.writeI32(3); return; }
  if (value === 'Variant4') { w.writeI32(4); return; }
  if (value === 'Variant5') { w.writeI32(5); return; }
  if (value === 'Variant6') { w.writeI32(6); return; }
  if (value === 'Variant7') { w.writeI32(7); return; }
  if (value === 'Variant8') { w.writeI32(8); return; }
  if (value === 'Variant9') { w.writeI32(9); return; }
  if (value === 'Variant10') { w.writeI32(10); return; }
  if (value === 'Variant11') { w.writeI32(11); return; }
  if (value === 'Variant12') { w.writeI32(12); return; }
  if (value === 'Variant13') { w.writeI32(13); return; }
  if (value === 'Variant14') { w.writeI32(14); return; }
  if (value === 'Variant15') { w.writeI32(15); return; }
  if (value === 'Variant16') { w.writeI32(16); return; }
  if (value === 'Variant17') { w.writeI32(17); return; }
  if (value === 'Variant18') { w.writeI32(18); return; }
  if (value === 'Variant19') { w.writeI32(19); return; }
  if (value === 'Variant20') { w.writeI32(20); return; }
  if (value === 'Variant21') { w.writeI32(21); return; }
  if (value === 'Variant22') { w.writeI32(22); return; }
  if (value === 'Variant23') { w.writeI32(23); return; }
  if (value === 'Variant24') { w.writeI32(24); return; }
  if (value === 'Variant25') { w.writeI32(25); return; }
  if (value === 'Variant26') { w.writeI32(26); return; }
  if (value === 'Variant27') { w.writeI32(27); return; }
  if (value === 'Variant28') { w.writeI32(28); return; }
  if (value === 'Variant29') { w.writeI32(29); return; }
  if (value === 'Variant30') { w.writeI32(30); return; }
  if (value === 'Variant31') { w.writeI32(31); return; }
  if (value === 'Variant32') { w.writeI32(32); return; }
  if (value === 'Variant33') { w.writeI32(33); return; }
  if (value === 'Variant34') { w.writeI32(34); return; }
  if (value === 'Variant35') { w.writeI32(35); return; }
  if (value === 'Variant36') { w.writeI32(36); return; }
  if (value === 'Variant37') { w.writeI32(37); return; }
  if (value === 'Variant38') { w.writeI32(38); return; }
  if (value === 'Variant39') { w.writeI32(39); return; }
  if (value === 'Variant40') { w.writeI32(40); return; }
  if (value === 'Variant41') { w.writeI32(41); return; }
  if (value === 'Variant42') { w.writeI32(42); return; }
  if (value === 'Variant43') { w.writeI32(43); return; }
  if (value === 'Variant44') { w.writeI32(44); return; }
  if (value === 'Variant45') { w.writeI32(45); return; }
  if (value === 'Variant46') { w.writeI32(46); return; }
  if (value === 'Variant47') { w.writeI32(47); return; }
  if (value === 'Variant48') { w.writeI32(48); return; }
  if (value === 'Variant49') { w.writeI32(49); return; }
  if (value === 'Variant50') { w.writeI32(50); return; }
  throw new Error(`Unknown LargeEnum variant: ${value}`);
}
function _liftLargeEnum(r: UniFFIReader): LargeEnum {
  const ordinal = r.readI32();
  if (ordinal === 1) return 'Variant1';
  if (ordinal === 2) return 'Variant2';
  if (ordinal === 3) return 'Variant3';
  if (ordinal === 4) return 'Variant4';
  if (ordinal === 5) return 'Variant5';
  if (ordinal === 6) return 'Variant6';
  if (ordinal === 7) return 'Variant7';
  if (ordinal === 8) return 'Variant8';
  if (ordinal === 9) return 'Variant9';
  if (ordinal === 10) return 'Variant10';
  if (ordinal === 11) return 'Variant11';
  if (ordinal === 12) return 'Variant12';
  if (ordinal === 13) return 'Variant13';
  if (ordinal === 14) return 'Variant14';
  if (ordinal === 15) return 'Variant15';
  if (ordinal === 16) return 'Variant16';
  if (ordinal === 17) return 'Variant17';
  if (ordinal === 18) return 'Variant18';
  if (ordinal === 19) return 'Variant19';
  if (ordinal === 20) return 'Variant20';
  if (ordinal === 21) return 'Variant21';
  if (ordinal === 22) return 'Variant22';
  if (ordinal === 23) return 'Variant23';
  if (ordinal === 24) return 'Variant24';
  if (ordinal === 25) return 'Variant25';
  if (ordinal === 26) return 'Variant26';
  if (ordinal === 27) return 'Variant27';
  if (ordinal === 28) return 'Variant28';
  if (ordinal === 29) return 'Variant29';
  if (ordinal === 30) return 'Variant30';
  if (ordinal === 31) return 'Variant31';
  if (ordinal === 32) return 'Variant32';
  if (ordinal === 33) return 'Variant33';
  if (ordinal === 34) return 'Variant34';
  if (ordinal === 35) return 'Variant35';
  if (ordinal === 36) return 'Variant36';
  if (ordinal === 37) return 'Variant37';
  if (ordinal === 38) return 'Variant38';
  if (ordinal === 39) return 'Variant39';
  if (ordinal === 40) return 'Variant40';
  if (ordinal === 41) return 'Variant41';
  if (ordinal === 42) return 'Variant42';
  if (ordinal === 43) return 'Variant43';
  if (ordinal === 44) return 'Variant44';
  if (ordinal === 45) return 'Variant45';
  if (ordinal === 46) return 'Variant46';
  if (ordinal === 47) return 'Variant47';
  if (ordinal === 48) return 'Variant48';
  if (ordinal === 49) return 'Variant49';
  if (ordinal === 50) return 'Variant50';
  throw new Error(`Unknown LargeEnum ordinal: ${ordinal}`);
}

function _liftErrorLargeError(rb: any): LargeError {
  return _rt.liftFromBuffer(rb, (r) => {
    const ordinal = r.readI32();
    if (ordinal === 1) return new LargeError('Case1');
    if (ordinal === 2) return new LargeError('Case2');
    if (ordinal === 3) return new LargeError('Case3');
    if (ordinal === 4) return new LargeError('Case4');
    if (ordinal === 5) return new LargeError('Case5');
    if (ordinal === 6) return new LargeError('Case6');
    if (ordinal === 7) return new LargeError('Case7');
    if (ordinal === 8) return new LargeError('Case8');
    if (ordinal === 9) return new LargeError('Case9');
    if (ordinal === 10) return new LargeError('Case10');
    if (ordinal === 11) return new LargeError('Case11');
    if (ordinal === 12) return new LargeError('Case12');
    if (ordinal === 13) return new LargeError('Case13');
    if (ordinal === 14) return new LargeError('Case14');
    if (ordinal === 15) return new LargeError('Case15');
    if (ordinal === 16) return new LargeError('Case16');
    if (ordinal === 17) return new LargeError('Case17');
    if (ordinal === 18) return new LargeError('Case18');
    if (ordinal === 19) return new LargeError('Case19');
    if (ordinal === 20) return new LargeError('Case20');
    if (ordinal === 21) return new LargeError('Case21');
    if (ordinal === 22) return new LargeError('Case22');
    if (ordinal === 23) return new LargeError('Case23');
    if (ordinal === 24) return new LargeError('Case24');
    if (ordinal === 25) return new LargeError('Case25');
    if (ordinal === 26) return new LargeError('Case26');
    if (ordinal === 27) return new LargeError('Case27');
    if (ordinal === 28) return new LargeError('Case28');
    if (ordinal === 29) return new LargeError('Case29');
    if (ordinal === 30) return new LargeError('Case30');
    throw new Error(`Unknown LargeError ordinal: ${ordinal}`);
  });
}

export namespace TypeLimitsDemo {
  /** @throws {LargeError} */
  export function maybeThrow(idx: number): void {
    const _argPtr = _rt.scratchAlloc(1 * 8);
    _rt.writeU32Element(_argPtr, idx);
    const _retPtr = _rt.scratchAlloc(4 * 8);
    try {
      _rt.call('uniffi_ffibuffer_crate_name_fn_func_maybe_throw', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr, (rb) => _liftErrorLargeError(rb));
    } finally {
      _rt.scratchReset();
    }
  }
  export function takeBytes(v: Uint8Array): Uint8Array {
    const _rb_v = _rt.lowerIntoBuffer((w) => { w.writeBytes(v); });
    const _argPtr = _rt.scratchAlloc(3 * 8);
    _rt.writeRustBufferElements(_argPtr, _rb_v);
    const _retPtr = _rt.scratchAlloc(7 * 8);
    try {
      _rt.call('uniffi_ffibuffer_crate_name_fn_func_take_bytes', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 24);
      const _result = _rt.liftFromBuffer(_rt.readRustBufferElements(_retPtr), (r) => { return r.readBytes(); });
      return _result;
    } finally {
      _rt.scratchReset();
    }
  }
  export function takeEnum(v: LargeEnum): LargeEnum {
    const _rb_v = _rt.lowerIntoBuffer((w) => { _lowerLargeEnum(w, v); });
    const _argPtr = _rt.scratchAlloc(3 * 8);
    _rt.writeRustBufferElements(_argPtr, _rb_v);
    const _retPtr = _rt.scratchAlloc(7 * 8);
    try {
      _rt.call('uniffi_ffibuffer_crate_name_fn_func_take_enum', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 24);
      const _result = _rt.liftFromBuffer(_rt.readRustBufferElements(_retPtr), (r) => { return _liftLargeEnum(r); });
      return _result;
    } finally {
      _rt.scratchReset();
    }
  }
  export function takeF32(v: number): number {
    const _argPtr = _rt.scratchAlloc(1 * 8);
    _rt.writeF32Element(_argPtr, v);
    const _retPtr = _rt.scratchAlloc(5 * 8);
    try {
      _rt.call('uniffi_ffibuffer_crate_name_fn_func_take_f32', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 8);
      const _result = _rt.readF32Element(_retPtr);
      return _result;
    } finally {
      _rt.scratchReset();
    }
  }
  export function takeF64(v: number): number {
    const _argPtr = _rt.scratchAlloc(1 * 8);
    _rt.writeF64Element(_argPtr, v);
    const _retPtr = _rt.scratchAlloc(5 * 8);
    try {
      _rt.call('uniffi_ffibuffer_crate_name_fn_func_take_f64', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 8);
      const _result = _rt.readF64Element(_retPtr);
      return _result;
    } finally {
      _rt.scratchReset();
    }
  }
  export function takeI16(v: number): number {
    const _argPtr = _rt.scratchAlloc(1 * 8);
    _rt.writeI16Element(_argPtr, v);
    const _retPtr = _rt.scratchAlloc(5 * 8);
    try {
      _rt.call('uniffi_ffibuffer_crate_name_fn_func_take_i16', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 8);
      const _result = _rt.readI16Element(_retPtr);
      return _result;
    } finally {
      _rt.scratchReset();
    }
  }
  export function takeI32(v: number): number {
    const _argPtr = _rt.scratchAlloc(1 * 8);
    _rt.writeI32Element(_argPtr, v);
    const _retPtr = _rt.scratchAlloc(5 * 8);
    try {
      _rt.call('uniffi_ffibuffer_crate_name_fn_func_take_i32', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 8);
      const _result = _rt.readI32Element(_retPtr);
      return _result;
    } finally {
      _rt.scratchReset();
    }
  }
  export function takeI64(v: bigint): bigint {
    const _argPtr = _rt.scratchAlloc(1 * 8);
    _rt.writeI64Element(_argPtr, BigInt(v));
    const _retPtr = _rt.scratchAlloc(5 * 8);
    try {
      _rt.call('uniffi_ffibuffer_crate_name_fn_func_take_i64', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 8);
      const _result = _rt.readI64Element(_retPtr);
      return _result;
    } finally {
      _rt.scratchReset();
    }
  }
  export function takeI8(v: number): number {
    const _argPtr = _rt.scratchAlloc(1 * 8);
    _rt.writeI8Element(_argPtr, v);
    const _retPtr = _rt.scratchAlloc(5 * 8);
    try {
      _rt.call('uniffi_ffibuffer_crate_name_fn_func_take_i8', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 8);
      const _result = _rt.readI8Element(_retPtr);
      return _result;
    } finally {
      _rt.scratchReset();
    }
  }
  export function takeString(v: string): string {
    const _rb_v = _rt.lowerString(v);
    const _argPtr = _rt.scratchAlloc(3 * 8);
    _rt.writeRustBufferElements(_argPtr, _rb_v);
    const _retPtr = _rt.scratchAlloc(7 * 8);
    try {
      _rt.call('uniffi_ffibuffer_crate_name_fn_func_take_string', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 24);
      const _result = _rt.liftString(_rt.readRustBufferElements(_retPtr));
      return _result;
    } finally {
      _rt.scratchReset();
    }
  }
  export function takeU16(v: number): number {
    const _argPtr = _rt.scratchAlloc(1 * 8);
    _rt.writeU16Element(_argPtr, v);
    const _retPtr = _rt.scratchAlloc(5 * 8);
    try {
      _rt.call('uniffi_ffibuffer_crate_name_fn_func_take_u16', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 8);
      const _result = _rt.readU16Element(_retPtr);
      return _result;
    } finally {
      _rt.scratchReset();
    }
  }
  export function takeU32(v: number): number {
    const _argPtr = _rt.scratchAlloc(1 * 8);
    _rt.writeU32Element(_argPtr, v);
    const _retPtr = _rt.scratchAlloc(5 * 8);
    try {
      _rt.call('uniffi_ffibuffer_crate_name_fn_func_take_u32', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 8);
      const _result = _rt.readU32Element(_retPtr);
      return _result;
    } finally {
      _rt.scratchReset();
    }
  }
  export function takeU64(v: bigint): bigint {
    const _argPtr = _rt.scratchAlloc(1 * 8);
    _rt.writeU64Element(_argPtr, BigInt(v));
    const _retPtr = _rt.scratchAlloc(5 * 8);
    try {
      _rt.call('uniffi_ffibuffer_crate_name_fn_func_take_u64', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 8);
      const _result = _rt.readU64Element(_retPtr);
      return _result;
    } finally {
      _rt.scratchReset();
    }
  }
  export function takeU8(v: number): number {
    const _argPtr = _rt.scratchAlloc(1 * 8);
    _rt.writeU8Element(_argPtr, v);
    const _retPtr = _rt.scratchAlloc(5 * 8);
    try {
      _rt.call('uniffi_ffibuffer_crate_name_fn_func_take_u8', _argPtr, _retPtr);
      _rt.checkCallStatus(_retPtr + 8);
      const _result = _rt.readU8Element(_retPtr);
      return _result;
    } finally {
      _rt.scratchReset();
    }
  }
}
