// Generated by uniffi-bindgen-js. DO NOT EDIT.
import { UniffiRuntime, UniFFIWriter, UniFFIReader } from './uniffi_runtime.js';

const _rt = await UniffiRuntime.load(new URL('./rename_exclude.wasm', import.meta.url), 'rename_exclude');

// --- Serialization helpers ---

export namespace RenameExclude {
  export function greet(name: string): string {
    const _rb_name = _rt.lowerString(name);
    const _argPtr = _rt.scratchAlloc(3 * 8);
    _rt.writeRustBufferElements(_argPtr, _rb_name);
    const _retPtr = _rt.scratchAlloc(7 * 8);
    _rt.call('uniffi_ffibuffer_rename_exclude_fn_func_hello', _argPtr, _retPtr);
    _rt.checkCallStatus(_retPtr + 24);
    const _result = _rt.liftString(_rt.readRustBufferElements(_retPtr));
    _rt.scratchReset();
    return _result;
  }
  export function version(): string {
    const _argPtr = 0;
    const _retPtr = _rt.scratchAlloc(7 * 8);
    _rt.call('uniffi_ffibuffer_rename_exclude_fn_func_version', _argPtr, _retPtr);
    _rt.checkCallStatus(_retPtr + 24);
    const _result = _rt.liftString(_rt.readRustBufferElements(_retPtr));
    _rt.scratchReset();
    return _result;
  }
}
