// Generated by uniffi-bindgen-js. DO NOT EDIT.
import __init, * as __bg from './rename_exclude_bg.js';
export { __init as init };

export namespace RenameExclude {
  export function greet(name: string): string { return __bg.hello(name); }
  export function version(): string { return __bg.version(); }
}
