// Generated by uniffi-bindgen-js. DO NOT EDIT.
import __init, * as __bg from './rename_exclude_bg.js';

function _uniffiEnsureApiIntegrity(): void {
  const bindingsContractVersion = 30;
  const scaffoldingContractVersion: number = (__bg as any).ffi_crate_name_uniffi_contract_version();
  if (bindingsContractVersion !== scaffoldingContractVersion) {
    throw new Error(`UniFFI contract version mismatch: expected ${bindingsContractVersion}, got ${scaffoldingContractVersion}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_farewell: number = (__bg as any).uniffi_crate_name_checksum_func_farewell();
  if (_checksum_uniffi_crate_name_checksum_func_farewell !== 15048) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_farewell\`: expected 15048, got ${_checksum_uniffi_crate_name_checksum_func_farewell}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_hello: number = (__bg as any).uniffi_crate_name_checksum_func_hello();
  if (_checksum_uniffi_crate_name_checksum_func_hello !== 14780) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_hello\`: expected 14780, got ${_checksum_uniffi_crate_name_checksum_func_hello}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_version: number = (__bg as any).uniffi_crate_name_checksum_func_version();
  if (_checksum_uniffi_crate_name_checksum_func_version !== 62316) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_version\`: expected 62316, got ${_checksum_uniffi_crate_name_checksum_func_version}`);
  }
}
export async function init(...args: Parameters<typeof __init>): Promise<ReturnType<typeof __init>> {
  const result = await __init(...args);
  _uniffiEnsureApiIntegrity();
  return result;
}

export namespace RenameExclude {
  export function greet(name: string): string { return __bg.hello(name); }
  export function version(): string { return __bg.version(); }
}
