// Generated by uniffi-bindgen-js. DO NOT EDIT.
import __init, * as __bg from './docstrings_bg.js';
export { __init as init };

/** A 2D point value. */
export interface Point {
  /** Horizontal position. */
  x: number;
  /** Vertical position. */
  y: number;
}

/**
 * The mood of the user.
 * - `Happy`: Feeling good.
 * - `Sad`: Feeling bad.
 */
export type Mood = 'Happy' | 'Sad';

/** A text processing callback. */
export interface Processor {
  /** Processes the input text and returns the result. */
  process(input: string): string;
}

/** A counter that can be incremented and decremented. */
export class Counter {
  private readonly _inner: __bg.Counter;
  private _freed = false;
  private _assertLive(): void {
    if (this._freed) throw new Error('Counter object has been freed');
  }
  private constructor(inner: __bg.Counter) {
    this._inner = inner;
  }
  /** @internal */
  static _fromInner(inner: __bg.Counter): Counter { return new Counter(inner); }
  /** Creates a new counter starting at the given value. */
  static new(start: bigint): Counter { return Counter._fromInner(new __bg.Counter(start)); }
  /** Returns the current value. */
  get(): bigint {
    this._assertLive();
    return this._inner.get();
  }
  /** Increments the counter by one. */
  increment(): void {
    this._assertLive();
    this._inner.increment();
  }
  /** Releases the underlying WASM resource. Safe to call more than once. */
  free(): void {
    if (this._freed) return;
    this._freed = true;
    this._inner.free();
  }
}

/** The docstrings demo namespace. */
export namespace Docstrings {
  /**
   * Returns a greeting for the given name.
   * Supports Unicode names.
   */
  export function greet(name: string): string { return __bg.greet(name); }
}
