// Generated by uniffi-bindgen-js. DO NOT EDIT.
import __init, * as __bg from './docstrings_bg.js';

function _uniffiEnsureApiIntegrity(): void {
  const bindingsContractVersion = 30;
  const scaffoldingContractVersion: number = (__bg as any).ffi_crate_name_uniffi_contract_version();
  if (bindingsContractVersion !== scaffoldingContractVersion) {
    throw new Error(`UniFFI contract version mismatch: expected ${bindingsContractVersion}, got ${scaffoldingContractVersion}`);
  }
  const _checksum_uniffi_crate_name_checksum_func_greet: number = (__bg as any).uniffi_crate_name_checksum_func_greet();
  if (_checksum_uniffi_crate_name_checksum_func_greet !== 51217) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_func_greet\`: expected 51217, got ${_checksum_uniffi_crate_name_checksum_func_greet}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_counter_get: number = (__bg as any).uniffi_crate_name_checksum_method_counter_get();
  if (_checksum_uniffi_crate_name_checksum_method_counter_get !== 31216) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_counter_get\`: expected 31216, got ${_checksum_uniffi_crate_name_checksum_method_counter_get}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_counter_increment: number = (__bg as any).uniffi_crate_name_checksum_method_counter_increment();
  if (_checksum_uniffi_crate_name_checksum_method_counter_increment !== 23326) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_counter_increment\`: expected 23326, got ${_checksum_uniffi_crate_name_checksum_method_counter_increment}`);
  }
  const _checksum_uniffi_crate_name_checksum_constructor_counter_new: number = (__bg as any).uniffi_crate_name_checksum_constructor_counter_new();
  if (_checksum_uniffi_crate_name_checksum_constructor_counter_new !== 29727) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_constructor_counter_new\`: expected 29727, got ${_checksum_uniffi_crate_name_checksum_constructor_counter_new}`);
  }
  const _checksum_uniffi_crate_name_checksum_method_processor_process: number = (__bg as any).uniffi_crate_name_checksum_method_processor_process();
  if (_checksum_uniffi_crate_name_checksum_method_processor_process !== 33196) {
    throw new Error(`UniFFI API checksum mismatch for \`uniffi_crate_name_checksum_method_processor_process\`: expected 33196, got ${_checksum_uniffi_crate_name_checksum_method_processor_process}`);
  }
}
export async function init(...args: Parameters<typeof __init>): Promise<ReturnType<typeof __init>> {
  const result = await __init(...args);
  _uniffiEnsureApiIntegrity();
  return result;
}

/** A 2D point value. */
export interface Point {
  /** Horizontal position. */
  x: number;
  /** Vertical position. */
  y: number;
}

/**
 * The mood of the user.
 * - `Happy`: Feeling good.
 * - `Sad`: Feeling bad.
 */
export type Mood = 'Happy' | 'Sad';

/** A text processing callback. */
export interface Processor {
  /** Processes the input text and returns the result. */
  process(input: string): string;
}

/** A counter that can be incremented and decremented. */
export class Counter {
  private readonly _inner: __bg.Counter;
  private _freed = false;
  private _assertLive(): void {
    if (this._freed) throw new Error('Counter object has been freed');
  }
  private constructor(inner: __bg.Counter) {
    this._inner = inner;
  }
  /** @internal */
  static _fromInner(inner: __bg.Counter): Counter { return new Counter(inner); }
  /** Creates a new counter starting at the given value. */
  static new(start: bigint): Counter { return Counter._fromInner(new __bg.Counter(start)); }
  /** Returns the current value. */
  get(): bigint {
    this._assertLive();
    return this._inner.get();
  }
  /** Increments the counter by one. */
  increment(): void {
    this._assertLive();
    this._inner.increment();
  }
  /** Releases the underlying WASM resource. Safe to call more than once. */
  free(): void {
    if (this._freed) return;
    this._freed = true;
    this._inner.free();
  }
  [Symbol.dispose](): void { this.free(); }
}

/** The docstrings demo namespace. */
export namespace Docstrings {
  /**
   * Returns a greeting for the given name.
   * Supports Unicode names.
   */
  export function greet(name: string): string { return __bg.greet(name); }
}
