use std::fs;
use std::path::Path;

use anyhow::{Context, Result};
use uniffi_bindgen::interface::{AsType, ComponentInterface, Type};

use crate::cli::GenerateArgs;

pub mod config;

pub fn generate_bindings(args: &GenerateArgs) -> Result<()> {
    let cfg = config::load(args)?;
    let metadata = parse_udl_metadata(&args.source)?;
    // For UDL sources the namespace comes from the parsed ComponentInterface;
    // for other sources fall back to the file stem.
    let namespace = if metadata.namespace.is_empty() {
        namespace_from_source(&args.source)?
    } else {
        metadata.namespace.clone()
    };

    let module_name = cfg
        .module_name
        .clone()
        .unwrap_or_else(|| pascal_case(&namespace));

    let out_file = args.out_dir.join(format!("{namespace}.ts"));
    fs::create_dir_all(&args.out_dir)
        .with_context(|| format!("failed to create output dir: {}", args.out_dir.display()))?;

    let content = render_ts(&module_name, &namespace, &metadata, &cfg);
    fs::write(&out_file, &content)
        .with_context(|| format!("failed to write: {}", out_file.display()))?;

    Ok(())
}

// ---------------------------------------------------------------------------
// Internal data types extracted from UDL
// ---------------------------------------------------------------------------

#[derive(Debug)]
struct UdlFunction {
    name: String,
    args: Vec<UdlArg>,
    return_type: Option<Type>,
    #[allow(dead_code)] // used in Phase 2+ (error handling)
    throws_type: Option<Type>,
    #[allow(dead_code)] // used in Phase 5+ (async)
    is_async: bool,
}

#[derive(Debug)]
struct UdlArg {
    name: String,
    type_: Type,
}

#[derive(Debug, Default)]
struct UdlMetadata {
    namespace: String,
    functions: Vec<UdlFunction>,
}

// ---------------------------------------------------------------------------
// UDL parsing via uniffi_bindgen ComponentInterface
// ---------------------------------------------------------------------------

fn parse_udl_metadata(source: &Path) -> Result<UdlMetadata> {
    if source.extension().and_then(|e| e.to_str()) != Some("udl") {
        return Ok(UdlMetadata::default());
    }

    let udl = fs::read_to_string(source)
        .with_context(|| format!("failed to read UDL: {}", source.display()))?;
    let ci = ComponentInterface::from_webidl(&udl, "crate_name")
        .with_context(|| format!("failed to parse UDL: {}", source.display()))?;

    let functions = ci
        .function_definitions()
        .iter()
        .map(|f| UdlFunction {
            name: f.name().to_string(),
            args: f
                .arguments()
                .into_iter()
                .map(|a| UdlArg {
                    name: a.name().to_string(),
                    type_: a.as_type(),
                })
                .collect(),
            return_type: f.return_type().cloned(),
            throws_type: f.throws_type().cloned(),
            is_async: f.is_async(),
        })
        .collect();

    Ok(UdlMetadata {
        namespace: ci.namespace().to_string(),
        functions,
    })
}

// ---------------------------------------------------------------------------
// Namespace extraction fallback (non-UDL sources only)
// ---------------------------------------------------------------------------

// For UDL sources, namespace_from_source is only called when the parsed
// UdlMetadata has an empty namespace (should not happen in practice).
fn namespace_from_source(source: &Path) -> Result<String> {
    source
        .file_stem()
        .and_then(|s| s.to_str())
        .map(ToOwned::to_owned)
        .ok_or_else(|| anyhow::anyhow!("source path must have a valid UTF-8 file stem"))
}

// ---------------------------------------------------------------------------
// TypeScript code generation (WASM/wasm-pack wrapper)
// ---------------------------------------------------------------------------

fn render_ts(
    module_name: &str,
    namespace: &str,
    metadata: &UdlMetadata,
    cfg: &config::JsBindingsConfig,
) -> String {
    let visible_fns: Vec<&UdlFunction> = metadata
        .functions
        .iter()
        .filter(|f| !cfg.exclude.contains(&f.name))
        .collect();

    let mut out = String::new();

    out.push_str("// Generated by uniffi-bindgen-js. DO NOT EDIT.\n");
    out.push_str(&format!(
        "import __init, * as __bg from './{namespace}_bg.js';\n"
    ));
    out.push_str("export { __init as init };\n");

    out.push_str(&format!("\nexport namespace {module_name} {{\n"));

    for f in &visible_fns {
        let exported = cfg
            .rename
            .get(&f.name)
            .cloned()
            .unwrap_or_else(|| camel_case(&f.name));

        let ts_params: Vec<String> = f
            .args
            .iter()
            .map(|a| format!("{}: {}", camel_case(&a.name), ts_type_str(&a.type_)))
            .collect();

        let ts_ret = f
            .return_type
            .as_ref()
            .map(ts_type_str)
            .unwrap_or_else(|| "void".to_string());

        let call_args: Vec<String> = f.args.iter().map(|a| camel_case(&a.name)).collect();

        out.push_str(&format!(
            "  export function {}({}): {} {{\n",
            exported,
            ts_params.join(", "),
            ts_ret
        ));

        if f.return_type.is_some() {
            out.push_str(&format!(
                "    return __bg.{}({});\n",
                f.name,
                call_args.join(", ")
            ));
        } else {
            out.push_str(&format!("    __bg.{}({});\n", f.name, call_args.join(", ")));
        }

        out.push_str("  }\n");
    }

    out.push_str("}\n");

    out
}

// ---------------------------------------------------------------------------
// Type helpers
// ---------------------------------------------------------------------------

fn ts_type_str(t: &Type) -> String {
    match t {
        Type::String => "string".to_string(),
        Type::Boolean => "boolean".to_string(),
        Type::Int8 | Type::Int16 | Type::Int32 => "number".to_string(),
        Type::UInt8 | Type::UInt16 | Type::UInt32 => "number".to_string(),
        Type::Int64 | Type::UInt64 => "bigint".to_string(),
        Type::Float32 | Type::Float64 => "number".to_string(),
        Type::Bytes => "Uint8Array".to_string(),
        Type::Optional { inner_type } => format!("{} | null", ts_type_str(inner_type)),
        Type::Sequence { inner_type } => format!("{}[]", ts_type_str(inner_type)),
        Type::Map {
            key_type,
            value_type,
        } => {
            format!(
                "Map<{}, {}>",
                ts_type_str(key_type),
                ts_type_str(value_type)
            )
        }
        Type::Enum { name, .. }
        | Type::Record { name, .. }
        | Type::Object { name, .. }
        | Type::CallbackInterface { name, .. } => pascal_case(name),
        _ => "unknown".to_string(),
    }
}

// ---------------------------------------------------------------------------
// Identifier helpers
// ---------------------------------------------------------------------------

fn camel_case(input: &str) -> String {
    let mut out = String::new();
    let mut capitalize_next = false;
    for ch in input.chars() {
        if ch == '_' || ch == '-' {
            capitalize_next = true;
        } else if capitalize_next {
            out.push(ch.to_ascii_uppercase());
            capitalize_next = false;
        } else {
            out.push(ch);
        }
    }
    out
}

fn pascal_case(input: &str) -> String {
    let mut out = String::new();
    for part in input.split(['_', '-']) {
        if part.is_empty() {
            continue;
        }
        let mut chars = part.chars();
        if let Some(first) = chars.next() {
            out.push(first.to_ascii_uppercase());
            out.push_str(chars.as_str());
        }
    }
    if out.is_empty() {
        "UniffiBindings".to_string()
    } else {
        out
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn camel_case_handles_underscores() {
        assert_eq!(camel_case("ping"), "ping");
        assert_eq!(camel_case("broken_greet"), "brokenGreet");
        assert_eq!(camel_case("async_greet"), "asyncGreet");
    }

    #[test]
    fn pascal_case_handles_common_cases() {
        assert_eq!(pascal_case("simple_bindings"), "SimpleBindings");
        assert_eq!(pascal_case("simple-bindings"), "SimpleBindings");
    }
}
