use std::collections::HashSet;
use std::fs;

use anyhow::{Context, Result};

use crate::cli::GenerateArgs;

pub mod config;

mod external_types;
mod naming;
mod parsing;
mod render_helpers;
mod render_objects;
mod render_types;
mod type_lifting;
mod types;

use external_types::collect_external_imports;
use naming::pascal_case;
use parsing::{namespace_from_source, parse_udl_metadata};
use render_helpers::{render_jsdoc, ts_type_str, type_name};
use render_objects::{render_function, render_object_class};
use render_types::{
    render_callback_interface, render_enum_type, render_error_class, render_lift_fn,
    render_object_error_lift_fn, render_record_interface,
};
use types::*;

pub fn generate_bindings(args: &GenerateArgs) -> Result<()> {
    let cfg = config::load(args)?;
    let metadata = parse_udl_metadata(&args.source, args.crate_name.as_deref(), args.library)?;
    let namespace = if metadata.namespace.is_empty() {
        namespace_from_source(&args.source)?
    } else {
        metadata.namespace.clone()
    };

    let module_name = cfg
        .module_name
        .clone()
        .unwrap_or_else(|| pascal_case(&namespace));

    let out_file = args.out_dir.join(format!("{namespace}.ts"));
    fs::create_dir_all(&args.out_dir)
        .with_context(|| format!("failed to create output dir: {}", args.out_dir.display()))?;

    let content = render_ts(&module_name, &namespace, &metadata, &cfg)?;
    fs::write(&out_file, &content)
        .with_context(|| format!("failed to write: {}", out_file.display()))?;

    Ok(())
}

// ---------------------------------------------------------------------------
// TypeScript code generation orchestrator
// ---------------------------------------------------------------------------

fn render_ts(
    module_name: &str,
    namespace: &str,
    metadata: &UdlMetadata,
    cfg: &config::JsBindingsConfig,
) -> Result<String> {
    let mut out = String::new();

    // Header
    out.push_str("// Generated by uniffi-bindgen-js. DO NOT EDIT.\n");
    out.push_str(&format!(
        "import __init, * as __bg from './{namespace}_bg.js';\n"
    ));

    let has_integrity_check = metadata.uniffi_contract_version.is_some()
        && metadata.ffi_uniffi_contract_version_symbol.is_some();

    if has_integrity_check {
        out.push('\n');
        render_integrity_check(&mut out, metadata);
        out.push_str(
            "export async function init(...args: Parameters<typeof __init>): Promise<ReturnType<typeof __init>> {\n",
        );
        out.push_str("  const result = await __init(...args);\n");
        out.push_str("  _uniffiEnsureApiIntegrity();\n");
        out.push_str("  return result;\n");
        out.push_str("}\n");
    } else {
        out.push_str("export { __init as init };\n");
    }

    // External type imports — one import statement per external package, types sorted for determinism.
    let external_imports =
        collect_external_imports(metadata, &cfg.external_packages, &metadata.local_crate)?;
    for (import_path, type_names) in &external_imports {
        let names: Vec<&str> = type_names.iter().map(String::as_str).collect();
        out.push_str(&format!(
            "import {{ {} }} from '{import_path}';\n",
            names.join(", ")
        ));
    }

    // Custom type aliases (top-level, before everything else)
    for ct in &metadata.custom_types {
        if !cfg.exclude.contains(&ct.name) {
            let exported = cfg
                .rename
                .get(&ct.name)
                .cloned()
                .unwrap_or_else(|| ct.name.clone());
            out.push('\n');
            out.push_str(&format!(
                "export type {} = {};\n",
                exported,
                ts_type_str(&ct.builtin)
            ));
        }
    }

    // Error classes (top-level, before namespace)
    for e in &metadata.errors {
        if !cfg.exclude.contains(&e.name) {
            out.push('\n');
            out.push_str(&render_error_class(e, cfg, &metadata.local_crate));
        }
    }

    // Record interfaces (top-level)
    for r in &metadata.records {
        if !cfg.exclude.contains(&r.name) {
            out.push('\n');
            out.push_str(&render_record_interface(r));
        }
    }

    // Enum types (top-level)
    for e in &metadata.enums {
        if !cfg.exclude.contains(&e.name) {
            out.push('\n');
            out.push_str(&render_enum_type(e, cfg, &metadata.local_crate));
        }
    }

    // Callback interfaces (structural TypeScript interfaces)
    for cb in &metadata.callback_interfaces {
        if !cfg.exclude.contains(&cb.name) {
            out.push('\n');
            out.push_str(&render_callback_interface(cb, cfg));
        }
    }

    // Object re-exports (top-level)
    let visible_objects: Vec<&UdlObject> = metadata
        .objects
        .iter()
        .filter(|o| !cfg.exclude.contains(&o.name))
        .collect();
    if !visible_objects.is_empty() {
        out.push('\n');
        for o in &visible_objects {
            out.push_str(&render_object_class(o, cfg, &metadata.local_crate));
        }
    }

    // Error lift helpers (private, before namespace)
    let all_throws: HashSet<String> = {
        let mut names: HashSet<String> = HashSet::new();
        for f in &metadata.functions {
            if let Some(t) = &f.throws_type {
                names.insert(type_name(t));
            }
        }
        for o in &metadata.objects {
            for c in &o.constructors {
                if let Some(t) = &c.throws_type {
                    names.insert(type_name(t));
                }
            }
            for m in &o.methods {
                if let Some(t) = &m.throws_type {
                    names.insert(type_name(t));
                }
            }
        }
        for e in &metadata.enums {
            for c in &e.constructors {
                if let Some(t) = &c.throws_type {
                    names.insert(type_name(t));
                }
            }
            for m in &e.methods {
                if let Some(t) = &m.throws_type {
                    names.insert(type_name(t));
                }
            }
        }
        for e in &metadata.errors {
            for c in &e.constructors {
                if let Some(t) = &c.throws_type {
                    names.insert(type_name(t));
                }
            }
            for m in &e.methods {
                if let Some(t) = &m.throws_type {
                    names.insert(type_name(t));
                }
            }
        }
        names
    };
    // Collect unique error names that need lift helpers, looking them up in errors
    // and error objects.
    let mut rendered_lifts: Vec<String> = Vec::new();
    for error in &metadata.errors {
        if all_throws.contains(&error.name) {
            let lift = render_lift_fn(error);
            if !lift.is_empty() {
                rendered_lifts.push(lift);
            }
        }
    }
    for obj in &metadata.objects {
        if obj.is_error && all_throws.contains(&obj.name) {
            rendered_lifts.push(render_object_error_lift_fn(&obj.name));
        }
    }
    if !rendered_lifts.is_empty() {
        out.push('\n');
        for lift in rendered_lifts {
            out.push_str(&lift);
        }
    }

    // Namespace with top-level functions — omit entirely if there are none.
    let visible_fns: Vec<&UdlFunction> = metadata
        .functions
        .iter()
        .filter(|f| !cfg.exclude.contains(&f.name))
        .collect();

    if !visible_fns.is_empty() {
        out.push('\n');
        out.push_str(&render_jsdoc(metadata.namespace_docstring.as_deref(), ""));
        out.push_str(&format!("export namespace {module_name} {{\n"));
        for f in &visible_fns {
            out.push_str(&render_function(f, cfg, &metadata.local_crate));
        }
        out.push_str("}\n");
    }

    Ok(out)
}

// ---------------------------------------------------------------------------
// API integrity verification
// ---------------------------------------------------------------------------

/// Render a private `_uniffiEnsureApiIntegrity()` function that validates the
/// contract version and API checksums against the loaded WASM module.
fn render_integrity_check(out: &mut String, metadata: &UdlMetadata) {
    let version = metadata.uniffi_contract_version.unwrap_or_default();
    let symbol = metadata
        .ffi_uniffi_contract_version_symbol
        .as_deref()
        .unwrap_or_default();

    out.push_str("function _uniffiEnsureApiIntegrity(): void {\n");
    out.push_str(&format!("  const bindingsContractVersion = {version};\n"));
    out.push_str(&format!(
        "  const scaffoldingContractVersion: number = (__bg as any).{symbol}();\n"
    ));
    out.push_str("  if (bindingsContractVersion !== scaffoldingContractVersion) {\n");
    out.push_str(
        "    throw new Error(`UniFFI contract version mismatch: expected ${bindingsContractVersion}, got ${scaffoldingContractVersion}`);\n",
    );
    out.push_str("  }\n");

    for checksum in &metadata.api_checksums {
        out.push_str(&format!(
            "  const {}: number = (__bg as any).{}();\n",
            checksum_var_name(&checksum.symbol),
            checksum.symbol
        ));
        out.push_str(&format!(
            "  if ({} !== {}) {{\n",
            checksum_var_name(&checksum.symbol),
            checksum.expected
        ));
        out.push_str(&format!(
            "    throw new Error(`UniFFI API checksum mismatch for \\`{}\\`: expected {}, got ${{{}}}`);\n",
            checksum.symbol,
            checksum.expected,
            checksum_var_name(&checksum.symbol)
        ));
        out.push_str("  }\n");
    }

    out.push_str("}\n");
}

/// Convert an FFI checksum symbol name to a valid JS variable name.
fn checksum_var_name(symbol: &str) -> String {
    format!(
        "_checksum_{}",
        symbol.replace(|c: char| !c.is_ascii_alphanumeric(), "_")
    )
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use std::collections::HashMap;

    use uniffi_bindgen::interface::{DefaultValue, Literal, Type};

    use super::config;
    use super::external_types::collect_external_imports;
    use super::naming::*;
    use super::render_helpers::*;
    use super::render_types::*;
    use super::type_lifting::*;
    use super::types::LOCAL_CRATE_SENTINEL;
    use super::types::*;

    #[test]
    fn camel_case_handles_underscores() {
        assert_eq!(camel_case("ping"), "ping");
        assert_eq!(camel_case("broken_greet"), "brokenGreet");
        assert_eq!(camel_case("async_greet"), "asyncGreet");
    }

    #[test]
    fn safe_js_identifier_escapes_reserved_words() {
        assert_eq!(safe_js_identifier("class"), "class_");
        assert_eq!(safe_js_identifier("return"), "return_");
        assert_eq!(safe_js_identifier("delete"), "delete_");
        assert_eq!(safe_js_identifier("void"), "void_");
        assert_eq!(safe_js_identifier("yield"), "yield_");
        assert_eq!(safe_js_identifier("async"), "async_");
        assert_eq!(safe_js_identifier("await"), "await_");
        assert_eq!(safe_js_identifier("typeof"), "typeof_");
        assert_eq!(safe_js_identifier("catch"), "catch_");
        assert_eq!(safe_js_identifier("finally"), "finally_");
        assert_eq!(safe_js_identifier("static"), "static_");
        // Non-reserved words should pass through unchanged
        assert_eq!(safe_js_identifier("name"), "name");
        assert_eq!(safe_js_identifier("count"), "count");
        assert_eq!(safe_js_identifier("value"), "value");
    }

    #[test]
    fn pascal_case_handles_common_cases() {
        assert_eq!(pascal_case("simple_bindings"), "SimpleBindings");
        assert_eq!(pascal_case("simple-bindings"), "SimpleBindings");
    }

    #[test]
    fn snake_case_handles_pascal() {
        assert_eq!(snake_case("Counter"), "counter");
        assert_eq!(snake_case("MyCounter"), "my_counter");
        assert_eq!(snake_case("MyHTTPClient"), "my_http_client");
        assert_eq!(snake_case("URLError"), "url_error");
        assert_eq!(snake_case("ABC"), "abc");
    }

    #[test]
    fn render_jsdoc_none_returns_empty() {
        assert_eq!(render_jsdoc(None, ""), "");
    }

    #[test]
    fn render_jsdoc_blank_returns_empty() {
        assert_eq!(render_jsdoc(Some("   "), ""), "");
        assert_eq!(render_jsdoc(Some(""), ""), "");
    }

    #[test]
    fn render_jsdoc_single_line() {
        assert_eq!(render_jsdoc(Some("Hello."), ""), "/** Hello. */\n");
    }

    #[test]
    fn render_jsdoc_single_line_with_indent() {
        assert_eq!(render_jsdoc(Some("Hello."), "  "), "  /** Hello. */\n");
    }

    #[test]
    fn render_jsdoc_multi_line() {
        let doc = "First line.\nSecond line.";
        let expected = "/**\n * First line.\n * Second line.\n */\n";
        assert_eq!(render_jsdoc(Some(doc), ""), expected);
    }

    #[test]
    fn render_jsdoc_multi_line_with_blank() {
        let doc = "First.\n\nSecond.";
        let expected = "/**\n * First.\n *\n * Second.\n */\n";
        assert_eq!(render_jsdoc(Some(doc), ""), expected);
    }

    #[test]
    fn render_jsdoc_escapes_comment_close() {
        assert_eq!(
            render_jsdoc(Some("Returns a*/ value."), ""),
            "/** Returns a*\\/ value. */\n"
        );
    }

    #[test]
    fn render_jsdoc_long_single_line_uses_block_format() {
        // 76+ chars on the line itself should spill into block format to stay under 80
        let doc = "This is a very long docstring that exceeds the eighty character threshold.";
        let result = render_jsdoc(Some(doc), "");
        assert!(
            result.starts_with("/**\n"),
            "expected block format, got: {result}"
        );
    }

    // -----------------------------------------------------------------------
    // render_literal tests
    // -----------------------------------------------------------------------

    #[test]
    fn render_literal_boolean() {
        assert_eq!(render_literal(&Literal::Boolean(true)), "true");
        assert_eq!(render_literal(&Literal::Boolean(false)), "false");
    }

    #[test]
    fn render_literal_string() {
        assert_eq!(render_literal(&Literal::String("hello".into())), "'hello'");
        // Escapes single quotes and backslashes
        assert_eq!(
            render_literal(&Literal::String("it's a \\path".into())),
            "'it\\'s a \\\\path'"
        );
    }

    #[test]
    fn render_literal_uint() {
        // Small uint → plain number
        assert_eq!(
            render_literal(&Literal::UInt(
                42,
                uniffi_bindgen::interface::Radix::Decimal,
                Type::UInt32
            )),
            "42"
        );
        // u64 → bigint suffix
        assert_eq!(
            render_literal(&Literal::UInt(
                100,
                uniffi_bindgen::interface::Radix::Decimal,
                Type::UInt64
            )),
            "100n"
        );
        // i64 → bigint suffix
        assert_eq!(
            render_literal(&Literal::UInt(
                7,
                uniffi_bindgen::interface::Radix::Decimal,
                Type::Int64
            )),
            "7n"
        );
    }

    #[test]
    fn render_literal_int() {
        assert_eq!(
            render_literal(&Literal::Int(
                -5,
                uniffi_bindgen::interface::Radix::Decimal,
                Type::Int32
            )),
            "-5"
        );
        assert_eq!(
            render_literal(&Literal::Int(
                -99,
                uniffi_bindgen::interface::Radix::Decimal,
                Type::Int64
            )),
            "-99n"
        );
    }

    #[test]
    fn render_literal_float() {
        assert_eq!(
            render_literal(&Literal::Float("3.14".into(), Type::Float64)),
            "3.14"
        );
    }

    #[test]
    fn render_literal_enum() {
        assert_eq!(
            render_literal(&Literal::Enum("North".into(), Type::String)),
            "'North'"
        );
    }

    #[test]
    fn render_literal_empty_sequence() {
        assert_eq!(render_literal(&Literal::EmptySequence), "[]");
    }

    #[test]
    fn render_literal_empty_map() {
        assert_eq!(render_literal(&Literal::EmptyMap), "new Map()");
    }

    #[test]
    fn render_literal_none() {
        assert_eq!(render_literal(&Literal::None), "null");
    }

    #[test]
    fn render_literal_some() {
        assert_eq!(
            render_literal(&Literal::Some {
                inner: Box::new(DefaultValue::Literal(Literal::String("x".into())))
            }),
            "'x'"
        );
    }

    // -----------------------------------------------------------------------
    // render_param tests
    // -----------------------------------------------------------------------

    #[test]
    fn render_param_no_default() {
        let arg = UdlArg {
            name: "user_name".into(),
            type_: Type::String,
            default: None,
        };
        assert_eq!(render_param(&arg), "userName: string");
    }

    #[test]
    fn render_param_literal_default() {
        let arg = UdlArg {
            name: "count".into(),
            type_: Type::Int32,
            default: Some(DefaultValue::Literal(Literal::UInt(
                0,
                uniffi_bindgen::interface::Radix::Decimal,
                Type::Int32,
            ))),
        };
        assert_eq!(render_param(&arg), "count: number = 0");
    }

    #[test]
    fn render_param_unspecified_default() {
        let arg = UdlArg {
            name: "label".into(),
            type_: Type::String,
            default: Some(DefaultValue::Default),
        };
        assert_eq!(render_param(&arg), "label?: string");
    }

    // -----------------------------------------------------------------------
    // ts_return_type tests
    // -----------------------------------------------------------------------

    #[test]
    fn ts_return_type_sync_void() {
        assert_eq!(ts_return_type(None, false), "void");
    }

    #[test]
    fn ts_return_type_async_void() {
        assert_eq!(ts_return_type(None, true), "Promise<void>");
    }

    #[test]
    fn ts_return_type_sync_string() {
        assert_eq!(ts_return_type(Some(&Type::String), false), "string");
    }

    #[test]
    fn ts_return_type_async_string() {
        assert_eq!(ts_return_type(Some(&Type::String), true), "Promise<string>");
    }

    // -----------------------------------------------------------------------
    // render_call_body tests
    // -----------------------------------------------------------------------

    #[test]
    fn render_call_body_no_throws_no_preamble_with_return() {
        assert_eq!(
            render_call_body("foo()", true, None, None),
            " return foo(); "
        );
    }

    #[test]
    fn render_call_body_no_throws_no_preamble_no_return() {
        assert_eq!(render_call_body("foo()", false, None, None), " foo(); ");
    }

    #[test]
    fn render_call_body_no_throws_with_preamble_with_return() {
        let body = render_call_body("foo()", true, None, Some("this._assertLive();"));
        assert_eq!(body, "\n    this._assertLive();\n    return foo();\n  ");
    }

    #[test]
    fn render_call_body_no_throws_with_preamble_no_return() {
        let body = render_call_body("foo()", false, None, Some("this._assertLive();"));
        assert_eq!(body, "\n    this._assertLive();\n    foo();\n  ");
    }

    #[test]
    fn render_call_body_throws_no_preamble_with_return() {
        let body = render_call_body("foo()", true, Some("MyError"), None);
        assert_eq!(
            body,
            "\n    try { return foo(); } catch (e) { return _liftMyError(e); }\n  "
        );
    }

    #[test]
    fn render_call_body_throws_no_preamble_no_return() {
        let body = render_call_body("foo()", false, Some("MyError"), None);
        assert_eq!(
            body,
            "\n    try { foo(); } catch (e) { _liftMyError(e); }\n  "
        );
    }

    #[test]
    fn render_call_body_throws_with_preamble_with_return() {
        let body = render_call_body("foo()", true, Some("MyError"), Some("this._assertLive();"));
        assert_eq!(
            body,
            "\n    this._assertLive();\n    try { return foo(); } catch (e) { return _liftMyError(e); }\n  "
        );
    }

    #[test]
    fn render_call_body_throws_with_preamble_no_return() {
        let body = render_call_body("foo()", false, Some("MyError"), Some("this._assertLive();"));
        assert_eq!(
            body,
            "\n    this._assertLive();\n    try { foo(); } catch (e) { _liftMyError(e); }\n  "
        );
    }

    // -----------------------------------------------------------------------
    // lift_return tests for Optional<Object> and Sequence<Object>
    // -----------------------------------------------------------------------

    const LC: &str = LOCAL_CRATE_SENTINEL;

    #[test]
    fn lift_return_optional_object_sync() {
        let result = lift_return(
            "__bg.find_item()",
            Some(&Type::Optional {
                inner_type: Box::new(Type::Object {
                    name: "Item".into(),
                    module_path: "crate_name::mod".into(),
                    imp: uniffi_bindgen::interface::ObjectImpl::Struct,
                }),
            }),
            false,
            LC,
        );
        assert_eq!(
            result,
            "((__v) => __v == null ? null : Item._fromInner(__v))(__bg.find_item())"
        );
    }

    #[test]
    fn lift_return_optional_object_async() {
        let result = lift_return(
            "__bg.find_item()",
            Some(&Type::Optional {
                inner_type: Box::new(Type::Object {
                    name: "Item".into(),
                    module_path: "crate_name::mod".into(),
                    imp: uniffi_bindgen::interface::ObjectImpl::Struct,
                }),
            }),
            true,
            LC,
        );
        assert_eq!(
            result,
            "((__v) => __v == null ? null : Item._fromInner(__v))(await __bg.find_item())"
        );
    }

    #[test]
    fn lift_return_sequence_object_sync() {
        let result = lift_return(
            "__bg.list_items()",
            Some(&Type::Sequence {
                inner_type: Box::new(Type::Object {
                    name: "Item".into(),
                    module_path: "crate_name::mod".into(),
                    imp: uniffi_bindgen::interface::ObjectImpl::Struct,
                }),
            }),
            false,
            LC,
        );
        assert_eq!(
            result,
            "(__bg.list_items()).map((__v) => Item._fromInner(__v))"
        );
    }

    #[test]
    fn lift_return_sequence_object_async() {
        let result = lift_return(
            "__bg.list_items()",
            Some(&Type::Sequence {
                inner_type: Box::new(Type::Object {
                    name: "Item".into(),
                    module_path: "crate_name::mod".into(),
                    imp: uniffi_bindgen::interface::ObjectImpl::Struct,
                }),
            }),
            true,
            LC,
        );
        assert_eq!(
            result,
            "(await __bg.list_items()).map((__v) => Item._fromInner(__v))"
        );
    }

    #[test]
    fn lift_return_external_object_not_lifted() {
        let result = lift_return(
            "__bg.get_ext()",
            Some(&Type::Object {
                name: "ExtObj".into(),
                module_path: "other_crate::mod".into(),
                imp: uniffi_bindgen::interface::ObjectImpl::Struct,
            }),
            false,
            LC,
        );
        assert_eq!(result, "__bg.get_ext()");
    }

    // -----------------------------------------------------------------------
    // lift_return: Map<K, Object> and nested types
    // -----------------------------------------------------------------------

    fn local_object(name: &str) -> Type {
        Type::Object {
            name: name.into(),
            module_path: "crate_name::mod".into(),
            imp: uniffi_bindgen::interface::ObjectImpl::Struct,
        }
    }

    #[test]
    fn lift_return_map_string_object_sync() {
        let result = lift_return(
            "__bg.get_map()",
            Some(&Type::Map {
                key_type: Box::new(Type::String),
                value_type: Box::new(local_object("Item")),
            }),
            false,
            LC,
        );
        assert_eq!(
            result,
            "new Map([...__bg.get_map()].map(([__k, __v]) => [__k, Item._fromInner(__v)]))"
        );
    }

    #[test]
    fn lift_return_map_string_object_async() {
        let result = lift_return(
            "__bg.get_map()",
            Some(&Type::Map {
                key_type: Box::new(Type::String),
                value_type: Box::new(local_object("Item")),
            }),
            true,
            LC,
        );
        assert_eq!(
            result,
            "new Map([...await __bg.get_map()].map(([__k, __v]) => [__k, Item._fromInner(__v)]))"
        );
    }

    #[test]
    fn lift_return_optional_sequence_object() {
        let result = lift_return(
            "__bg.maybe_list()",
            Some(&Type::Optional {
                inner_type: Box::new(Type::Sequence {
                    inner_type: Box::new(local_object("Item")),
                }),
            }),
            false,
            LC,
        );
        assert_eq!(
            result,
            "((__v) => __v == null ? null : (__v).map((__v) => Item._fromInner(__v)))(__bg.maybe_list())"
        );
    }

    #[test]
    fn lift_return_sequence_optional_object() {
        let result = lift_return(
            "__bg.list_maybe()",
            Some(&Type::Sequence {
                inner_type: Box::new(Type::Optional {
                    inner_type: Box::new(local_object("Item")),
                }),
            }),
            false,
            LC,
        );
        assert_eq!(
            result,
            "(__bg.list_maybe()).map((__v) => ((__v) => __v == null ? null : Item._fromInner(__v))(__v))"
        );
    }

    #[test]
    fn lift_return_no_lifting_for_plain_types() {
        assert_eq!(
            lift_return("__bg.foo()", Some(&Type::String), false, LC),
            "__bg.foo()"
        );
        assert_eq!(
            lift_return(
                "__bg.foo()",
                Some(&Type::Map {
                    key_type: Box::new(Type::String),
                    value_type: Box::new(Type::Int32),
                }),
                false,
                LC
            ),
            "__bg.foo()"
        );
    }

    #[test]
    fn needs_object_lifting_detects_nested() {
        assert!(needs_object_lifting(&local_object("Foo"), LC));
        assert!(needs_object_lifting(
            &Type::Optional {
                inner_type: Box::new(local_object("Foo"))
            },
            LC
        ));
        assert!(needs_object_lifting(
            &Type::Sequence {
                inner_type: Box::new(local_object("Foo"))
            },
            LC
        ));
        assert!(needs_object_lifting(
            &Type::Map {
                key_type: Box::new(Type::String),
                value_type: Box::new(local_object("Foo")),
            },
            LC
        ));
        assert!(!needs_object_lifting(&Type::String, LC));
        assert!(!needs_object_lifting(
            &Type::Map {
                key_type: Box::new(Type::String),
                value_type: Box::new(Type::Int32),
            },
            LC
        ));
    }

    // -----------------------------------------------------------------------
    // render_enum_methods_on_class tests
    // -----------------------------------------------------------------------

    fn make_method(name: &str, return_type: Option<Type>, is_async: bool) -> UdlMethod {
        UdlMethod {
            name: name.into(),
            args: vec![],
            return_type,
            throws_type: None,
            is_async,
            docstring: None,
        }
    }

    #[test]
    fn render_enum_methods_on_class_instance_method() {
        let methods = vec![make_method("describe", Some(Type::String), false)];
        let cfg = config::JsBindingsConfig::default();
        let result = render_enum_methods_on_class(&methods, "StatusCode", &cfg, LC);
        assert!(
            result.contains("describe(): string { return __bg.status_code_describe(this); }"),
            "got: {result}"
        );
    }

    #[test]
    fn render_enum_methods_on_class_async_method() {
        let methods = vec![make_method("process", None, true)];
        let cfg = config::JsBindingsConfig::default();
        let result = render_enum_methods_on_class(&methods, "Task", &cfg, LC);
        assert!(
            result.contains("async process(): Promise<void>"),
            "got: {result}"
        );
    }

    // -----------------------------------------------------------------------
    // render_enum_type companion namespace tests
    // -----------------------------------------------------------------------

    #[test]
    fn render_enum_type_with_methods_has_companion_namespace() {
        let e = UdlEnum {
            name: "Shape".into(),
            variants: vec![UdlVariant {
                name: "Circle".into(),
                fields: vec![],
                docstring: None,
                discr: None,
            }],
            is_flat: true,
            is_non_exhaustive: false,
            docstring: None,
            methods: vec![make_method("area", Some(Type::Float64), false)],
            constructors: vec![],
        };
        let cfg = config::JsBindingsConfig::default();
        let result = render_enum_type(&e, &cfg, LC);
        assert!(
            result.contains("export type Shape = 'Circle';"),
            "got: {result}"
        );
        assert!(result.contains("export namespace Shape {"), "got: {result}");
        assert!(
            result.contains(
                "export function area(self: Shape): number { return __bg.shape_area(self); }"
            ),
            "got: {result}"
        );
    }

    #[test]
    fn render_enum_type_without_methods_no_namespace() {
        let e = UdlEnum {
            name: "Dir".into(),
            variants: vec![UdlVariant {
                name: "Up".into(),
                fields: vec![],
                docstring: None,
                discr: None,
            }],
            is_flat: true,
            is_non_exhaustive: false,
            docstring: None,
            methods: vec![],
            constructors: vec![],
        };
        let cfg = config::JsBindingsConfig::default();
        let result = render_enum_type(&e, &cfg, LC);
        assert!(!result.contains("namespace"), "got: {result}");
    }

    // -----------------------------------------------------------------------
    // pascal_case edge case
    // -----------------------------------------------------------------------

    #[test]
    fn pascal_case_empty_returns_fallback() {
        assert_eq!(pascal_case(""), "UniffiBindings");
    }

    // -----------------------------------------------------------------------
    // ts_type_str: Sequence<Optional<T>> parenthesization
    // -----------------------------------------------------------------------

    #[test]
    fn sequence_of_optional_parenthesized() {
        let t = Type::Sequence {
            inner_type: Box::new(Type::Optional {
                inner_type: Box::new(Type::String),
            }),
        };
        assert_eq!(ts_type_str(&t), "(string | null)[]");
    }

    #[test]
    fn sequence_of_plain_not_parenthesized() {
        let t = Type::Sequence {
            inner_type: Box::new(Type::String),
        };
        assert_eq!(ts_type_str(&t), "string[]");
    }

    // -----------------------------------------------------------------------
    // Generator error-path tests
    // -----------------------------------------------------------------------

    #[test]
    fn missing_external_package_errors_for_object() {
        let metadata = UdlMetadata {
            functions: vec![UdlFunction {
                name: "get_ext".into(),
                args: vec![],
                return_type: Some(Type::Object {
                    name: "ExtObj".into(),
                    module_path: "other_crate::mod".into(),
                    imp: uniffi_bindgen::interface::ObjectImpl::Struct,
                }),
                throws_type: None,
                is_async: false,
                docstring: None,
            }],
            ..Default::default()
        };
        let empty_packages = HashMap::new();
        let result = collect_external_imports(&metadata, &empty_packages, LC);
        assert!(result.is_err());
        let msg = result.unwrap_err().to_string();
        assert!(
            msg.contains("external_packages"),
            "error should mention external_packages, got: {msg}"
        );
        assert!(
            msg.contains("other_crate"),
            "error should mention the crate name, got: {msg}"
        );
    }

    #[test]
    fn missing_external_package_errors_for_custom_type() {
        let metadata = UdlMetadata {
            custom_types: vec![UdlCustomType {
                name: "RemoteUrl".into(),
                builtin: Type::String,
                module_path: "remote_crate::types".into(),
            }],
            ..Default::default()
        };
        let empty_packages = HashMap::new();
        let result = collect_external_imports(&metadata, &empty_packages, LC);
        assert!(result.is_err());
        let msg = result.unwrap_err().to_string();
        assert!(
            msg.contains("remote_crate"),
            "error should mention the crate name, got: {msg}"
        );
    }

    #[test]
    fn external_package_with_config_succeeds() {
        let metadata = UdlMetadata {
            functions: vec![UdlFunction {
                name: "get_ext".into(),
                args: vec![],
                return_type: Some(Type::Object {
                    name: "ExtObj".into(),
                    module_path: "other_crate::mod".into(),
                    imp: uniffi_bindgen::interface::ObjectImpl::Struct,
                }),
                throws_type: None,
                is_async: false,
                docstring: None,
            }],
            ..Default::default()
        };
        let mut packages = HashMap::new();
        packages.insert("other_crate".into(), "./other.js".into());
        let result = collect_external_imports(&metadata, &packages, LC);
        assert!(result.is_ok());
        let imports = result.unwrap();
        assert!(imports.contains_key("./other.js"));
        assert!(imports["./other.js"].contains("ExtObj"));
    }

    // -----------------------------------------------------------------------
    // [NonExhaustive] enum/error tests
    // -----------------------------------------------------------------------

    #[test]
    fn non_exhaustive_flat_enum_appends_string_catchall() {
        let e = UdlEnum {
            name: "Status".into(),
            variants: vec![
                UdlVariant {
                    name: "Active".into(),
                    fields: vec![],
                    docstring: None,
                    discr: None,
                },
                UdlVariant {
                    name: "Inactive".into(),
                    fields: vec![],
                    docstring: None,
                    discr: None,
                },
            ],
            is_flat: true,
            is_non_exhaustive: true,
            docstring: None,
            methods: vec![],
            constructors: vec![],
        };
        let cfg = config::JsBindingsConfig::default();
        let result = render_enum_type(&e, &cfg, LC);
        assert!(
            result.contains("export type Status = 'Active' | 'Inactive' | string;"),
            "got: {result}"
        );
    }

    #[test]
    fn non_exhaustive_data_enum_appends_tag_string_catchall() {
        let e = UdlEnum {
            name: "Shape".into(),
            variants: vec![UdlVariant {
                name: "Circle".into(),
                fields: vec![UdlField {
                    name: "radius".into(),
                    type_: Type::Float64,
                    docstring: None,
                    default: None,
                }],
                docstring: None,
                discr: None,
            }],
            is_flat: false,
            is_non_exhaustive: true,
            docstring: None,
            methods: vec![],
            constructors: vec![],
        };
        let cfg = config::JsBindingsConfig::default();
        let result = render_enum_type(&e, &cfg, LC);
        assert!(
            result.contains("| { tag: 'Circle', radius: number }"),
            "got: {result}"
        );
        assert!(
            result.contains("| { tag: string; [key: string]: unknown };"),
            "got: {result}"
        );
    }

    #[test]
    fn non_exhaustive_flat_error_appends_string_tag() {
        let e = UdlError {
            name: "AppError".into(),
            variants: vec![UdlVariant {
                name: "NotFound".into(),
                fields: vec![],
                docstring: None,
                discr: None,
            }],
            is_flat: true,
            is_non_exhaustive: true,
            docstring: None,
            methods: vec![],
            constructors: vec![],
        };
        let cfg = config::JsBindingsConfig::default();
        let result = render_error_class(&e, &cfg, LC);
        assert!(result.contains("tag: 'NotFound' | string"), "got: {result}");
    }

    #[test]
    fn non_exhaustive_rich_error_appends_catchall_variant() {
        let e = UdlError {
            name: "NetError".into(),
            variants: vec![UdlVariant {
                name: "Timeout".into(),
                fields: vec![UdlField {
                    name: "elapsed_ms".into(),
                    type_: Type::UInt32,
                    docstring: None,
                    default: None,
                }],
                docstring: None,
                discr: None,
            }],
            is_flat: false,
            is_non_exhaustive: true,
            docstring: None,
            methods: vec![],
            constructors: vec![],
        };
        let cfg = config::JsBindingsConfig::default();
        let result = render_error_class(&e, &cfg, LC);
        assert!(
            result.contains("| { tag: string; [key: string]: unknown };"),
            "got: {result}"
        );
    }

    #[test]
    fn non_exhaustive_flat_error_lift_has_fallback() {
        let e = UdlError {
            name: "AppError".into(),
            variants: vec![UdlVariant {
                name: "NotFound".into(),
                fields: vec![],
                docstring: None,
                discr: None,
            }],
            is_flat: true,
            is_non_exhaustive: true,
            docstring: None,
            methods: vec![],
            constructors: vec![],
        };
        let result = render_lift_fn(&e);
        assert!(
            result.contains("if (typeof tag === 'string') throw new AppError(tag);"),
            "got: {result}"
        );
    }

    #[test]
    fn non_exhaustive_rich_error_lift_has_fallback() {
        let e = UdlError {
            name: "NetError".into(),
            variants: vec![UdlVariant {
                name: "Timeout".into(),
                fields: vec![],
                docstring: None,
                discr: None,
            }],
            is_flat: false,
            is_non_exhaustive: true,
            docstring: None,
            methods: vec![],
            constructors: vec![],
        };
        let result = render_lift_fn(&e);
        assert!(
            result.contains(
                "if (typeof tag === 'string') throw new NetError(raw as NetErrorVariant);"
            ),
            "got: {result}"
        );
    }

    #[test]
    fn local_types_not_treated_as_external() {
        let metadata = UdlMetadata {
            functions: vec![UdlFunction {
                name: "get_local".into(),
                args: vec![],
                return_type: Some(Type::Object {
                    name: "LocalObj".into(),
                    module_path: "crate_name::mod".into(),
                    imp: uniffi_bindgen::interface::ObjectImpl::Struct,
                }),
                throws_type: None,
                is_async: false,
                docstring: None,
            }],
            ..Default::default()
        };
        let empty_packages = HashMap::new();
        let result = collect_external_imports(&metadata, &empty_packages, LC);
        assert!(result.is_ok());
        assert!(result.unwrap().is_empty());
    }

    // -----------------------------------------------------------------------
    // Enum constructor tests
    // -----------------------------------------------------------------------

    fn make_ctor(name: &str, args: Vec<UdlArg>) -> UdlConstructor {
        UdlConstructor {
            name: name.into(),
            args,
            throws_type: None,
            is_async: false,
            docstring: None,
        }
    }

    #[test]
    fn enum_constructors_rendered_in_companion_namespace() {
        let e = UdlEnum {
            name: "Color".into(),
            variants: vec![UdlVariant {
                name: "Red".into(),
                fields: vec![],
                docstring: None,
                discr: None,
            }],
            is_flat: true,
            is_non_exhaustive: false,
            docstring: None,
            methods: vec![],
            constructors: vec![make_ctor(
                "from_hex",
                vec![UdlArg {
                    name: "hex".into(),
                    type_: Type::String,
                    default: None,
                }],
            )],
        };
        let cfg = config::JsBindingsConfig::default();
        let result = render_enum_type(&e, &cfg, LC);
        assert!(result.contains("export namespace Color {"), "got: {result}");
        assert!(
            result.contains(
                "export function fromHex(hex: string): Color { return __bg.color_from_hex(hex); }"
            ),
            "got: {result}"
        );
    }

    #[test]
    fn flat_enum_with_discriminants_emits_values_object() {
        let e = UdlEnum {
            name: "Priority".into(),
            variants: vec![
                UdlVariant {
                    name: "Low".into(),
                    fields: vec![],
                    docstring: None,
                    discr: Some(Literal::UInt(
                        1,
                        uniffi_bindgen::interface::Radix::Decimal,
                        Type::UInt8,
                    )),
                },
                UdlVariant {
                    name: "Medium".into(),
                    fields: vec![],
                    docstring: None,
                    discr: Some(Literal::UInt(
                        5,
                        uniffi_bindgen::interface::Radix::Decimal,
                        Type::UInt8,
                    )),
                },
                UdlVariant {
                    name: "High".into(),
                    fields: vec![],
                    docstring: None,
                    discr: Some(Literal::UInt(
                        10,
                        uniffi_bindgen::interface::Radix::Decimal,
                        Type::UInt8,
                    )),
                },
            ],
            is_flat: true,
            is_non_exhaustive: false,
            docstring: None,
            methods: vec![],
            constructors: vec![],
        };
        let cfg = config::JsBindingsConfig::default();
        let result = render_enum_type(&e, &cfg, LC);
        assert!(
            result.contains("export const PriorityValues = {"),
            "expected Values object, got:\n{result}"
        );
        assert!(
            result.contains("Low: 1,"),
            "expected Low: 1, got:\n{result}"
        );
        assert!(
            result.contains("Medium: 5,"),
            "expected Medium: 5, got:\n{result}"
        );
        assert!(
            result.contains("High: 10,"),
            "expected High: 10, got:\n{result}"
        );
        assert!(
            result.contains("} as const;"),
            "expected as const, got:\n{result}"
        );
    }

    #[test]
    fn flat_enum_without_discriminants_omits_values_object() {
        let e = UdlEnum {
            name: "Color".into(),
            variants: vec![
                UdlVariant {
                    name: "Red".into(),
                    fields: vec![],
                    docstring: None,
                    discr: None,
                },
                UdlVariant {
                    name: "Green".into(),
                    fields: vec![],
                    docstring: None,
                    discr: None,
                },
            ],
            is_flat: true,
            is_non_exhaustive: false,
            docstring: None,
            methods: vec![],
            constructors: vec![],
        };
        let cfg = config::JsBindingsConfig::default();
        let result = render_enum_type(&e, &cfg, LC);
        assert!(
            !result.contains("Values"),
            "should not have Values object, got:\n{result}"
        );
    }

    #[test]
    fn error_constructors_rendered_as_static_methods() {
        let e = UdlError {
            name: "AppError".into(),
            variants: vec![UdlVariant {
                name: "Generic".into(),
                fields: vec![],
                docstring: None,
                discr: None,
            }],
            is_flat: true,
            is_non_exhaustive: false,
            docstring: None,
            methods: vec![],
            constructors: vec![make_ctor(
                "from_code",
                vec![UdlArg {
                    name: "code".into(),
                    type_: Type::Int32,
                    default: None,
                }],
            )],
        };
        let cfg = config::JsBindingsConfig::default();
        let result = render_error_class(&e, &cfg, LC);
        assert!(
            result.contains("static fromCode(code: number): AppError { return __bg.app_error_from_code(code); }"),
            "got: {result}"
        );
    }

    #[test]
    fn enum_with_constructors_and_methods_has_both() {
        let e = UdlEnum {
            name: "Shape".into(),
            variants: vec![UdlVariant {
                name: "Circle".into(),
                fields: vec![],
                docstring: None,
                discr: None,
            }],
            is_flat: true,
            is_non_exhaustive: false,
            docstring: None,
            methods: vec![make_method("area", Some(Type::Float64), false)],
            constructors: vec![make_ctor(
                "parse",
                vec![UdlArg {
                    name: "s".into(),
                    type_: Type::String,
                    default: None,
                }],
            )],
        };
        let cfg = config::JsBindingsConfig::default();
        let result = render_enum_type(&e, &cfg, LC);
        assert!(result.contains("export namespace Shape {"), "got: {result}");
        assert!(result.contains("export function parse("), "got: {result}");
        assert!(result.contains("export function area("), "got: {result}");
    }
}
