use crate::cli::GenerateArgs;
use anyhow::{Context, Result};
use serde::Deserialize;
use std::fs;
use std::path::Path;

#[derive(Debug, Default, Deserialize)]
struct RootConfig {
    bindings: Option<Bindings>,
}

#[derive(Debug, Default, Deserialize)]
struct Bindings {
    js: Option<JsConfig>,
}

#[derive(Debug, Default, Deserialize)]
struct JsConfig {
    module_name: Option<String>,
}

pub fn generate_bindings(args: &GenerateArgs) -> Result<()> {
    let module_name = resolve_module_name(args)?;
    let out_file = args
        .out_dir
        .join(format!("{}.ts", module_name.to_lowercase()));

    fs::create_dir_all(&args.out_dir)
        .with_context(|| format!("failed to create output dir {}", args.out_dir.display()))?;

    let content = render_stub(&module_name, &args.source);
    fs::write(&out_file, content)
        .with_context(|| format!("failed to write {}", out_file.display()))?;

    Ok(())
}

fn resolve_module_name(args: &GenerateArgs) -> Result<String> {
    if let Some(config_path) = &args.config {
        if config_path.exists() {
            let raw = fs::read_to_string(config_path)
                .with_context(|| format!("failed to read {}", config_path.display()))?;
            let parsed: RootConfig = toml::from_str(&raw)
                .with_context(|| format!("failed to parse {}", config_path.display()))?;
            if let Some(name) = parsed
                .bindings
                .and_then(|b| b.js)
                .and_then(|j| j.module_name)
            {
                return Ok(name);
            }
        }
    }

    Ok(stem_or_default(&args.source, "uniffi_bindings"))
}

fn stem_or_default(path: &Path, default: &str) -> String {
    path.file_stem()
        .and_then(|s| s.to_str())
        .map(ToOwned::to_owned)
        .unwrap_or_else(|| default.to_string())
}

fn render_stub(module_name: &str, _source: &Path) -> String {
    format!(
        "// Generated by uniffi-bindgen-js\n// Source: <udl>\n\nexport namespace {} {{\n  // TODO: implement full UniFFI JS/TS bindings generation\n}}\n",
        pascal_case(module_name),
    )
}

fn pascal_case(input: &str) -> String {
    let mut out = String::new();
    for part in input.split(['_', '-']) {
        if part.is_empty() {
            continue;
        }
        let mut chars = part.chars();
        if let Some(first) = chars.next() {
            out.push(first.to_ascii_uppercase());
            out.push_str(chars.as_str());
        }
    }
    if out.is_empty() {
        "UniffiBindings".to_string()
    } else {
        out
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn pascal_case_handles_common_cases() {
        assert_eq!(pascal_case("simple_bindings"), "SimpleBindings");
        assert_eq!(pascal_case("simple-bindings"), "SimpleBindings");
    }
}
